HerculesWS/Hercules

npc/re/quests/quests_eclage.txt
I think the quest progress check is incorrect.
should be these 4 quests I believe.
> 7423,0,0,0,0,0,0,0,"A rumor about the King 1"
> 7424,0,0,0,0,0,0,0,"A rumor about the King 2"
> 7425,0,0,0,0,0,0,0,"A rumor about the King 3"
> 7426,0,0,0,0,0,0,0,"A rumor about the King 4"
=> Incorrect quest progress checking.

src/char/int_mail.c, src/common/HPM.c, src/map/unit.c
@MishimaHaruna @Michieru 
Please review it.
=> Fixes Compile Error on Windows

src/map/battle.c, src/map/clif.c, src/map/clif.h, src/map/map.h, src/map/pc.c, src/map/pc.h, src/map/skill.c, src/map/status.c, src/map/unit.c
Please do not merge (it's still a work in progress). I'm opening this just for discussion.
=> Cleaned up spirit charms implementation

src/map/battle.c
=> Missing break in skill

src/map/status.c
It was giving too much def. Adjusted and confirmed with malufett
=> Fixing Prestige formula

db/re/item_db.conf
Item Details are from itemInfo.lua (Provided by kRO)
More Detail of this file: http://hercules.ws/board/topic/8552-new-costume-headgear-db/
Contains almost all costumes from iteminfo.lua
Credits to @zackdreaver for sharing the db file on the board.
=> Updated item_db with New Costume's

src/common/HPMi.h, src/map/HPMmap.c, src/map/battleground.c, src/map/battleground.h
@MishimaHaruna , Can you review this?
=> Battleground Data to HPM Struct

npc/re/quests/eden/100-110.txt, npc/re/quests/eden/111-120.txt, npc/re/quests/eden/121-130.txt, npc/re/quests/eden/131-140.txt, npc/re/quests/eden/eden_quests.txt, npc/re/scripts.conf
=> Eden Scripts

npc/instances/EndlessTower.txt
http://hercules.ws/board/tracker/issue-8590-endless-tower-possible-bu/
=> Fixed Endless Tower weekly timer issue 

db/re/item_combo_db.txt, db/re/item_db.conf
List of changed : 
- Added new costume garments
- Added new costume headgears
- Added new footgears
- Added new accessories
- Added new shields
- Added new weapons
- Added 'Thanatos' weapons pack
- Added 'Crimson' weapons pack
- Added 'Vicious Mind' weapons pack
- Added Shadow equipments
- Fixed bug 8563
=> Added new items DB and script fixes

db/re/item_combo_db.txt, db/re/item_db.conf, npc/cities/prontera.txt, npc/kafras/dts_warper.txt
Please check the script before merge.
=> Added new items DB and corrected scripts (part 2)

db/re/item_combo_db.txt, db/re/item_db.conf, npc/re/quests/eden/eden_quests.txt
Please check the script before merge.
=> Added new items DB and corrected scripts (part 3)

db/re/item_db.conf
=> Fix items DB script

src/map/pc.c
Dont show use error if item with KeepAfterUse attribute
From pc_equipitem/pc_unequipitem return actual state is action was success or not.
=> Small fixed for pc.c

src/char/int_auction.c, src/char/int_guild.c
Introduced on: dab1fba3a88b9c5e86a778a29bd4d565fc937155
=> Fixed some compiling errors under MSVC

db/re/item_db.conf
Please check the scripts before merge.
=> Added new items DB and corrected scripts (part 4)

db/re/item_db.conf
Data from itemmoveinfov5.txt is been used as reference.
Thanks to Rytech for giving us the hint that the file is been put on client.
@MishimaHaruna @Streusel @malufett 
If anyone want to review it?
Else I will merge it in few days, if there's no problem with it.
=> Item Restrictions Updated to match info from kRO

db/re/item_db.conf
http://hercules.ws/board/tracker/issue-8653-parasite-and-harpy-card/
=> Fix bug 8653

src/map/atcommand.c
The comment is right, but the wrong message number is there
=> Typo when setting JoinAnnounce for channels

db/re/item_db.conf
http://hercules.ws/board/tracker/issue-8665-tidungs-script-damage-reduction/
=> Fixed Bug#8665

db/quest_db.conf
Fixed bug#8692
http://hercules.ws/board/tracker/issue-8692-eden-quests-111-120/
=> Fix timer for Eden quest 110+

src/map/atcommand.c, src/map/pc.c
A small bug in VS with the new function created by malufett.
Also resolved some of Mashima's FIXMEs.
Hope they help you.
=> Some small follow ups

npc/re/jobs/3-2/sura.txt
The quest worked fine on the first try. But the loop would break after that and only 1 person could do the quest per server restart. This small edit slightly adjusts the loop so it works as intended.
=> Sura quest fix

src/char/char.c, src/char/int_guild.c, src/char/int_homun.c, src/char/int_mail.c, src/char/inter.c, src/char/pincode.c, src/login/account_sql.c, src/login/login.c, src/map/battle.c, src/map/clif.c, src/map/skill.c, src/map/status.c
This checks was found by special tool. It cant find all issues, but can find some atleast.
Login and char server i checked before by hands.
=> Add missing check to login and char server and remove useless checks from char and map servers

src/map/script.c
Signed-off-by: Angelmelody <Angelmelody@gmail.com>
=> Follow up 98274e4 fix script command questactive warnings

src/map/clif.c, src/map/pc.c, src/map/pc.h, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
This remove code duplicates and improve a bit code.
=> Move cards checks related code into separate functions.

src/map/itemdb.c
This fixes the script loading issue mentioned here -> http://herc.ws/board/topic/10249-issue-with-item-db-after-update/
=> Fix script loading via sql in itemdb.c

src/map/clif.c, src/map/clif.h, src/map/packets.h, src/map/packets_struct.h
Thanks to Rytech and 3CeAM
Uses 0 as data, till we know exactly know how item gets those optionData..
@MishimaHaruna Reviews?
=> New EquipPackets Support

sql-files/main.sql, sql-files/upgrades/2015-08-27--20-42.sql, src/char/char.c, src/common/mmo.h, src/map/clif.c, src/map/clif.h, src/map/packets.h, src/map/packets_struct.h
This is feature for client 2014-10-22 and greater..
@4144 @MishimaHaruna 
I have tested(in game), and it works,
just wanted to let you review the code, before its been pushed to master.
=> Hotkey Rotate Packet Implemented

src/common/HPMi.h, src/map/HPMmap.c, src/map/pc.c, src/map/pc.h
Updated Autotrade Struct (Previous PR: #451 , it was difficult to update the old branch, so I just delete and created new)
also didn't saw that I have opened PR to update that minor thing :P
=> Autotrade Struct to HPM

src/map/script.c
Was broken in previous commits.
=> Fix script command checkcell without player attached.

src/map/battle.c, src/map/status.c
=> Corrected critical bonus display

npc/quests/first_class/tu_sword.txt
issue #008561 (from old tracker)
=> Fix quest log linking in first_class/tu_sword.txt

npc/quests/first_class/tu_merchant.txt
Fixes quest log linking and a wrong check that was blocking players who had level 10 increase weight limit to continue the quest.
Also from issue #008561 from the old tracker
=> Fix quests/first_class/tu_merchant.txt

src/map/battle.c
Bug Report: https://github.com/HerculesWS/Hercules/issues/731
=> Fixes Maelstrom crashing server

db/re/item_db.conf, npc/custom/events/mushroom_event.txt, npc/custom/quests/may_hats.txt, npc/re/quests/eden/eden_iro.txt
Added Items needed in eden_iro.txt
Changed NPC id->constant in eden_iro.txt
Fixed case warning errors on may_hats.txt and mushroom_event.txt
=> Added needed items and some npc fixes in Eden and other events

doc/script_commands.txt, src/map/script.c
* Added Missing ScriptCommands in the doc.
* Corrected sleep/sleep2 parameter list.
* Changed bg_join_team return values.
=> Updated script_commands.txt

db/pre-re/item_db.conf, db/re/item_db.conf
- Update Flame Stone, Ice Stone, Wind Stone, and Shadow Orb selling price in Renewal base on kRO.
- Update 'Mother_Heart' item effect. (Ref: http://www.divine-pride.net/database/item/2885)
- Update 'Fools_Day_Box' and 'Fools_Day_Box2' based on Aegis.
- Update some item scripts based on Aegis.
- Changed some ItemID into Constants, Partial commit of my ItemID to Constant assignment.
- Added New items and its effect and trade restrictions:
• Mercenary_Casting_ (ID# 12807) (Ref: http://www.divine-pride.net/database/item/12807)
• Mother_Love_Box (ID# 12808) (Ref: http://www.divine-pride.net/database/item/12808)
• Level_Up_Box (ID# 12809) (Ref: http://www.divine-pride.net/database/item/12809)
• Zherlthsh_Tck_Box_ (ID# 12819) (Ref: http://www.divine-pride.net/database/item/12819)
=> ItemDB Updates:

db/re/item_combo_db.txt, db/re/item_db.conf, db/re/item_group.conf
Adds WoE:TE items from episode 14.2
These are official effects / specs.
=> Added WoE:TE Items from EP 14.2

doc/script_commands.txt, src/char/inter.c, src/common/mmo.h, src/login/account_sql.c, src/map/atcommand.c, src/map/intif.c, src/map/mapreg_sql.c, src/map/script.c
This is a merge of the pull requests #866 and #867, with a change through the source, to change the maximum variable size from 31+1 to 32+1 (to hold variable names up to 32 character long). This is in order to avoid having to delete rows from the SQL tables.
Closes #865 as fixed, closes #866 as merged and closes #867 as merged.
=> Merge of #866 and #867

conf/battle/player.conf, src/map/battle.c, src/map/battle.h, src/map/status.c
=> Added Costume/Shadow Atk/Def refine bonus setting

db/pre-re/item_db.conf, db/re/item_db.conf
Removal of 'Buy: 0' in re and pre-re item database.
=> ItemDB Updates

db/pre-re/item_db.conf, db/re/item_db.conf
- In Official, when you use a Enchantment stone, you can compound them in all of the General items that have slots.
=> Enchantment Stones Update:

npc/woe-fe/agit_main.txt
Barely noticeable, but I wanted to test how this site works.
=> Fixed typo

src/login/ipban_sql.c, src/login/login.c, src/login/login.h
Move declaration of login config struct to login interface
=> Move declaration of login config struct to login interface

src/map/status.c
GC_CLOAKINGEXCEED Speed must 140% rather than 200+%
=> Fixes #907

src/map/unit.c
Rude attack was not checking for this setting.
=> Fixes monsters not taking rude attack when OFFICIAL_WALKPATH is used.

src/map/skill.c
Now it will automatically update with new values (according to the
current song properties) when the status change is about to finish.
Thanks Kyeme for the necessary proofs and reminders!
=> Revamped Aegis style songs behavior. Fixes #835

db/re/mob_db.conf
- Lighthalzen Biolab F4
- Hall of Abyss
- Old Glast Heim
Merged rAthena @ f987f1bcbe22ccd4f75fa15e21193b7419aa7f5c
Credit: secretdataz
=> Mob DB Update - Added card drops

src/map/battle.c
The original eathena source mapped ```sd``` to ```bl``` (the target), and ```sc``` to bl's status. Later on, people found the need to add equivalents for ```src```, and instead of first renaming the existing variables, just dropped in the mappings ```tsd``` to ```src``` (the source) and ```tsc``` to src's status. These were really poor choices, since the 't' prefix refers to the target in all other code. I'd like this inconsistency resolved.
Things get a bit more complicated when considering existing custom code, because if the names are just swapped around, all that code would silently break, acting on the source instead of the target and vice versa.
Here is an attempt to recover from this situation. I introduce a top-level variable for src's sd to eliminate four locally-scoped …
=> more meaningful variable names in battle_calc_damage()

sql-files/item_db2.sql, sql-files/item_db_re.sql, src/map/itemdb.c, src/plugins/db2sql.c
- Fixed issues while parsing the Item DB
- Added support for the recently introduced new format to the db2sql plugin
See commit messages for more details.
=> Various fixes for the "Job" itemdb field

npc/cities/izlude.txt, npc/other/marriage.txt, npc/pre-re/mobs/dungeons/gefenia.txt, npc/pre-re/quests/quests_13_1.txt, npc/quests/quests_alberta.txt, npc/quests/quests_moscovia.txt, npc/re/cities/dicastes.txt, npc/re/events/christmas_2013.txt
- Added missed standardization changes to npc\quests\quests_moscovia.txt script changing item numbers to constants.
- Fix to NPC [Iromo's Mother#ep3_2] to fix a bug that restarts the quest.
- A minor fix to some typo error.
- Pre-RE: Fixed the position of NPC [Promotional Staff#iz] from izlude before renewal.
=> Added missed standardization changes and some fixes.

src/map/pc.h, src/map/status.c, src/map/status.h
Updated other instances of MAX_WEAPON_TYPE to MAX_SINGLE_WEAPON_TYPE.
=> Fixes #1198 and fixes #1194 introduced in pull request #1189

src/map/status.c
=> Fixes #1014

doc/script_commands.txt
=> Fix a typo in script_commands.txt

src/common/timer.c, src/map/npc.c, src/map/unit.c, src/map/unit.h
Now timer id start count from 1.
=> Fix one of timer issue and add protection agains future issues like this

.travis.yml
Install in travis package zlib1g-dev.
=> Fix ubuntu travis issue

src/common/mmo.h, src/map/status.h
=> Allow redefine some array sizes by preprocessor from command line

src/map/script.c, src/map/script.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1339)
=> Add one check for possible script issue.

src/map/skill.c, src/map/skill.h, src/map/status.c, src/map/status.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1342)
=> Move some static functions into interfaces

src/common/core.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1343)
=> Dont show compilation warnings about root if building for ci.

db/pre-re/item_db.conf, db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c, src/map/skill.h, tools/skilldbconverter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1352)
=> Some skilldb fixed after conversion

conf/messages.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1358)
=> Reworded some lines in messages.conf - chrif related.

src/map/battle.c, src/map/battle.h, src/map/skill.c, src/map/skill.h, src/map/status.c
Also improve a bit cast end functions call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1354)
=> Add into skill.c some handling for unknown skills/skill units.

src/map/clif.c, src/map/clif.h, src/map/unit.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1360)
=> Simplify clif_skillcasting.

src/map/skill.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1366)
=> Removed Leftover of skill_db.txt

src/map/map.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1367)
=> Improve a bit performance in bl_getall_area.

src/common/showmsg.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1369)
=> If build bot enabled, show error message in ShowConfigWarning.

tools/skilldbconverter.php
Fixes issue #1363.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1364)
=> Fixes skilldbconverter.php display on windows.

db/re/item_db.conf
fix issue #1303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1371)
=> Fix a typo in some items bonus

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/clif.c, src/map/skill.c, src/map/skill.h, src/map/status.c, src/map/unit.c, tools/skilldbconverter.php
FreeCastReduced - allow move while casting with slowdown
FreeCastNormal - allow move while casting with normal speed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1372)
=> Add skill attributes for allow moving while casting this skill

npc/re/instances/OldGlastHeim.txt
missing ( ) in npctalk and unittalk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1374)
=> Followup d5d646c

doc/script_commands.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1375)
=> Remove duplicate entry for getnameditem function on script commands documentation.

npc/re/instances/OldGlastHeim.txt
change all old glast heim ontalk syntaxes to npctalk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1376)
=> Update OGH change donpcevent to npctalk

src/char/char.c, src/char/inter.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1400)
=> Add missing sql escapes in char server

npc/pre-re/jobs/1-1/mage.txt
…of some code, that calls a function we might want to modify at some time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1414)
=> Fixed Mixed Solution No.3 Arc never being assigned and repositioning

npc/re/jobs/1-1e/taekwon.txt, npc/re/scripts_jobs.conf
Fix issue#[1418](https://github.com/HerculesWS/Hercules/issues/1418)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1420)
=> Followup 0a097048

src/map/pc_groups.c, src/map/pet.c, src/map/quest.c, src/map/script.c, src/map/searchstore.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1421)
=> Add missing checks into some files in map server

src/map/npc.c
Not sure is gravity client support this, but for other clients it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/483)
=> Allow sell items to market shop.

src/map/clif.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1429)
=> Dont send packets with size 0

src/map/skill.c, src/map/status.c, src/map/storage.c, src/map/trade.c, src/map/unit.c, src/map/vending.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1438)
=> Add missing checks in map server

src/char/int_quest.c, src/map/clif.c
Fix assert in clif_detion
Save quest time into db
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1443)
=> Small fixes

src/common/cbasetypes.h, src/common/db.c, src/common/sql.c, src/map/battle.c, src/map/battleground.c, src/map/clif.c, src/map/homunculus.c, src/map/itemdb.c, src/map/map.c, src/map/mob.c, src/map/npc_chat.c, src/map/pc.c, src/map/quest.c, src/map/script.c, src/map/skill.c, src/map/status.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1450)
=> Add different fixes for gcc 7 warnings.

db/re/item_db.conf
bSkillAtk not increasing damage for some skills
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1437)
=> fix some items bonus

npc/re/warps/cities/izlude.txt
added missing end; and parantheses
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1456)
=> followup 805a2b3b

src/common/HPM.c, src/common/console.c, src/common/core.c, src/common/db.c, src/common/des.c, src/common/ers.c, src/common/grfio.c, src/common/mapindex.c, src/common/mutex.c, src/common/socket.c, src/common/sql.c, src/common/strlib.c, src/common/sysinfo.c, src/common/utils.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1452)
=> Add missing checks in common directory

db/re/item_db.conf, npc/re/quests/eden/100-110.txt, npc/re/quests/eden/11-25.txt, npc/re/quests/eden/111-120.txt, npc/re/quests/eden/121-130.txt, npc/re/quests/eden/131-140.txt, npc/re/quests/eden/26-40.txt, npc/re/quests/eden/41-55.txt, npc/re/quests/eden/56-70.txt, npc/re/quests/eden/71-85.txt, npc/re/quests/eden/86-90.txt, npc/re/quests/eden/91-99.txt, npc/re/quests/eden/eden_common.txt, npc/re/quests/eden/eden_quests.txt, npc/re/quests/eden/eden_service.txt
This comes from pull request #1319, closed due deletion of forked repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1460)
=> Added support to Para_Team_Mark_ item in Eden Group

src/map/status.c
Fixes #1442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1459)
=> CRI should only be calculated if flag have SCB_CRI.

db/re/item_db.conf
according to this post
http://herc.ws/board/topic/12721-doubt-about-races-demihuman-player-demiplayer-and-nons/#entry73689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1465)
=> Fix wrong items bonus

db/quest_db.conf
original commit https://github.com/rathena/rathena/commit/25c4334e8406b21a74ecbc313205ea42e9b2df50 by secretdataz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1463)
=> Add official quest condition for Guillotine Cross job change quest

src/map/clif.c
Thans for @Ridley8819 for reporting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1470)
=> Fix packet id for clif_heal for packet version >= 20150513.

doc/script_commands.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1476)
=> missing type at setlook documentation

src/char/char.c, src/map/clif.c
Fixed packets betweet 20111005 to 20141022.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1461)
=> Dont send packets for known unsupported client versions.

db/re/skill_db.conf
closes #1246
reference:
http://irowiki.org/wiki/King's_Grace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1466)
=> Added RG King's Grace cooldown

src/common/HPM.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1497)
=> Fixed wrong nullpo check

src/map/clif.c, src/map/packets.h
Add some new packets and fix packet versions. Processed only 2010-2011 packet versions.
Based on info from https://gitlab.com/4144/servergreps/tree/master/peek_all/packets/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1504)
=> Add some new packets and fix packet versions

db/re/item_db.conf
https://github.com/HerculesWS/Hercules/issues/1484
Signed-off-by: Angelmelody <cutepeipei@hotmail.com.tw>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1502)
=> fix incorrect item type

npc/quests/the_sign_quest.txt
disabled npc's do not show the effects
Fixes #1518 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1519)
=> Fix wrong command usage at the sign quest

npc/quests/quests_13_2.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1529)
=> Add a custom weight check in ring of the wise king quest

npc/re/jobs/3-2/royal_guard.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1538)
=> Double NPC Name in Royal Guard job change quest

npc/events/gdevent_aru.txt, npc/events/gdevent_sch.txt, npc/quests/kiel_hyre_quest.txt, npc/quests/quests_13_1.txt, npc/quests/quests_morocc.txt, npc/quests/quests_nameless.txt, npc/quests/skills/knight_skills.txt
Credit: rathena/rathena@a9faab82cbcfbdb3009c5584032505e8617310bd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1536)
=> Fixed incorrect OnTouch label in Crow of Destiny Quest

npc/airports/airships.txt
Fixed airships.txt if player and NPC get same number of dice but below than 8 then it was only showing NPC name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1486)
=> Fixed airships.txt

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1526)
=> Fixing an small markdown mistake

npc/re/quests/eden/eden_quests.txt
- Fix classes checking (https://github.com/HerculesWS/Hercules/issues/1173)
- Update and remove redundant script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1493)
=> Update Eden Quest script

db/re/item_db.conf
in kRO Para_Team_Mark_ warp the player to eden group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1557)
=> Correct Para_Team_Mark_ effect.

npc/quests/quests_juperos.txt
* also change name of 2 variables to the official names
- yuno_hist -> yuno_book
- jupe_hist -> jupe_book
partial merge of
rathena/rathena@c488268d8c2fa74e1d16daf0c04a6bf2d36e2350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1555)
=> Add quest log for Juperos Ruins History Quest

npc/instances/NydhoggsNest.txt
fixes #1551
http://herc.ws/board/tracker/issue-8657-nydhoggs-nest/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1559)
=> Adjust 2@nyd areamobs

npc/quests/quests_moscovia.txt
Before merging this in [here](https://github.com/HerculesWS/Hercules/pull/1561/commits/be4d5da4069c5ce03a6cd848e82dd895a1bec361#diff-2ce818a0f7b8295c7f3ef056870b7d80R7595) aegis script has this exception for thief, since im not sure if it's affecting the rest of the quest i left it but i believe they just miss it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1561)
=> Add quest log for moscovia quests

npc/quests/quests_hugel.txt, npc/quests/quests_lighthalzen.txt, npc/quests/quests_louyang.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1575)
=> remove useless check for questprogress

doc/script_commands.txt, src/map/script.c
adds `chr()` and `ord()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1588)
=> add ascii manipulation buildins

doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/mob.c, src/map/script.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
HPM is giving me an error after the change, probably because I edited the parameters of clif_class_change, but it's regenerated by herc build bot right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1587)
=> Added option to show classchange only to one player

db/pre-re/skill_db.conf
#1600 Fixing Beast Strafe: atm it's untargetable and should be targeted like double strafe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1605)
=> Fixing Beast Strafe

db/pre-re/map_zone_db.conf, db/re/map_zone_db.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1599)
=> Fixing some spelling

doc/script_commands.txt, src/map/script.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1592)
=> revert #1586, add getvariableofpc

npc/other/Global_Functions.txt
- not using in any script, could be easily replace by simply if-else
condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1607)
=> Update Global Function - Remove F_SexMes

npc/quests/the_sign_quest.txt
credit rathena/rathena@800f22b77bb63c2305d05956de8fbe5db0327ded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1608)
=> Change variable type on the sign quest

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Initial implementation of issue and pull request templates for github that enforce certain basic requirements before submitting an issue or pull request.
Template follows basic markdown syntax.
More details on github templates can be found here - https://github.com/blog/2111-issue-and-pull-request-templates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1606)
=> Issue and Pull Request Templates.

src/char/int_party.c, src/map/party.c
Now party leader is changed to the second user. Closes #1107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1530)
=> Changed behavior when party leader leaves

npc/quests/the_sign_quest.txt
As suggested by @iRagno this commit adds geffenia_warp to the variables clearing function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> add geffenia_warp var to the clear function.

db/quest_db.conf
=> Add missing quest db entries

src/map/unit.c
Fix issue from http://herc.ws/board/topic/13719-map-error-need-help-here/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1509)
=> Fix assert in unit_resume_running.

db/pre-re/job_db.conf
Adds a commented value to Priest Knuckles BaseASPD.
Users can decide to remove comment to normalize Priest aspd with knuckles.
**Issues addressed:** #1204 Attack Speed Bug (2)
None …
=> Solves #1204. Adds a commented value to Priest Knuckles BaseASPD.

db/re/map_zone_db.conf
**Issues addressed:** #686 WoE gear and consumable still work in instance
- None …
=> Fixes #686. Blocks Vellum and Siege equips/potions usage on non WOE/PVP maps.

npc/instances/NydhoggsNest.txt
- Attaches [Yggdrasil Gatekeeper] NPC to make him capable of read instance variables.
**Issues addressed:** #1293 Error and Warning
- None
[cont]: …
=> Fixes #1293. Attaches [Yggdrasil Gatekeeper] NPC to make him capable of read instance variables.

db/pre-re/mob_db.conf, db/re/mob_db.conf, doc/mob_db.txt
**Issues addressed:** #569 add doc/mob_db.txt plis
None
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already …
=> Fixes #569. Adds mob_db.txt documentation.

npc/mapflag/gvg.txt, npc/pre-re/mapflag/gvg.txt, npc/pre-re/scripts_main.conf, npc/pre-re/scripts_mapflags.conf, npc/re/mapflag/gvg.txt, npc/re/woe-fe/invest_main.txt
- Fixes to issues on checks of Guild Dungeon Investment.
- Separates mapflag gvg_dungeon from common to pre-renewal and renewal.
-- pre-renewal: set gvg_dungeon to woe fe guild dungeons
-- renewal: sets gvg_dungeon to hall of the abyss dungeons (removes gvg_dungeon to woe fe guild dungeons).
- Update some numbers to constants.
**Affected Branches:** …
=> Fixes #1625. Fixes checks on Guild Dungeon Investment and separates Guild Dungeon mapflags for pre-renewal and renewal

db/re/item_db.conf
- Fixes Peuz_Greave effect with refine level.
- #1533 Peuz's Greaves - Wrong bonus script
None
[cont]: …
=> Item DB Fixes.

src/map/atcommand.c
Based on @Dastgir's commit. https://github.com/RagEmu/Renewal/commit/9409e435cab3c7ee24172f09b865b2803411f0ff
only GM with the minimum group id able to view it.
There was an Issue created in Herc, but I didnt found where was it.
**Preview**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Enable display of custom commands in @commands.

conf/map/battle/client.conf, conf/messages.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/clif.h
- Credit to https://github.com/rathena/rathena/commit/85749e84b91087960e868e30a7a052b0c0cdce5b
- Master
- Fixed MVP exp message issue clients 2013-12-23cRagexe and newer.
- Gravity removed packet MVP exp message
- rA Merges …
=> Fixed MVP exp message issue for clients 2013-12-23cRagexe and newer

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c
- NPC_LICK now has a base chance of 20%*level and a base duration of 5s
- Excruciating Palm now has a base duration 5s
- Shield Press now has a base duration of 5s+0.5s*level
- Earth Shaker now has a base duration of 2s (level 2-3) and 3s (level
4-5)
- Sightless Mind now has a base duration of 30s in pre-re and 20s in
renewal
- Credit …
=> Official status change base durations for Stun (#1234)

src/common/mmo.h
- kRO Mains recently increased their character slots from 11 to 12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1184)
=> Increase Character Slots from 9 to 12

src/common/strlib.c, src/map/clif.c
- [ x ] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
Fix npc text input For 2015 clients.
Fixes #1640
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1641)
=> Fix npc text input For 2015 clients (Fixes #1640).

conf/map/logs.conf
- [ x ] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
Fix item logging default flag.
Also update docs for log types in logs.conf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1646)
=> Fix item logging default flag.

src/char/char.c, src/char/char.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
- [ x ] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
Add support for sex based character creation for 2015-10+ clients.
Allow select for new char gender and human or doram class.
Doram starting point not implemented.
Also summoner char may looks not like summoner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1644)
=> Add selection char sex and class in char creation for 2015-10 + clients

src/map/clif.c, src/map/packets_struct.h
- [ x ] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
Fix auth packet for adding future clients packets (2015+)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1643)
=> Fix map server auth packet for clients >= 20160330.

db/re/skill_db.conf, src/map/skill.c
This pr corrects the homunculus skill `HAMI_CASTLE` based on test in kRO and [irowiki](http://irowiki.org/wiki/Castling) the skill has 1 sec cooldown.
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled …
=> Correct Castling skill to use cooldown

src/map/battle.c
Allow skills and attacks with flags `BCT_ENEMY` and `BCT_PARTY` to affect "guild enemy units" within the party on maps with flags `gvg` and `gvg_noparty`.
**Issues addressed:** #1647 
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." …
=> Fixes issue #1647

npc/jobs/2-1/wizard.txt
I have check in several versions of aegis script but non have this warp so im assuming its a copy paste typo.
[code]: …
=> remove wrong warp in wizard job quest

doc/constants.md, doc/script_commands.txt, src/map/script.c
See the comments in #1610. This PR adds a new buildin:
```
getunits(<type>, <var>[<index>], <limit>, "<map>"{, <x1>, <y1>, <x2>, <y2>})
```
```c++
npctalk("I am the most beautiful being the Universe ever begat!");
sleep(500);
npctalk("...and you shall all love me!");
.@count = getunits(UNITTYPE_PC, .@gid[0], 5, "map", 45, 67, 109, 111);
for (.@i = 0; …
```
=> add getunits() buildin

src/map/script.c
My bad, I forgot to commit this somehow
=> add missing _pc in set_reg

src/map/clif.c
Fixes PR#1681 that tackles an issue with compilation.
**Issues addressed:** #1681 
=> Fixes issue #1681

src/char/char.c, src/map/packets.h
Add packets for diffrent 2015 clients.
Fix some existing packets for 2015 clients.
=> Add packets for diffrent 2015 clients

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/clif.c
=> Cart Decorate & Change Cart Fixes

db/constants.conf, src/map/npc.h
=> Update NPC ID

npc/cities/aldebaran.txt, npc/events/MemorialDay_2008.txt, npc/events/easter_2010.txt, npc/events/nguild/nguild_ev_agit.txt, npc/events/nguild/nguild_kafras.txt, npc/events/nguild/nguild_managers.txt, npc/events/xmas.txt, npc/instances/NydhoggsNest.txt, npc/jobs/2-2/sage.txt, npc/merchants/clothes_dyer.txt, npc/other/hugel_bingo.txt, npc/other/marriage.txt, npc/quests/bard_quest.txt, npc/quests/bunnyband.txt, npc/quests/cooking_quest.txt, npc/quests/quests_airship.txt, npc/quests/quests_lighthalzen.txt, npc/quests/quests_rachel.txt, npc/quests/thana_quest.txt, npc/re/instances/BangungotHospital.txt, npc/re/jobs/2e/kagerou_oboro.txt, npc/re/jobs/3-1/guillotine_cross.txt, npc/re/quests/eden/eden_tutorial.txt, npc/re/quests/quests_malangdo.txt, npc/re/quests/quests_malaya.txt
Removed the usage of deprecated command goto from npc scripts (except custom folder). This includes only the needed changes to remove goto command, anything else wasn't changed (included script improvement) to make it easier the revision and because those would be matter of other commits.
**Issues addressed:** #374 …
=> Removed the usage of deprecated command goto from npc scripts (except custom folder)

conf/map/battle/skill.conf, src/map/pc.c
=> Added AB_HIGHNESSHEAL in skill_add_heal_rate configuration

conf/map/battle/items.conf, src/map/atcommand.c, src/map/battle.c, src/map/battle.h, src/map/script.c
=> Removed hard coded values on @cashmount and setcashmount.

conf/messages.conf, src/map/clif.c, src/map/pc.c
The message string only shows if mode is RENEWAL only.
[//]: # (**NOTE** Enable the setting "[√] …
=> Added the correct PACKETVER Date for MSG_NPC_WORK_IN_PROGRESS message.

conf/map/battle/drops.conf, conf/messages.conf, db/pre-re/item_db.conf, db/re/item_db.conf, doc/item_db.txt, src/map/battle.c, src/map/battle.h, src/map/itemdb.c, src/map/itemdb.h, src/map/mob.c, src/map/pc.c, tools/configconverter.pl
Removing hard coded entry and added a field in item db for Monster Rare Drop Announce.
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/994
Current implementation of …
=> Fixes #994

conf/messages.conf, src/map/atcommand.c
Other jobs can still use this command even they don't have body styles. This addition can prevent client crashes.
[//]: # (Syntax: - …
=> Added job checks for @bodystyle command

conf/map/battle/items.conf, db/pre-re/item_db.conf, db/re/item_db.conf, src/map/battle.c, src/map/battle.h, src/map/itemdb.h, src/map/pc.c, src/map/status.c
in kRO, you can still use cash foods, battle manual, bubble gum while the status effect is still active.
Status effects from Cash Food items cannot be removed by …
=> Cash Foods Update

conf/char/char-server.conf
=> Spacing correction.

doc/script_commands.txt
- [x ] I have followed [proper Hercules code styling][code].
- [x ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x ] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
=> Updated *showscript documentation description.

npc/quests/quests_ein.txt
Make NPC Uwe Kleine readable.
Fix some of the typos in quests_ein.txt
Basically I had to read through the NPC Uwe Kleine in quests_ein.txt
and it's absolutely unreadable for any human being, so what I did is:
- Remove repetition ( A LOT )
- Make logic of obfuscated parts readable
- Fixed an unintended fallthrough because of a condition which the Aegis Script doesn't cover
- other stuff ...
EDIT:
While reading a few other NPCs I noticed a few typos and fixed those as well with my most recent commit.
**Issues addressed:** none
=> Clean up repetition and increase readability of Uwe Kleine NPC-Script.

doc/script_commands.txt, src/map/channel.c, src/map/channel.h, src/map/script.c
* Allow chat channels to have event handlers
* Add `addchannelhandler("<#channel>", "<NPC::OnEvent>")`
* Add `removechannelhandler("<#channel>", "<NPC::OnEvent>")`
* Update the documentation accordingly
<br>
```c
OnChannelMessage:
if (compare(@channelmes$, "hello")) {
channelmes("#chan", "NPC : hi there!");
}
end;
OnInit:
addchannelhandler("#chan", …
```
=> add channel handler events

src/char/char.c, src/char/int_storage.c, src/char/int_storage.h
Fix memory leak in storage item vector
=> Fix memory leak in storage item vector (Fixes #1751)

db/pre-re/item_db.conf, db/re/item_db.conf, doc/script_commands.txt, npc/custom/quests/thq/THQS_TTShop.txt, npc/dev/test.txt, npc/other/Global_Functions.txt, src/map/script.c, src/map/script.h
This is an implementation of the exponentiation operator (from #1667) with left-assignment.
* `pow(5, 3)` => `5 ** 3`
* `pow(pow(5, 3), 2)` => `5 ** 3 ** 2`
* `pow(5, pow(3, 2))` => `5 ** (3 ** 2)`
* `.@var = pow(.@var, 3)` =>`.@var **= 3`
The exponentiation operator has higher precedence than the multiplication operator and lower precedence than the …
=> implementation of the exponentiation operator

doc/script_commands.txt, src/map/atcommand.c, src/map/atcommand.h, src/map/script.c
* new buildin: [add_group_command](https://github.com/HerculesWS/Hercules/issues/1726)
**Issues addressed:** #1726 
**Type:** [enhancement](https://github.com/HerculesWS/Hercules/labels/type%3Aenhancement)
**Compopents:** …
=> new buildin: add_group_command

src/char/char.c, src/login/lclif.c, src/login/lclif.p.h, src/map/packets.h
Add support for most released 2017 RE clients.
Add shuffle packets.
Add new packet ids in login and char server.
=> Add support for most released 2017 RE clients

doc/script_commands.txt
- [X ] I have followed [proper Hercules code styling][code].
- [ X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ X] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.
[//]: …
=> Documenation for <URL> browser dimensions.

src/map/script.c
* fix a memory leak with `at_groups` and `chat_groups` of atcommand bindings
**Issues addressed:** (none)
=> fix memory leak introduced by 5ceccb7

src/map/skill.c
Merged rAthena @ 45aab55ca18aea17695fff3d39dac4172a63674c
Credit: cydh
=> Fixed Chain Lighting animation was sent in wrong flow.

db/re/item_combo_db.txt, db/re/item_db.conf
- correct Yggdrasil_Herald_Crown equip location : fixes #1724
- correct combo bonus for advanced angelic set : fixes #1286
=> fixes some item bonuses

src/map/script.c
Currently, removing cards from commands remove item options too.
* Changes the way successremovecards and failedremovecards works.
* all
None
[//]: # (Insert checklist …
=> Fixes remove card bug

doc/script_commands.txt, src/map/script.c, src/map/script.h
* it can now be used on a single player
* it can now be used on a whole map, or area
* it is backward-compatible
---
closes #1784 
=> Make the recovery() command more versatile

src/map/npc.c
some variables weren't set to 0 and cleararray wasn't called.
#1772 
[//]: # (**NOTE** Enable the setting …
=> Fixes crash with sell shop.

conf/map/battle.conf
battle.conf from import folder should be used with import and not by include, currently, it was both included and imported.
* all
[//]: # …
=> fixes reading battle.conf multiple times

db/item_options.conf, doc/script_commands.txt, src/map/script.c
Non-existent bonuses were used in item_options.conf.
Documentation was having wrong command name.
* None
2 …
=> Item option fixes

src/map/script.c
=> Allow to use channelmes without attached player

tools/ci/retry.sh, tools/ci/travis.sh, tools/mobdbconvall.sh, tools/stackdump
Changes the interpreter directive in tools to use `/usr/bin/env bash` rather than `/bin/bash`. Apparently it's incompatible with BSD otherwise
=> use /usr/bin/env bash in tools

.travis.yml, src/common/cbasetypes.h, src/plugins/HPMHooking.c, tools/ci/travis.sh
Add into travis check for hpm update
This will prevent issue what happened in master with rodex pull request.
=> Add into travis check for hpm update

3rdparty/libconfig/libconfig.c, src/map/npc.c
Fix warnings in libconfig.
Fix possible buffer overflow in function npc_parsename.
=> fix different issues in libconfig and hercules

src/map/clif.c
Fix some wrong packet versions in rodex code.
Also replace some numbers to constants.
=> Fix some wrong packet versions in rodex code.

npc/other/comodo_gambling.txt
Fixes the check that the Diamond Seller "Blacksmith Miner" NPC would make before selling the diamonds.
master
[//]: # (Syntax: - [ ] …
=> Fix Diamond Seller weight check

doc/script_commands.txt, src/map/script.c
=> Deprecate buildin_useatcmd

doc/script_commands.txt, src/map/script.c
=> Allow using getgroupid on another player

src/map/atcommand.c
=> Update Sorcerer and Sura alternate body style in atcommand.c

doc/script_commands.txt, src/map/script.c
=> Added dressroom script commands to open/close Dress Room window

doc/script_commands.txt, src/map/script.c
Allows `logmes` to log to the atcommand table. This is also future-proof in case we want to add other log tables at some point
=> Improve logmes

conf/map/battle/party.conf, src/map/battle.c, src/map/battle.h, src/map/clif.h, src/map/party.c
Simple implementation of #1804.
For current installations it will use the old behaviour and for new installations it will use the official behaviour.
=> add option to restrict party leader change to same map

npc/kafras/functions_kafras.txt
Change in functions_kafras to show a different text between normal characters and Doram characters.
Credits to @RagEmu.
[//]: # …
=> Open Storage for Doram

src/map/script.c
Fix warning if build with gcc-7.
=> Fix warning with gcc-7.

npc/re/instances/ghost_palace.txt
=> Applied standardization to ghost_palace script

conf/login/login-server.conf, src/login/lclif.c, src/login/login.c, src/login/login.h
Add ability to show char servers list with colors based on players count.
Add missing functions from login.c into interface.
=> Add ability to show char servers list with colors based on players count.

db/constants.conf, doc/script_commands.txt, src/map/script.c
master
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not …
=> update qtype constants to support new 2017 client icons.

npc/instances/OrcsMemory.txt
=> Applied standardization to OrcsMemory script

npc/instances/SealedShrine.txt
=> Applied standardization to SealedShrine script

src/map/script.c
has_instance and has_instance2 can now search for IOT_NONE istances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1469)
=> Fixes #1397

npc/instances/EndlessTower.txt
- Change progressbar() command to use integer instead of string.
- Define constants to missing color codes.
[√]: # (**NOTE** …
=> Applied standardization to EndlessTower script

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/clif.c, src/map/clif.h, src/map/packets_struct.h, src/map/skill.c, src/map/skill.h
this pr adds support for packet to show an area of effect for some skills using client lua files.
Master
non
[//]: # (Syntax: - [ ] …
=> Implement skill scale packet for client versions >= 20151223.

npc/re/instances/OldGlastHeim.txt
=> Applied standardization to OldGlastHeim script

src/char/char.c
=> correct wrong conf file path in showerror

src/map/status.c
The status change timer wasn't correctly rearmed in such a condition, keeping SC_POISON active indefinitely. (`sc_timer_next()` wasn't called before returning 0)
- master
- stable
N/A (the issue was reported elsewhere)
There might be other places where a similar issue occurs, but that is beyond the scope of this pull request.
=> Natural expiration of Poison when under Slow Poison effect

Hercules.xcodeproj/project.pbxproj
Added RoDEX files to Xcode.
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." …
=> Added RoDEX files to Hercules.xcodeproj

src/common/nullpo.h
Enable always asserts and nullpo checks.
Before this options was depend on debug configure flag.
But this options is must because without it server may crash in any exploits.
=> Enable always asserts and nullpo checks.

src/char/int_rodex.c, src/map/intif.c
This pull request fixes a bug when RoDEX is open and the mail list requires more than one packet to be sent to map-server.
master
Fixes #1933 
[//]: # (Insert checklist …
=> Fixed rodex loading mails when it requires multiple packets.

tools/ci/travis.sh
Disable leak detector on travis ci due mysql issue
=> Disable leak detector on travis ci due mysql issue

npc/instances/NydhoggsNest.txt
=> Applied standardization to NydhoggsNest script

README.md
Edited the README.md document:
- Removed the unused waffle.io links
- Added a Discord link
- Added badges for GitHub Releases, Contributors, Open PRs
- master
N/A
N/A
=> Update links and badges in the README document

npc/re/instances/BuwayaCave.txt
=> Applied standardization to BuwayaCave script

npc/re/instances/EclageInterior.txt
=> Applied standardization to EclageInterior script

npc/re/instances/HazyForest.txt
=> Applied standardization to HazyForest script

npc/re/instances/MalangdoCulvert.txt
=> Applied standardization to MalangdoCulvert script

src/map/atcommand.c, src/map/clif.c
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1200)
=> Hide area packets from hidden players/gms.

src/map/clan.c, src/map/clif.c
Add missing online check for clan members.
Clean sd pointer after clan member went offline.
master
=> Fix different clan issues.

src/map/packets.h, src/map/packets_keys_main.h, src/map/packets_keys_zero.h, src/map/packets_shuffle_main.h, src/map/packets_shuffle_zero.h
Update packets and keys tables up to 20180207.
=> Update packets and keys tables up to 20180207.

conf/messages.conf, src/map/atcommand.c, src/map/map.c
Fix messages about enabled/disabled cvc mode.
Fix possible crash in zone change code.
#1971
=> fix some clan issues

src/map/script.c, src/map/script.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
I need this for [evol/evol-hercules@68886b5](https://gitlab.com/evol/evol-hercules/commit/68886b570125930f7a5d6343900a16d584a6dccd)
=> expose script_sprintf to plugins

vcproj-11/map-server.vcxproj, vcproj-11/map-server.vcxproj.filters, vcproj-12/map-server.vcxproj, vcproj-12/map-server.vcxproj.filters, vcproj-14/map-server.vcxproj, vcproj-14/map-server.vcxproj.filters
this doesn't affect the build since those files are loaded via include but it will allow using search when working with visual studio as an editor.
[cont]: …
=> update vs projects with new packet files

src/char/inter.c
This need for better security.
Dont show password and pincode in @accinfo gm command.
This need for better security.
=> Dont show password and pincode in @accinfo gm command.

src/char/pincode.c, src/login/login.c, src/map/atcommand.c, src/map/clif.c, src/map/unit.c
Fix null pointer in login.c in login->accounts. This affect only plugins.
Fix use after free error in @reloadatcommand gm command.
=> fix different crashes

src/map/clan.c
ClanDB is initialized so that constants can be loaded. …
=> DB2SQL Crash Fix

src/map/clif.c, src/map/rodex.c
RoDEX should not open, neither should send mail (packet manipulation) when it is disabled or NPC is opened.
[//]: # (Syntax: - [ ] …
=> RoDEX Update

src/map/atcommand.c, src/map/clif.c, src/map/pc.c
Kafrapoints should now be used correctly.
Issue #1540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1541)
=> Changed Kafrapoints calculation.

vcproj-11/login-server.vcxproj, vcproj-12/login-server.vcxproj, vcproj-14/login-server.vcxproj
This removes a duplicated file in visual studio login-server projects that avoided the project from loading. Tested on VS2017 (without project update)
master
[//]: # …
=> Remove duplicated file in login-server VS projects

db/constants.conf, db/re/item_db.conf, doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/pc.c, src/map/pc.h, src/map/script.c, src/map/unit.c
Implemented HatEffect Feature.
It is mostly used in items to give new appearance to players.
[//]: # …
=> Implemented HatEffect

src/map/clif.c, src/map/clif.h, src/map/packets_struct.h, src/map/quest.c
- Updated Quest Packets to structure form
- Added 2015 variant of Quest Packets
=> changed quest packets to structure form + some update

src/char/int_guild.c, src/common/mmo.h, src/map/clif.c, src/map/guild.c, src/map/guild.h, src/map/intif.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Signed-off-by: Megasantos <jonataandretta@hotmail.com>
This PR implements support to show the last online date of guild members.
The date used is a timestamp, this allows some modifications to the client side.
Search in msgstringtable. txt the line **3012**
**Oficial message:** …
=> Implemented login date for guild members.

src/map/clif.c, src/map/clif.h, src/map/packets_struct.h
This pr adds support for some missing msgtable packets.
=> add some missing msgtable packets

conf/map/battle/items.conf, src/map/battle.c, src/map/battle.h, src/map/pc.c
In official servers, you can't open boxes and use usable/consumables items when the storage is open.
master
Fixes #1806 
[//]: # (Syntax: - …
=> Fixes #1806

src/map/clif.c
this will send packet on login/changemap so the ui can get updated to show correct status
thanks to @Lemongrass3110  for da reminder
[cont]: …
=> add missing homunculus autofeed update on change map

conf/map/battle/monster.conf, src/map/battle.c, src/map/battle.h, src/map/mob.c, src/map/mob.h, src/map/npc.h
This adds a configurable delay time to spawning a tomb after a MVP is killed.
master
Fixes #1980 
[//]: # …
=> Added delay to tomb spawn

src/map/status.c
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/680
[//]: # (**NOTE** Enable the setting "[√] Allow …
=> Fixes https://github.com/HerculesWS/Hercules/issues/680

conf/map/battle/feature.conf, doc/item_db.txt, src/map/clif.c, src/map/packets_struct.h
this enables use of new drop packet & attendance in more recent versions.
[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.m …
=> Enable some features for newer client versions

conf/map/battle/guild.conf, src/map/battle.c, src/map/guild.c, src/map/skill.c, src/map/skill.h
This adds the possibility of guild skills continue reducing their cooldown while guild master is offline, that seems to be the official behavior (from the issue discussion).
master
Fixes #1774 
[//]: # (**NOTE** Enable the setting "[√] Allow …
=> Allow guild skills cooldown to continue when logged out

src/common/grfio.c, src/common/sysinfo.c, src/common/utils.c, src/map/atcommand.c, src/map/clif.c, src/map/map.c, src/map/map.h
Fix possible buffer overflows in different files found by gcc trunk.
=> Fix some possible buffer overflows.

npc/re/other/clans.txt
=> Clan npc message fix

src/map/atcommand.c, src/map/script.c
Fix map flag pvp_nocalcrank if use at or script command for enable pvp.
Fixes #2056
=> Fix map flag pvp_nocalcrank if use at or script command for enable pvp.

src/map/clif.c
Fix clif_parse_OpenVending with empty items list.
=> Fix clif_parse_OpenVending with empty items list.

npc/instances/EndlessTower.txt, npc/instances/NydhoggsNest.txt, npc/instances/OrcsMemory.txt, npc/instances/SealedShrine.txt, npc/re/instances/BakonawaLake.txt, npc/re/instances/BangungotHospital.txt, npc/re/instances/BuwayaCave.txt, npc/re/instances/EclageInterior.txt, npc/re/instances/HazyForest.txt, npc/re/instances/MalangdoCulvert.txt, npc/re/instances/OldGlastHeim.txt, npc/re/instances/WolfchevLaboratory.txt, npc/re/instances/ghost_palace.txt, npc/re/instances/octopus_cave.txt, npc/re/instances/saras_memory.txt, src/map/script.c
This is fixes the issue #1651 where instance scripts show error message when trying to generate an already existing instance.
Also corrects the wrong return values for command `instance_create()` to the match the values in the documentation.
master
[//]: # …
=> Update Instance generating behaviour

doc/sample/npc_rodex.txt, src/map/script.c
This fixes `rodex_sendmail_acc` script command that wasn't using account id field. Also fixed the examples in docs/samples.
master
Fixes #2024 
Not exactly an …
=> Fixed rodex_sendmail_acc script command and rodex examples

src/map/skill.c, src/map/skill.h
Changed returntype of skill_check_condition_castend_unknown. skill_check_condition_castend is terminated if returntype is true
This allows plugin to terminate the skill currently being cast.
[//]: # (Issue …
=> Plugin function ReturnType fix

doc/script_commands.txt
see https://github.com/HerculesWS/Hercules/pull/2081#discussion_r195763559
=> standardize the multi-form buildin definitions

doc/script_commands.txt, src/map/script.c
1. Adds BUILDIN(setparam), which sets the parameter of an account id. Reason is it is currently not possible to set stuff like StatusPoint of a character unless they are attached to the script.
2. Adds functionality so BUILDIN(readparam) can take either a Character Name or account …
=> Adds setparam(), change optional param for readparam()

src/char/pincode.c
https://github.com/HerculesWS/Hercules/issues/2046
[//]: # (**NOTE** Enable the setting "[√] Allow edits …
=> Fix pincode bug

doc/script_commands.txt, src/map/script.c
while skimming through every script commands, this one in particular ...
.... seriously .... just fix it already ....
* Master
=> Fix *queueopt documentation

src/map/packets_struct.h
Fix issues found by coverity in last packets related commits.
=> Fix issues found by coverity in last commits.

doc/script_commands.txt, npc/re/jobs/novice/academy.txt, npc/re/warps/cities/izlude.txt, src/common/mmo.h, src/map/clif.c, src/map/homunculus.c, src/map/instance.c, src/map/map.c, src/map/map.h, src/map/pc.c, src/map/quest.c, src/map/quest.h, src/map/script.c
using a vector to hold the data for quest info.
=> Questinfo System overhaul

sql-files/upgrades/2018-07-24--03-23.sql
Fix syntax error in sql update file 2018-07-24--03-23.sql
=> Fix syntax error in sql update file 2018-07-24--03-23.sql

db/stylist_db.conf, src/map/clif.c, src/map/clif.h
now you can disable doram from using certain styles that does not exist for their race
nothing
[cont]: …
=> Add support for doram restriction in stylist shop

src/map/npc.c
this has been commented as an issue on the pr but no fix was included.
=> correct sell item achievement being validated after item is deleted

src/map/achievement.c
Fixed some issues reported by coverity scan for recent merge(achievement system).
[//]: # (**NOTE** Enable …
=> Fix achievement issues

src/map/clif.c, src/map/script.c
Set all fields to 0 in fake bl's.
=> Set all fields to 0 in fake bl's.

src/map/achievement.c
ACH_ZENY_SPEND_* achievements were recording zeny in negative values.
Related Topic: http://herc.ws/board/topic/16215-achievement-system-sql-db-error/
[//]: # (Insert …
=> Fixed an achievement bug.

doc/script_commands.txt, src/map/script.c
`BUILDIN(is_function)` can now tell the difference between the different function types
=> improve is_function()

doc/item_bonus.txt
Adjusted the description of bonuses: bHealPower and bHealPower2.
Adjusted the description of the bHealPower and bHealPower2 to be more explicit.
Master
N/A
[//]: # (Insert …
=> Adjust item_bonus.txt

src/map/clif.c, src/map/clif.h
Add missing fields into banking enums.
Fix roulette info packet size.
=> Packets updates/fixes

conf/messages.conf, doc/atcommands.txt, src/map/atcommand.c, src/map/map.c, src/map/map.h, src/map/npc.c
* fixes #2133 
* adds `@setzone`, which allows changing the zone on the current map
=> add atcommand_setzone, and fix #2133

src/map/clif.c, src/map/clif.h, src/map/instance.c, src/map/instance.h, src/map/packets.h, src/map/packets_struct.h
Add support for PACKET_CZ_MEMORIALDUNGEON_COMMAND which allows instance destruction by the owner.
fixes #2194 
=> Implement PACKET_CZ_MEMORIALDUNGEON_COMMAND

src/plugins/db2sql.c
Updated db2sql to convert mob_skill_db.conf to sql format
#2128 
[//]: # (**NOTE** Enable the setting "[√] …
=> MobSkillDB to SQL conversion

src/map/mob.c
Check if monster is clone before calling achievement system
#2201 
[//]: # (**NOTE** Enable the setting …
=> Fixed issue #2201

src/char/int_guild.c
Fixes crash when character is removed from `char` table but not from guild_member.
#2173 
On Long term, we …
=> Fixes #2173

src/map/guild.c
When player accepts invite, add them to member structure.
#2210 
[//]: # (**NOTE** Enable the setting "[√] …
=> Fixed failed assertion in guild invite.

conf/map/battle/items.conf, src/map/battle.c, src/map/battle.h, src/map/pc.c
If Item Price is 0, it is now changed to 1.
#2177 
[//]: # (**NOTE** Enable the setting "[√] Allow edits …
=> Changes the item price to 1 if it is 0

src/map/achievement.c
Achievement validate function is only called if refine is > 0
#2217 
[//]: # (**NOTE** Enable the setting …
=> Fixed Assertion Error when refine is failed

doc/script_commands.txt
=> Add missing documentation for script command achievement_progress()

src/map/script.c
=> change showevent icon validation to use function from questinfo

doc/script_commands.txt, src/common/mmo.h, src/map/map.h, src/map/quest.c, src/map/quest.h, src/map/script.c
=> Add new type for mercenary class to setquestinfo()

.mailmap
if you know the github username of any contributor from the `missing from github` section ([L45](https://github.com/mekolat/Hercules/blob/e8766a67a2b15b602e41fc807cdf99a4a41e9a03/.mailmap#L45)), please tell so I can add them
=> mailmap update

CONTRIBUTING.md
Grammatical changes to improve readability and flow of document.
[//]: # (**NOTE** Enable the setting "[√] …
=> Proofread & edited CONTRIBUTING document

src/map/status.c
These conditions in switch case were already checked by the line `if (type >= SC_COMMON_MIN && type <= SC_COMMON_MAX)`
[//]: # (Syntax: - [ …
=> Fixed Logically Dead Code in status.c

tools/mobdbconverter.py, tools/mobskilldbconverter.py, tools/petdbconverter.py, tools/utils/common.py
Fixes Several alerts that were shown for python in LGTM
[//]: # (**NOTE** Enable the setting "[√] Allow …
=> Fixes alerts shown by LGTM for python

conf/channels.conf, conf/messages.conf, src/map/atcommand.c, src/map/channel.c, src/map/channel.h
I recall a forum post somewhere which asks how to increase the maximum message delay for HCS. This PR will allow people to set their own delay value to a maximum of 255 seconds (the limit mentioned in that thread).
**Issues …
=> Add config for '@channel setopt MessageDelay <delay>'

conf/map/battle/player.conf, src/map/battle.h, src/map/clif.c
- remove idle when interact with scripts.
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/181
[//]: # …
=> Remove idle when interact with scripts

src/map/script.c
Add missing check in run_script_main (Thanks to @functor-x)
=> Add missing check in run_script_main

configure, configure.ac
=> Add support for mysql versions where type my_bool not exists.

src/char/mapif.c, src/map/intif.c
=> Fix buffer size issue in inter server packets

doc/item_bonus.md
Fixes a few typos in item bonus doc.
=> Fix some item_bonus typos

.travis.yml, tools/ci/travis.sh
Add gcc-7, gcc-8 builds to travis.
Add crash dumps if any server crashed in travis and gitlab tests.
=> Add gcc versions and core dumps into travis

src/map/pet.c
why does homunculus feature shows up in pet.c file ?
https://github.com/HerculesWS/Hercules/blob/e2db93490af67bb42a5611b3cb299770ff0131d7/src/map/battle.c#L7408-L7409
fix pet autofeed feature
* Master
=> fix pet autofeed feature

npc/custom/events/mushroom_event.txt
- fix error due to event terminated by GM using `@killmonster` command.
https://github.com/HerculesWS/Hercules/issues/1955
=> Fix issue #1955

conf/messages.conf, doc/atcommands.txt, src/map/atcommand.c, src/map/atcommand.h
- Enable to drop items based on item type.
Unable to drop items based on item type.
Reference: https://github.com/RagEmu/Renewal/commit/fa865ca07f43e5154c5253393640ec3f28da4a79
=> Update dropall atcommand drop item based on type.

db/re/item_combo_db.txt
- update missing item_combo_db
https://github.com/HerculesWS/Hercules/issues/1982
=> Update item combo db, fix issue #1982

src/char/int_rodex.c
Corrected an extra query in rodex item retrieval in inter-server code, the current code was removing zeny from mail regardless of the fact that we're only requesting items.
=> Fix Item retrieval from rodex

src/map/clif.c
Fix player name packet (Fixes #2459)
=> Fix player name packet (Fixes #2459)

src/map/mob.c
Fixes a nullpointer on mvp drops, caused by #2309 
=> Fixes a nullpo on MVP drops

src/map/clif.c
Fix sending guild storage to client (Fixes #2463)
=> Fix sending guild storage to client (Fixes #2463)

src/map/clif.c
Fix packet ZC_SE_PC_BUY_CASHITEM_RESULT for old packet versions
=> Fix packet ZC_SE_PC_BUY_CASHITEM_RESULT for old packet versions

src/map/status.h
Fix aspd and probably other stats issues.
=> Fix aspd and probably other stats issues.

src/map/refine.c
Fix reading rates from refine db.
=> Fix reading rates from refine db

db/re/item_db.conf
- Added item to regain status point by stat reduction.
- follow up d7bbebdf8526667b288223c8adc2d110204814c5
=> Update item_db - Stat Reduction Potions

src/map/script.c
- only `type == 1` will remove the card.
- fixes #2469
=> Fix *failedremovecards script command.

src/map/mob.c, src/map/mob.h
- fix living mobs aren't updated by latest mob_db upon updated.
https://github.com/rathena/rathena/issues/3783
=> Update @reloadmobdb to update living mobs

npc/quests/quests_morocc.txt
- Fixed an issue with a cooldown after killing Wounded Morroc.
https://github.com/rathena/rathena/issues/4205 
https://github.com/rathena/rathena/pull/4207
=> Fix Wounded Morocc Cooldown

conf/messages.conf, doc/atcommands.txt, src/map/atcommand.c, src/map/atcommand.h
- list of costume and shadow equipments
- refine all equipments option
```
Please enter a position bitmask and an amount (usage: @refine <equip position> <+/- amount>).
-3: Refine All Equip (Shadow)
-2: Refine All Equip (Costume)
-1: Refine All Equip (General)
1: Headgear (Low)
2: Hand (Right)
4: Garment
8: Accessory (Left)
16: Body Armor
32: Hand (Left)
64: Shoes
128: Accessory (Right)
256: Headgear (Top)
1024: Costume Headgear (Top)
2048: Costume Headgear (Mid)
4096: Costume Headgear (Low)
8192: Costume Garment
65536: Shadow Armor
131072: Shadow Weapon
262144: Shadow Shield
524288: Shadow Shoes
1048576: Shadow Accessory (Right)
2097152: Shadow Accessory (Left)
2097152: Shadow Accessory (Left)
```
none
[cont]: …
=> Update refine atcommand

conf/map/battle/drops.conf, src/map/battle.c, src/map/battle.h, src/map/mob.c
Added battle config `autoloot_adjust` that allows autoloot to take player drop penalties and bonuses into account.
Credit to [Aleos and others](https://github.com/rathena/rathena/commit/63daab5860cc20b1fefc18c93c4c8387c724f871)
https://github.com/rathena/rathena/issues/2540
=> Added battle config autoloot_adjust

src/map/script.c
- added missing costume equipment validation for both `isequipped()` and `isequippedcnt()`
none
=> Update script command isequipped count

db/re/item_db.conf
- Removes limit of Turisus runestone, Asir runestone and Pertz runestone amount that can be hold.
- Increases limit of other runestones amount that can be hold to 60.
Source : [divine-pride](https://www.divine-pride.net/forum/index.php?/topic/3723-kro-classes-improvement-project/&tab=comments#comment-5514) / [GnjoyTW](https://ro.gnjoy.com.tw/notice/notice_view.aspx?id=2112)
none
=> Update Runestones stack limit

db/constants.conf, db/mob_db2.conf, db/pre-re/mob_db.conf, db/re/mob_db.conf, doc/script_commands.txt, src/map/battle.c, src/map/mob.c, src/map/mob.h, src/map/script.c, src/map/script.h, src/map/skill.c
- ref: https://github.com/idathena/trunk/commit/e267d2e2dada6196b479a6f2f35e9d25291ef22b
- adjust the damage taken by monster. (default = `100 = 1x`)
**New constant values for script commands**
- `getmonsterinfo(...)` - `MOB_DMG_TAKEN_RATE`
- `setunitdata(...)` - `UDT_DAMAGE_TAKEN_RATE`
- `getunitdata(...)` - `UDT_DAMAGE_TAKEN_RATE`
part of [KRO : MVP bosses adjustment](https://www.divine-pride.net/forum/index.php?/topic/3318-kro-mvp-bosses-adjustment/)
=> Update mob_db - DamageTakenRate field

src/map/clif.c, src/map/pc.h, src/map/trade.c
Add some missing checks into clif.c
=> Add some missing checks into clif.c

db/constants.conf, src/map/npc.h
=> Update NPC Identity

db/quest_db.conf, db/re/mob_db.conf, npc/jobs/valkyrie.txt, npc/re/mobs/fields/yuno.txt
- Quest allow player to waive the transcendent cost.
Quest Walkthrough
https://www.youtube.com/watch?v=vFYlweubU2M
Monster Spawn
http://s010381.blogspot.com/2019/04/blog-post_87.html
<details>
Quest seem to be introduced in KRO around 2012 April I think
</details>
none
=> Add Library Mistake Quest

conf/map/battle/guild.conf, src/map/battle.c, src/map/battle.h, tools/configconverter.pl
This pull request removes some legacy code and legacy battle flags.
A bit of backstory on this... when investing in your castle's defenses, your Emperium and Guardian's defenses and HP increases resulting in decreased damage taken when enemies attack them.
Back in the day, jAthena's team wasn't really sure to the full extent how to handle this. So they added this battle config, and a few lines of code related to reducing the overall damage taken based on the castle's defense number.
However, this introduced a bug, that when a castle reached 100 defense, the damage taken was reduced to 0, making the Emperium and Guardians unkillable. I commented out this code during eAthena as a hotfix. The correct method was implemented by increasing the defense stats and hp within status.c thus making …
=> Removed jAthena 1082 legacy code related to Castle Defense Rate.

conf/messages.conf, src/map/battleground.c, src/map/channel.c, src/map/clif.c, src/map/homunculus.c, src/map/irc-bot.c, src/map/mob.c, src/map/pc.c, src/map/skill.c
Some of the strings were hardcoded in the source,
moved them to messages.conf
#1282 
[//]: # (**NOTE** …
=> Moved hardcoded messages to conf

db/pre-re/item_db.conf, db/re/item_db.conf
The item is supposed to resist curse for 40% and stun for 10%.
https://www.divine-pride.net/database/item/5330
Merge from https://github.com/rathena/rathena/commit/9f4e40d490c1091ebe844119d81b7beea1ba0657
=> Update Drooping Kitty item bonus

src/map/status.c
Show/update HP bar when unhiding in a party.
**Issues addressed:** none?
=> Fix HP bar not showing when unhiding in a party

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c
Credit to: https://github.com/rathena/rathena/commit/fc2c6e02
Fix Magnum Break delay which accidentally had an undocumented hard-coded cooldown of 2s, which couldn't be reduced by Bragi.
Stated here in more detail: https://github.com/rathena/rathena/issues/4191
=> Correct Magnum Break delay

npc/pre-re/quests/quests_payon.txt, npc/pre-re/scripts.conf, npc/quests/quests_payon.txt, npc/re/cities/brasilis.txt, npc/re/quests/quests_payon.txt, npc/re/scripts.conf, npc/warps/cities/lighthalzen.txt, npc/warps/cities/yuno.txt
Update NPC locations
Merge from rAthena
https://github.com/rathena/rathena/commit/752d3143f5f9cabcc5a6326db2cf75102954e887
https://github.com/rathena/rathena/commit/0d1eb9948371a95ff0f4b9326f5c3a8fc3ad1d01
https://github.com/rathena/rathena/commit/ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae
Credits: https://github.com/JohnnyPlayy
=> Update NPC locations

db/sc_config.conf, src/map/status.c, src/map/status.h
Move boss resistance to status to the sc config
=> Dehardcode status effect boss resistance

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c, src/map/skill.h
Move skill combo check to a skill db flag instead of hardcoded list
=> Dehardcode combo skills check

.travis.yml, sql-files/upgrades/2017-03-15--14-29.sql, sql-files/upgrades/2019-10-12--14-21.sql, tools/checksql.sh, tools/php-sqllint/bin/php-sqllint, tools/php-sqllint/build.xml, tools/php-sqllint/composer.json, tools/php-sqllint/composer.lock, tools/php-sqllint/src/phpsqllint/Autoloader.php, tools/php-sqllint/src/phpsqllint/Cli.php, tools/php-sqllint/src/phpsqllint/Renderer.php, tools/php-sqllint/src/phpsqllint/Renderer/Emacs.php, tools/php-sqllint/src/phpsqllint/Renderer/Text.php, tools/php-sqllint/src/stub-phar.php
Add shell/php script for validate sql files.
Fix syntax errors in update scripts.
=> Add script for sql files syntax validation

db/pre-re/item_chain.conf, db/pre-re/item_db.conf, db/re/item_chain.conf, src/map/itemdb.c, src/map/itemdb.h, src/map/pc.c, src/map/pc.h
also fixes an issue with resurrection tokens
=> Add support for auto exp insurance items

db/quest_db.conf, db/re/item_db.conf, db/re/mob_db.conf, npc/re/jobs/2e/rebellion.txt, npc/re/scripts_jobs.conf
Added Job Change quest of rebellion and supporting monster/items.
Some item/monster entries taken from rA database and some are having placeholder values.
=> Added Rebellion Job Quest

conf/messages.conf, db/constants.conf, db/sc_config.conf, doc/script_commands.txt, src/map/atcommand.c, src/map/pc.c, src/map/pc.h, src/map/script.c, src/map/script.h, src/map/skill.c, src/map/status.c, src/map/status.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Support for the new mado gear outfit.
=> Implement support for switching madogear type

tools/mobdbconverter.py
Updated mobdbconverter to support Race, Size and Element constants
None
=> Updated mobdbconverter tools

doc/script_commands.txt, npc/custom/itembind.txt, src/map/script.c
- improve readability.
- already exists in core, why not expose it to npc script too.
none
=> Added Item Bound Type constants

src/map/battle.c
Thanks to Marida from oRO Dev Team for fixing this.
Stop Basicila from restraining boss monsters.
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/1276
**Issues partially addressed:** https://github.com/HerculesWS/Hercules/issues/2420
=> Fix Basilica unintentionally restraining boss mobs

db/pre-re/item_db.conf, db/re/item_db.conf
Updated items 12459-12465.
* Added bonus scripts.
* Fixed names in pre-RE item DB.
**Issues addressed:** #1196
=> Update items 12459-12465

doc/script_commands.txt, src/map/script.c
Regarding [this topic](https://herc.ws/board/topic/17846-possible-to-move-characters-player), I'd like to add `unitiswalking()` script command to improve the usability of `unitwalk()` script command.
=> Add unitiswalking() script command

src/map/clif.c
- disable selling of favorite item to NPC.
favorite items are currently can be sell to NPC.
=> Item with favorite flag can't sell to NPC.

db/constants.conf, db/pre-re/item_db.conf, db/re/item_db.conf, db/sc_config.conf, src/map/pc.c, src/map/skill.c, src/map/status.c, src/map/status.h
Add 7 new status changes and use them for the related items.
Closes #1177
=> Add new status changes and update related items

doc/atcommands.txt, src/map/atcommand.c, src/map/atcommand.h, src/map/clif.c, src/map/pc.h
* Fix the issue, where not even the fake name shows up, when using `@fakename` in RE clients.
* Add parameter `options` to `@fakename`, to be able to select which names will be displayed.
Closes #2168
Closes #1966
=> Fix/extend @fakename

src/map/map.c, src/map/map.h, src/map/quest.c, src/map/script.c
Fixed various memory violations and wrong handling of npc_data in quest info
=> Questinfo memory violation and handling fixes

CHANGELOG.md
milestone: https://github.com/HerculesWS/Hercules/milestone/42
=> Changelog for v2020.04.05

db/mob_db2.conf, db/pet_db2.conf, db/pre-re/mob_db.conf, db/re/item_combo_db.conf, db/re/item_db.conf, db/re/mob_db.conf, db/re/mob_skill_db.conf, db/re/pet_db.conf, src/map/mob.c
Renewal pet DB update.
**Issues addressed:** #2435 
Sprites for the jRO exclusive pets can be found here: https://herc.ws/board/files/file/498-jro-exclusive-monsters/
=> Renewal pet DB update

src/map/map.c, src/map/mob.c, src/map/pc.c, src/map/pet.c, src/map/skill.c
The `*=` operator was misused in some cases which caused unexpected results.
=> Fix usage of *= operator

doc/mob_skill_db.md
I needed an doc for the mob_skill_db.conf to create some Custom Mobs and Adjust some skill settings in other Mobs.
So i created an new doc file for this.
All Constants and States are found in mob.c and mob.h in */src/map/
The Only thing is to adjust the Language :X
=> New Doc: mob_skill_db.conf

src/map/battle.c, src/map/skill.c
Fix the skill type of RK_DRAGONBREATH and RK_DRAGONBREATH_WATER, they should be BF_WEAPON in official server, and they support bLongAtkRate bonus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1304)
=> Fix some skills bugs

db/pre-re/item_db.conf, db/re/item_db.conf, src/map/status.c
I was told that the changes made in #2614 have no effect because of a missing implementation of the `SC_RESIST_PROPERTY_*` status changes. Well, that's true. :grin:
I have to admin that I didn't check this. Sorry. But even if they had fully been implemented, affecting 1 element for each status change would have led to problems anyway.
Because the 4 *proof Potions (12118-12121) and Undead Elemental Scroll (12279) share the same status changes and icons, they'd unpredictably influence each other. For example mutual status change negation or icon removal due to different duration.
My implementation of the  `SC_RESIST_PROPERTY_*` status changes is based on the *proof Potions and affects 2 elements each.
I added icon display to `SC_ARMOR_RESIST` and use it in the Undead Elemental Scroll's …
=> Implement SC_RESIST_PROPERTY_* and icon display for SC_ARMOR_RESIST

npc/re/quests/quests_brasilis.txt
The dogs were unable to reappear because they did not have a unique name.
=> Fixed lost puppies quest

src/map/chrif.c
Save character data to the database before changing account/character gender to prevent data corruption through job class mismatch.
**Issues addressed:** #985
=> Secure gender changing

src/map/clif.c
This adds the benefit of gaining an additional character for NPC names when whispering NPCs and does not break anything...
**Issues addressed:** #718
=> Enable receiving not NULL terminated whisper names with a length of 24 characters

.mailmap, AUTHORS, tools/authors.sh
Add nicks and emails from all commits into AUTHORS file.
With duplicates because for some people exists more than one emails.
=> Add nicks and emails from all commits into AUTHORS file

db/re/mob_db.conf
According to DivinePride and my Aegis data the drop chances are:
- Anubis drops White Wing Suits with a chance of 0,5%.
- Elusive Luciola Vespa drops Black Wing Suits with a chance of 0,25%.
**Issues addressed:** #562
=> Update drop chances of Black and White Wing Suits

src/map/pc.c
=> Fix an issue regarding using items when the storage is open.

conf/map/battle/player.conf
Player must be always faced north when warped.
=> Player always faces north when warped.

src/plugins/db2sql.c
Fix crash in db2sql plugin in escape string function.
=> Fix db2sql crash with mariadb client library

db/pre-re/attr_fix.txt, db/re/attr_fix.txt
The description of rows and columns was swapped.
=> Fix wrong comment in attr_fix.txt

conf/map/battle/skill.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c
Storage now closes when using teleport skill.
https://github.com/HerculesWS/Hercules/issues/1762
=> Storage now closes when using teleport skill.

src/map/npc.c
Fix npc selling behavior if price is over INT_MAX.
**Issues addressed:** #2780
=> Fix npc selling behavior if price is over INT_MAX.

src/map/clif.c
When spawning a character `clif_status_change2()` was used to re-apply status icons without an timer data.
To also send the status' timer data `clif_status_change()` should be used.
**Issues addressed:** #580
=> Pass timer data when re-applying status icons upon spawning character

npc/quests/quests_moscovia.txt
- Add missing `Baehideun4#ship::OnEnable` event call.
- Replace misplaced "next;" with "close;". (Not related to the issue.)
**Issues addressed:** #2715
=> Fix Moscovia quests getting stuck in infinite loop

doc/script_commands.txt, src/map/npc.c
- missing random item option's param array. (Part of #2379)
=> Update NPC OnSellitem Array List

src/map/skill.c
Old formula provides 305/1000 chances. This forces RG_SNATCHER to trigger with max chance of 200/1000(based on dp) and moved old formula to Pre-Renewal.
=> Fix RG_SNATCHER formula.

conf/messages.conf, src/map/pc.c
Since macro is used in message, I believe we can't move it to messages.conf yet, and it will display the format specifier instead of value
None
=> Fixed Experience Gain message

.mailmap, AUTHORS, conf/battlegrounds.conf, conf/char/char-server.conf, conf/common/socket.conf, conf/global/console.conf, conf/global/sql_connection.conf, conf/login/login-server.conf, conf/map/battle/gm.conf, conf/messages.conf, conf/network.conf, db/constants.conf, doc/constants.md, doc/option_drop_group.md, doc/script_commands.txt, src/config/secure.h
Just some typo errors in /conf/ that should be fixed.
Also, one improvement in understanding atcommand_mobinfo_type config (gm.conf).
=> Correction of few typo errors (conf/)

db/re/item_db.conf
Official says 3mins duration of this particular scroll.
=> Fixed 30mins duration to 3mins, which is the official one.

db/re/item_db.conf
Based on DP
```
When pure STR is 90 or higher, ATK + 10. When pure STR is 120 or higher, ATK + 10 additionally.
When pure INT is 90 or higher, MATK + 3%. When pure INT is 120 or higher, MATK + 2% additionally.
```
Also weight should be `10` not `100`
=> Added item bonus effects of Runes Boots.

src/map/script.c
=> Fix mercinfo_* constant value.

.github/workflows/build.yml, .github/workflows/clang10_test.yml, .github/workflows/gcc10_test.yml, .github/workflows/gcc9_test.yml, .github/workflows/mariadb.yml, .github/workflows/mysql.yml, .gitlab-ci.yml, tools/validateinterfaces.py
=> Fix github and gitlab ci

src/common/cbasetypes.h, src/plugins/generate-translations.c
Fix generate translations plugin on windows.
=> Fix generate translations plugin on windows

src/map/status.c
This PR should fix the **MDEF and DEF reduction** of `SC_ODINS_POWER` status. It should be **-20** on level 1 and **-40** on level 2.
=> Fixed the MDEF and DEF reduction on SC_ODINS_POWER.

doc/script_commands.txt, src/map/script.c
- enable script to remove mercenary from attached player.
none
=> Add *mercenary_delete script command

db/item_options.conf
This PR add 3 missing item options available at least in Zero Client, the Magic Attack on Size
=> [Zero]Added missing item options

npc/merchants/cash_hair.txt, src/map/clif.c
Removed two duplicated entries
=> Removed two duplicated entries

db/sc_config.conf
This PR should fix the night mode issue not working for so long.. Thanks @4144 for the tip :D
**Issues addressed:** https://herc.ws/board/topic/18572-night-command-not-working/
=> Nightmode Fix

src/map/status.c
=> Fix regeneration

src/char/geoip.c
Fix possible wrong ip check in geoip.c
=> Fix possible wrong ip check in geoip.c

src/map/npc.c
- remove duplicated codes.
- followup https://github.com/HerculesWS/Hercules/commit/a3a7a98c5641e5603e84ef602aff6ba59acaadaf
none
=> Refactor NPC parse mapflag codes

src/map/status.c
Based from [iRO Group A Songs](https://irowiki.org/wiki/Group_A_Songs), Frigg Song is no longer part of it.
=> Removed SC_FRIGG_SONG from Group A Song Skills

conf/map/battle/client.conf
made it a little more nice for the eyes to read, since we are not using micro sized monitors anymore
=> A few updates to client.conf

doc/script_commands.txt
- fix variable name of array.
Fix part of #2843 
we can't actually merge this PR yet. This is because the following name exceed the max variable name length `> 24 chars`.
```
@cartinventorylist_identify[]      - whether it is identified.
@cartinventorylist_attribute[]     - whether it is broken.
@cartinventorylist_opt_id1~5[]     - array of random option id.
@cartinventorylist_opt_val1~5[]    - array of random option val.
@cartinventorylist_opt_param1~5[]  - array of random option param.
```
Shorten the length of current variable name?
or perhap we can consider to drop the `cart` keyword? and leave it same with `getinventorylist_***`?
- theorically, they are still in the `inventory` of `cart` lol
- its less used probably, and its up to user who use the script …
=> Update *getcartinventorylist documentation

conf/messages.conf, src/map/atcommand.c, src/map/battleground.c, src/map/clif.c, src/map/guild.c, src/map/pc.c, src/map/rodex.c
Moved a few messages that weren't present in messages.conf yet, please **NOTE** that I'm not a coder in any way, so a review is greatly appreciated as I mostly just copy&pasted pieces from everywhere...
Check specially the rodex.c one!
=> Moved a few messages to messages.conf

doc/script_commands.txt, src/map/script.c
Minor change to enable to use both a char name or an account id in buildin_getcharid
=> Allow to pass an account id to getcharid

src/map/clif.c, src/map/party.c, src/map/party.h
Adjusted the name of defines to better suit their purpose.
https://github.com/HerculesWS/Hercules/issues/1234  references: https://github.com/rathena/rathena/commit/ed7157c80b0da86aa81d3cfee5e9b9679938b4e2 …
=> Refactored Party Booking defines.

doc/script_commands.txt, src/map/script.c
Added checking if target npc exists.
Enable the script to specify which NPC to execute the commands.
_(most of the waitingroom related script commands enable to specify which NPC to execute, except these 2.)_
Master
**Deprecated script command :**
`*kickwaitingroomall({"<NPC object name>"})`
```
*waitingroom("<chatroom name>", …
```
=> Update waitingroom script commands.

src/map/pc.c, src/map/pc.h
pc_calc_pvprank_sub cannot hook by plugin
fix pc_calc_pvprank_sub cannot hook by plugin
* Master
none
=> fix pc_calc_pvprank_sub cannot hook by plugin

db/re/item_db.conf
Add missing "Card" suffix to Fruit Pom Spider Card.
**Issues addressed:** #2896 
=> Add missing "Card" suffix to Fruit Pom Spider Card

src/map/battle.c, src/map/battle.h, src/map/elemental.c, src/map/mob.c, src/map/npc.c, src/map/npc.h, src/map/path.c, src/map/path.h, src/map/pc.c, src/map/pet.c, src/map/script.c, src/map/skill.c, src/map/status.c, src/map/unit.c, src/map/unit.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
All commits are guaranteed to compile *on their own*. If not, please mention this in the PR.
All commits are guaranteed to be as atomic as possible to make the reviewing as enjoyable and easy as possible.
The following functions have been refactored:
- unit->walktobl
- unit->run_hit
- unit->run
- unit->escape
- unit->movepos
- return value fix in unit->walk_toxy_timer
- unit->blown
- path->blownpos (related to unit->blown change)
- added npc->handle_touch_events function
Changes that were made can be summarized as follows:
- Add proper documentation in doxygen-format.
- Move variables declaration closer to their first use
- Correct mistreatment on checks of non-boolean variables
- Rename some variables to clarify their use
- Save re-used *calculations* in variables or create local macros …
=> Refactor unit.c - Part II

.github/workflows/build.yml, .github/workflows/clang10_test.yml, .github/workflows/gcc10_test.yml, .github/workflows/gcc9_test.yml, .github/workflows/mariadb.yml, .github/workflows/mysql.yml, src/common/sql.c
Fix compilation with new mysql/mariadb client libraries
=> Fix compilation with new mysql/mariadb client libraries

src/map/map.c, src/plugins/mapcache.c
Add support for rsw formats up to 2.5 for reading water level
=> Add support for rsw formats up to 2.5 for reading water level

src/map/skill.c, src/map/skill.h
before I follow the guidelines, (just copy paste anyway)
how to run HPMHook update on your own emulator ? (my own test server)
because this is even causing error when compiling locally
=> Remove skill->get_linked_song_dance_id

src/map/status.c, src/map/status.h
https://herc.ws/board/topic/19033-cell_pvp/?do=findComment&comment=99012
better add a function for it or I'll overload the function and do something stupid like this
https://gist.github.com/AnnieRuru/f6f75c9cbeb60cd49161757a2bcf3d09#file-cell_pvp_1-7z-c-L653-L674
Add status_check_skilluse_mapzone function for plugin manipulations
* Master
maybe other flag in other function also affected ?
need to take a look ...
=> Add status_check_skilluse_mapzone function for plugin manipulations

src/map/unit.c
Access sc before nulling it ....
**Issues addressed:** #2923
=> Fix a guaranteed segment fault in unit->run_hit

src/map/clif.c, src/map/clif.h, src/map/packets_struct.h
=> Adds enum for client side action types

conf/map/battle/misc.conf, src/map/atcommand.c, src/map/battle.c, src/map/battle.h, src/map/elemental.c, src/map/map.c, src/map/map.h, src/map/mob.c, src/map/script.c, src/map/skill.c, src/map/unit.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Refactor map->search_freecell so it's readable.
Add an `enum freecell` for flag parameter of map->search_freecell
Introduce search_freecell_map_margin battle configuration in misc.conf set to 15 by default,
it makes map->search_freecell skip 15 cells on all 4 sides of any map. (As Aegis does)
This affects Teleports and Monster spawning and fixes mobs spawning in cells that are known as dead cells or outside of the map.
Research in Aegis was made to validate that this is the case for teleporting and monster spawning.
Happy reviewing and thanks in advance :)
=> Introduce map border for map->search_freecell, fixing dead cell bugs.

db/quest_db.conf, src/map/clif.c, src/map/mob.c, src/map/quest.c, src/map/quest.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc, tools/HPMHookGen/HPMHookGen.pl
These changes add support for hunting quests for any monsters, level range restricted, map restricted missions.
=> Add more options to the quest database 

db/pet_db2.conf, src/map/clif.c, src/map/itemdb.h, src/map/map.c, src/map/npc.c, src/map/pet.c, src/map/pet.h, src/map/script.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
PetDB2 no longer overrides entry of PetDB
Closes #2181 
[//]: # (**NOTE** Enable the setting "[√] Allow …
=> Fixed Issue #2181

configure, configure.ac, src/common/atomic.h, src/common/cbasetypes.h, src/common/sql.c, src/common/sysinfo.c, src/common/sysinfo.h, src/common/winapi.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc, src/plugins/HPMHooking/HPMHooking_login.Hooks.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
=> Fix compilation with mingw

db/pre-re/skill_db.conf, db/re/skill_db.conf, db/sc_config.conf, src/map/status.c, src/map/status.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
=> Dehardcode status change skill assosiation

.github/workflows/codeql-analysis.yml
Remove git checkout HEAD^2 from codeql-analysis.yml.
=> Small CI fixes

src/map/unit.c
Fix possible use after free in unit_skilluse_id2.
=> Fix possible use after free in unit_skilluse_id2

npc/kafras/kafras.txt
Small fix with kafra's savepoint message in **alb2trea**
=> Kafra savepoint message typo

db/re/skill_db.conf
PR should fix the cast time Emergency Call without ignoring `unit_skilluse_id2`
=> Fixed GD_EMERGENCYCALL casttime

db/sc_config.conf
When you're under SC_DEFSET or SC_MDEFSET, their respective status icon should show up.
=> Fixed SC_DEFSET and SC_MDEFSET status icon display.

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c, src/map/skill.h
Configure skills that can be blocked by `SC_STASIS` and `SC_KG_KAGEHUMI` via skill_db.conf
=> De-hardcode skills blocked under SC_STASIS and SC_KG_KAGEHUMI.

src/map/skill.c
This should prevent manhole from working to guardians and emperium.
=> Fixed manhole shouldn't work on Guardians.

src/map/script.c
Signed-off-by: Samuel23 <johnsamuel_santos3@yahoo.com>
- [√] I have followed [proper Hercules code styling][code].
- [√] I have read and understood the [contribution guidelines][cont] before making this PR.
- [√] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.
Decarding should run unequip script of cards
https://github.com/HerculesWS/Hercules/issues/2922
=> Fix successremovecard doesn't run unequip script

src/map/status.c
Fix issue with not working skill/status.
Fixes issue #2977
=> Add missing {} after if in status.c

src/map/battle.c, src/map/status.c
Fix crash with skill WHITEIMPRISON.
Fix possible crash with SWORDREJECT and/orASC_BREAKER.
=> Add missing free block lock/unlock for prevent dangling pointer usage

src/map/clif.c
=> Fix adoption context menu

src/map/battle.c, src/map/map.c, src/map/map.h, src/map/mob.c, src/map/party.c, src/map/script.c, src/map/skill.c, src/map/status.c, src/map/unit.c
Add guard check method and macro for check map locks count
=> Add guard check method and macro for check map locks count

src/map/battle.c, src/map/skill.c, src/map/status.c
While under Water Screen...
* It's master should now heal 1,000 HP every 10 seconds.
* All damage inflicted by it's master will be deflected to the Elemental Spirit(Aqua).
=> Water Screen Skill Fix

src/map/instance.c, src/map/instance.h
Reloads instance map flags from the source map
Note: I spent a decent amount of time making sure this wasn't being done elsewhere during the reload script process.  However the instance code/structures still don't make a ton of sense to me so I could be misunderstanding.
#3002
=> reload instance map flags

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c
Fixes the visual effect and flag of SO_CLOUD_KILL. Thanks @Asheraf 
**Issues addressed:** #2978 
=> Killing Cloud Fix

src/map/skill.c
Explicitly define the targets that should be ignored by UNT_MANHOLE.
**Issues addressed:** #2964 
=> Explicitly define ignored by UNT_MANHOLE.

src/map/clif.c
- [√] I have followed [proper Hercules code styling][code].
- [√] I have read and understood the [contribution guidelines][cont] before making this PR.
- [√] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.
Fix a bug when no items to refine, can't equip anything
[Discord issue](https://discord.com/channels/306632465294819331/306634170858471425/844372061900111902)
=> WeaponRefine Fix

db/re/skill_db.conf
Renewal Neutral Barrier cooldown is based per level.
https://www.divine-pride.net/database/skill/2273
=> Renewal Neutral Barrier Cooldown

src/map/clif.c, src/map/packets_struct.h
=> Update some guild related packets to use structures

db/re/skill_db.conf
Fixed re skill_db indentation, and removed empty lines from the end of the file
=> Fixed re skill_db indentation

src/map/map.c, src/map/map.h
Fix crash on double bl deletion.
=> Fix bl double deletion

src/map/status.c
Tera's SC_POWER_OF_GAIA should increase maxhp by 20% within the aoe.
=> Fix Power of Gaia MaxHP effect.

src/common/mmo.h, src/map/skill.c
Change MAX_SKILL_ID to 10020.
Check skill id for smaller than MAX_SKILL_ID while loading skill db.
=> Fix max skill id

src/map/battle.c
Piercing critical attack should work in renewal.
**Issues addressed:** #3022 
=> Fixed piercing crit damage

db/pre-re/item_db.conf, db/pre-re/sc_config.conf, db/pre-re/skill_db.conf
This should make rebellion work in pre-re using renewal skill_db and sc_config.
=> Missing Rebellion config and db for Pre-RE

src/map/skill.c
PR should fix the animation not showing on newer clients.
**Post-fix on 2019-05-30 Ragexe:**
EDIT: Need to test on RE too.
**Issues addressed:** #2511  
=> Fixed ignition break animation not showing on newer client.

db/pre-re/sc_config.conf, db/re/sc_config.conf, src/map/skill.c, src/map/status.c, src/map/status.h
Added `NoBBReset` for sc that cannot be reset by **Rebellion's Banishing Buster** skill
=> NoBBRest New SC Type

db/pre-re/skill_db.conf, db/re/skill_db.conf
This works same as #1149, which is stalled PR.
=> Blast, Claymore and Land Mines Card Damage Reduction

src/map/battle.c
In renewal, when you're buff with kaite, damage to you will be increase by 400% as long as its melee.
=> Renewal Kaite Damage Increase

db/pre-re/sc_config.conf, db/re/sc_config.conf, src/map/status.c, src/map/status.h
=> Add new status config flag NoMagicBlocked

db/pre-re/sc_config.conf, db/re/sc_config.conf
This fixes `SC_GENTLETOUCH_CHANGE` watk increase to be applied.
**Issues addressed:** #1629 
=> Missing watk calcflag

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/skill.c
This PR should fix `KO_JYUMONJIKIRI` not working properly. You should be able to use particular skill:
- left and right hand ain't bare fist
- right hand can be shield.
=> Fixed KO_JYUMONJIKIRI weapon type requirement.

src/map/atcommand.c, src/map/clif.c, src/map/clif.h
=> Fixed multiple VS compiler warning

db/pre-re/item_db.conf, db/re/item_db.conf, doc/item_db.txt, src/map/clif.c, src/map/itemdb.c, src/map/itemdb.h, src/map/npc.c, src/map/pc.c, src/map/pc.h, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
If `IgnoreDiscount` is enabled, the affected item that is listed on the npc ignores the effect of discount skill.
If `IgnoreOvercharge` is enabled, the affected item that is sold to the npc ignores the effect of overcharge skill.
Special thanks to @Asheraf for the help.
#3055
=> Added option to ignore the effect of discount/overcharge skill 

db/pre-re/sc_config.conf, db/re/sc_config.conf, src/map/status.c
=> Dehardcode status change vfx flag

src/map/status.c
=> Fix an incorrect castle id check

conf/messages.conf, src/map/atcommand.h, src/map/battle.c, src/map/clif.c, src/map/pc.h
=> Implement monster one shot kill state

db/captcha_db.conf, src/map/macro.c, src/map/macro.h, src/map/map.c
=> Add support for loading captcha images with server startup

doc/script_commands.txt, src/map/pc.c, src/map/script.c
should cover all card slots since these slots doesn't only store card anymore.
ex: enchantment items are also added beyond existing item's card slot.
script commands failed to check if item exists in these slots.
=> Update Item Card slot count

npc/pre-re/mobs/fields/niflheim.txt, npc/re/mobs/fields/niflheim.txt
Fix case 6 of Lord of Death spawning never happening.
=> Fix Lord Of Death case 6 never triggering

src/common/console.c, src/common/grfio.c, src/common/grfio.h, src/common/sysinfo.c, src/common/sysinfo.h
Report zlib errors on compress/uncompress api calls.
Show zlib version on server start.
Check is linked and compiled zlib versions is same.
=> Zlib error reporting

doc/script_commands.txt, src/map/script.c
enable to use script command to make an item on ground with the light pillar effect
none
=> Enable *makeitem to display DropEffect

src/map/script.c
Parameters to be dereferenced before checking with data_isint/data_isstring
This allows variables to be passed in rodex_sendmail
#3027
=> Fixes #3027 - Allows variable to be passed in rodex_sendmail 

conf/map/battle.conf, conf/map/battle/roulette.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c
Add configurable steps for roulette.
For change steps in client side need use one of this patches:
http://nemo.herc.ws/patches/ChangeRouletteBronzeLimit
http://nemo.herc.ws/patches/ChangeRouletteGoldLimit
http://nemo.herc.ws/patches/ChangeRouletteSilverLimit
=> Add configurable steps for roulette

src/map/clif.c
=> Remove unnecessary memcpy uses from packet code

src/map/clif.c
this one slipped though review 😅
regression from 8044455a81aad69559d59d3e6529aed3d37e5865
=> Fix an issue where item amount was never assigned in cart packet

.github/workflows/gccsnapshot_test.yml
Update asan dll version in gcc-snapshot ci.
=> Update asan dll version in gcc-snapshot ci

src/map/clif.c
=> Add missing check in clif.c

src/plugins/Makefile.in, src/plugins/sample.c
Add custom compiler flags in plugins. See sample.c
=> Add support for custom compiler flags in plugins

src/char/int_pet.c, src/char/inter.c, src/char/inter.h, src/char/mapif.c, src/common/Makefile.in, src/common/packets_struct.h, src/map/intif.c, vcproj-15/char-server.vcxproj, vcproj-15/char-server.vcxproj.filters, vcproj-15/map-server.vcxproj, vcproj-15/map-server.vcxproj.filters, vcproj-16/char-server.vcxproj, vcproj-16/char-server.vcxproj.filters, vcproj-16/map-server.vcxproj, vcproj-16/map-server.vcxproj.filters, vcproj-17/char-server.vcxproj, vcproj-17/char-server.vcxproj.filters, vcproj-17/map-server.vcxproj, vcproj-17/map-server.vcxproj.filters
Also convert the PACKET_INTER_CREATE_PET to use a structure.
=> Add common packets struct file for inter server packets

src/map/clif.c, src/map/packets_struct.h
=> Convert some packets to use struct-based format.

src/map/HPMmap.c
This PR should solve the issue regarding:
```
[Error]: HPMDataCheck:PLUGIN_NAME: 'PACKET_INTER_CREATE_PET' was not found
[Fatal Error]: HPM:plugin_load: 'plugins/PLUGIN_NAME.dll' failed DataCheck, out of sync from the core (recompile plugin)!
```
=> Missing include to HPMmap

src/map/atcommand.c, src/map/clif.c, src/map/clif.h, src/map/homunculus.c, src/map/map.h, src/map/packets_struct.h, src/map/pc.c, src/map/skill.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Follow-up to #3030. Merged both `clif_soulball` and `clif_spiritball` into one.
=> Spiritball Update

src/map/pc.c, src/map/pc.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Clean-up and interfaced pc_bonus_addele and pc_bonus_subele.
=> addele and subele Update

doc/constants.md, doc/script_commands.txt, src/map/script.c, src/map/script.h
Add gethominfo constants
**Issues addressed:** #3133 
=> Add gethominfo consts

src/char/pincode.c, src/map/clif.c
Fix style and variable type in function pincode_decrypt.
Fix party messages in old clients.
=> Different fixes

npc/other/monster_race.txt, npc/quests/quests_lighthalzen.txt, npc/quests/quests_louyang.txt
-  Make the order in dual monster races not matter as on officials
-  Simplify MN() function in Dual Monster Race logic
-  Ensure only 1 instance of the Pickpocket Quest NPC
-  Fix a case of the Doctor Quest taking items and not rewarding in return (and potentially some exploits)
=> Add some minor NPC fixes

.github/workflows/codeql-analysis.yml, src/common/ers.c, src/map/battle.c, src/map/skill.c, src/map/status.c, tools/validateinterfaces.py
This fixes a number of issues (many of which are false positives, but some are actual issues) reported by CodeQL. Each commit includes links to the security report and a comment on whether it's relevant or not.
**Issues addressed:** None, but the related security check reports are linked in each commits.
=> Various security fixes (as reported by CodeQL)

tools/setup_mariadb.ps1
This fixes an encoding issue in the output of setup maridb power shell script that was found during a discussion in discord: https://discord.com/channels/306632465294819331/306632465294819331/1033769412748128337
PowerShell's Out-File function uses UTF8 with BOM for UTf8 encoding, this encoding is not compatible with Hercules' libconfig implementation, causing several errors during config reading.
Using Set-Content and encoding it to UTF8 beforehand will ensure sql_connection is always generated in UTF8 without BOM.
Power Shell v6 seems to have a new encoding called "UTF8NoBOM", but I am not sure how power shell updates are sent to windows users, because my windows 10 machine fully updated is still on Power Shell v5. Given that, and that this script would be meant for quick …
=> fix output encoding for setup_mariadb script

src/map/clif.c, src/map/pc.c, src/map/rodex.c, src/map/skill.c
Add some missing checks for null in sd->inventory_data pointers
=> Add some missing checks for null in sd->inventory_data pointers

.github/workflows/tools.yml, sql-files/main.sql, tools/checksql.py
Add tool for check sql updates.
Fix sql updates issue in main.sql.
=> Add sql updates check tool

db/pre-re/sc_config.conf, db/re/sc_config.conf, src/map/status.c
1. Fixes the `RA_WUGBITE` immobile status.
2. `SC_FEINTBOMB` cloak status not working.
3. `SC__BLOODYLUST` returning `[Error]: UnknownStatusChange`.
=> Multiple StatusChange missing

npc/quests/thana_quest.txt
These are some small changes to Thanatos Tower released through the years. They only affect renewal servers and does NOT include the revamp update from 2019.
The changes are all based in kRO patch notes and some other info I found on the web (references at the end).
From 2012.04.04 kRO Patch:
- It is no longer required to have several players near the NPC to move to the 3rd floor. You can go to the 3rd floor by talking to the NPC
From 2016.06.29 kRO Patch:
- Burled Request quest exp reward updated
- Base EXP: 120,000 -> 1,200,000
- Job EXP : 100,000 -> 1,000,000
- Burled Request quest required level changed
- No level requirement -> Level 91 or higher required
- Changed weapon level required to progress Burled Request quest
- Level 4 Weapon equipped -> Level 3 or 4 Weapon equipped
- …
=> Updates to Thanatos Tower (renewal only)

src/map/pc.c, src/map/pc.h, src/map/rodex.c
attempt to fix #3009 & #3186, likely needs to be applied for zeny as well.
=> Queue up rodex item claim requests

README.md
Removed deprecated LGTM.com badge
source: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
=> Remove soon-to-be deprecated LGTM.com badge

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/script.c, src/map/skill.c, src/map/skill.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Small fixes to some skills. Applies to renewal & pre-renewal.
Commit messages copy/pasted below with some formatting
- the skill should fail and not consume requirements when:
1. being cast on Gunslinger class
2. being cast in a player that already have 5 spheres
3. being cast in non-players (but friend -- e.g. Mercenary)
for those cases it should send USESKILL_FAIL cause
Currently, they were consuming SP and not showing message.
- it should fail and not consume SP when
1. the target player doesn't have spheres
2. the target player is of Gunslinger class (due to never having
spheres)
3. the target player is friendly
- it should fail and consume SP when
1. Used in BOSS monster
2. Used in non-boss monster, but failing the 20% check
3. Using in non-player units (like mercenaries)
Currently, …
=> Some skill fixes

Hercules-17.sln, vcproj-17/plugin-HPMHooking_api.vcxproj
Fix vcproj-17 solution missing the required file for plugin HPM Hooking api project.
None.
=> Fixed vcproj-17 solution missing files for HPM Hooking api plugin

src/map/battle.c
Added hit bonus to TF_DOUBLE as explained [here](https://irowiki.org/classic/Double_Attack)
=> Fixed TF_DOUBLE not granting hit bonus when triggered

src/api/HPMapi.c, src/login/HPMlogin.c
Add missing include into HPMapi.c and HPMlogin.c
=> Add missing include into HPMapi.c and HPMlogin.c

vcproj-17/plugin-HPMHooking_api.vcxproj
Fixed issue regarding compiling api hooking via Visual Studio 17.x
=> Fixed api hooking compiling under vs 17.x

src/map/skill.c
Fixed Sage's dispel to work in duels.
#640 
=> Fixed SA_DISPEL not working in duels

.gitignore, vcproj/plugin-HPMHooking_api.vcxproj, vcproj/plugin-HPMHooking_char.vcxproj, vcproj/plugin-HPMHooking_login.vcxproj, vcproj/plugin-HPMHooking_map.vcxproj, vcproj/plugin-sample.vcxproj
Restore missing vcxproj files previously ignored by typo introduced in #3262 
=> Restored missing vcxproj files previously ignored.

src/map/clif.c
Fixes a regression from 6c8811b86b903a74160fdef5a41523191f577634
=> Fix incorrect assignment in item trade packet

.github/workflows/controller.yml, .github/workflows/windows.yml, tools/ci/windows.ps1
Github actions for windows, unlike appveyor this actually runs the server and some of the tests.
I've done a couple runs on my fork to verify the errors are being captured correctly at [test1](https://github.com/Asheraf/Hercules/actions/runs/8147194440) and [test2](https://github.com/Asheraf/Hercules/actions/runs/8147198539)
=> Adding github actions workflows for windows

src/char/char.c
This fixes a regression introduced by #3304 
=> Fix size of PACKET_CHARLOGIN_ONLINE_ACCOUNTS

npc/custom/quests/hunting_missions.txt, npc/other/marriage.txt, npc/quests/guildrelay.txt, npc/quests/partyrelay.txt, npc/quests/quests_louyang.txt, npc/quests/quests_morocc.txt, npc/quests/quests_nameless.txt, npc/re/instances/MalangdoCulvert.txt
Update all NPC to use new `getpartymember` ( #3305 ) script command.
none
=> Update all npc getpartymember commands
