HerculesWS/Hercules

src/char/char.c, src/char/char.h, src/char/inter.h, src/common/HPM.c, src/common/HPM.h, src/common/HPMi.h, src/common/core.c, src/common/core.h, src/common/malloc.c, src/common/malloc.h, src/login/login.c, src/login/login.h, src/map/atcommand.c, src/map/map.c, src/map/map.h, src/plugins/db2sql.c, src/tool/mapcache.c
- login_server, char_server, map_server as well as the tools (mapcache)
now have a common command line arguments handling mechanism.
- All of them now accept `--help` (`-h`), `--version` (`-v`) and
`--load-plugin`.
- login_server now accepts `--login-config` and `--lan-config` instead
of relying on positional arguments to override those files. The old
syntax will no longer work, please update your custom startup scripts.
- char_server now accepts `--char-config`, `--inter-config`,
`--lan-config` instead of relying on positional arguments. The old
syntax will no longer work, please update your custom startup scripts.
- mapcache now accepts `--grf-list`, `--map-list`, `--map-cache`,
`--rebuild` in place of, respectively, `-grf`, `-list`, `-cache`,
`-rebuild`.
- A new macro `CMDLINEARG()` is …
=> Command line arguments handling overhaul

src/map/clif.c
Was used skill id, but must be used skill idx.
=> Fix wrong id usage in clif_addskill.

src/map/skill.c
Warmer skill was regenerating 10% instead of 5% per 3 seconds.
Full details of report and fix result here: http://hercules.ws/board/tracker/issue-8579-sorcerer-warmer-giving-10-mhp-regeneration-per-3-seconds-instead-of-5/
=> Fix for Sorcerer Skill Warmer

db/quest_db.conf
Solo at Sphinx Dungeon Quest should require Zerom to be hunted.
=> Fix for "Solo at Sphinx Dungeon!" Quest

npc/custom/itembind.txt
Prevent the NPC to show rental items when players try to bind an items.
=> Avoid binding rental items.

npc/quests/quests_ein.txt
Because of some very old typo, this quest could never reach Minerals exchange dialog.
To save current server's progress, it's a good idea to rename `$einamanoama` to `$ein_amano` at **`mapreg`** table and make sure it's not > 60.
=> Fixed a bug in Einbech "Oridecon/Mineral Quest"

src/char/char.c, src/char/char.h, src/map/atcommand.c, src/map/chrif.c, src/map/chrif.h, src/map/script.c
- Fixes bugreport:8504
http://hercules.ws/board/tracker/issue-8504-changesex/
- Existing database entries with an incorrect per-character sex will be
fixed automatically when the character logs in to match the account's
sex, if the PACKETVER doesn't support per-character sex.
Although I have tested this on a live server for some time, I'd prefer to have someone review it, in case I missed to handle some cases. Thank you.
=> Fixed @changesex issues on PACKETVERs that don't support per-character sex

npc/dev/test.txt, src/map/script.c
Bugreport:8642 http://hercules.ws/board/tracker/issue-8642-script-engine-issue-quo/
=> Fix script function return always removing references from NPC variables.

db/re/item_combo_db.txt
-Fixed to make WoE Suit and WoE Boots get its set bonus when combined with WoE Manteau instead of WoE Muffler
-Ur Set, Nab Set, Sapha Set item combo effect fix
-Fixed Rogue of Treasure's combo effect with Cold Heart and Black Cat
=> WoE, Ur, Sapha, Nab, Rogue Treasure's combo effect

src/common/HPM.c
If you set a plugin to load and it fails for some reason, the server
will now exit. It will still warn when attempting to load a plugin
twice.
=> Plugin load failure now causes Fatal Error

src/char/int_party.c
mapif_party_created was incorrectly checking for a null pointer
=> Fixing party creation failure condition

npc/quests/lvl4_weapon_quest.txt
Always results "0" in dialog.
An ancient one. Discovered by Aafemt.
=> Fixed a bug in Lv4 Weapon Quest

doc/script_commands.txt, src/map/clif.c, src/map/pc.c, src/map/pc.h, src/map/script.c
At old times if npc what talking with player or player itself went in long distance or in other map, npc script terminated with error. Now it will not terminate after changes some months ago.
Current warp issue. If start talking with npc and warp, all npc related variables will be set to 0. And player cant continue talking to npc. This patch fix this issue.
More about issue and example code here: http://herc.ws/board/topic/10242-invalid-menu-selection-on-npc-after-warp/
Old patch what add this cleanup: https://github.com/HerculesWS/Hercules/commit/9babdbcbb4209a6ae861550eb662ac810d7ad886.
@MishimaHaruna what you can say?
=> Dont stop npc scripts after warp.

conf/subnet.conf, src/char/char.c, src/char/char.h, src/login/login.c, src/login/login.h, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc, src/plugins/HPMHooking/HPMHooking_login.Hooks.inc
If ip not in configured subnet, connection refused.
This can protect servers from brutforcing attacks.
=> Add checks for servers ip address in inter server connections.

src/map/status.c, src/map/status.h
So that One can invoke bonuses from plugin(by script->run)
since bonuses like bInt and bStr won't work directly, and needs to be in between status_calc_pc.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/HerculesWS/Hercules/pull/464%23issuecomment-76389663%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23issuecomment-77407786%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23issuecomment-77408165%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23discussion_r25882561%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23discussion_r25882595%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23discussion_r25882609%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/464%23discussion_ …
=> Additional Status Calculation for Plugins.

src/map/itemdb.c
It’ll now return the first result, rather than the last due to item2
being overwritten as it searches through the array.
=> Corrected search order in itemdb_searchname

conf/network.conf, conf/subnet.conf, src/char/char.c, src/char/char.h, src/common/socket.c, src/common/socket.h, src/login/login.c, src/login/login.h
The subnet.conf system has been rewritten to offer greater flexibility, and to fix some issues that appeared with 838321a36c79e71117320154c9b611c99e93af03.
It is now possible to enter, separately, LAN subnets:
- `lan_subnets`: This is essentially the same feature present in the old subnet.conf. Each entry in this list defines a (LAN, private) subnet the server is in. Clients connecting from the same subnet, will be redirected to the LAN IP rather than the default public IP. The format has been simplified, and it only requires one IP and one subnet mask (as opposed to a character and a map server IP).
- `allowed`: Allowed IPs are IP ranges a server (char to login or map to char) can connect from. Any attempt to connect as a server from an IP not included here, will fail. For convenience, a …
=> subnet.conf overhaul

npc/quests/lvl4_weapon_quest.txt
Dialog with rolled rock/paper/scissors didn't appear because of variable typo.
An ancient one. Discovered by Aafemt.
=> Fixed a bug in Lv4 Weapon Quest dialog

src/map/map.c, src/map/map.h
- Both "Normal" and "PK Mode" default zones will now be overwritten (instead of merged) by "GvG", "PvP" and "Battlegrounds" zones.
- Refactored some code to clarify intent.
=> Fixed merge behaviour of map zones. Fixes #572

src/map/battle.c
In pre-re Defender doesn't reduce damage from Acid Demonstration
http://hercules.ws/board/tracker/issue-8560-pre-renewal-defending-aura-bug/
=> Fixed defending aura bug in pre-renewal 

src/map/mob.c, src/map/npc.c, src/map/npc.h
This changes the way duplicates are created when they're needed in an instance.
Previously, duplicates were created through an opportunely forged fake script line, parsed as if it was a normal duplicate NPC loaded from a script. Now, it's done without formatting and parsing a script line.
This fixes #812.
=> Fix a warning when loading instance duplicates (#812)

src/map/atcommand.c
Like when some message_id from messages.conf is commented out, it crashes currently, but this will fix it and show "??" instead.
@4144 @MishimaHaruna
=> Fix Crash when message is not defined

conf/battle/player.conf, src/map/battle.c, src/map/battle.h, src/map/npc.c, src/map/npc.h
tested with
```
prontera,145,187,5	script	test1	-1,{}
prontera,155,187,5	script	test2	HIDDEN_NPC,{}
prontera,165,187,5	script	test3	HIDDEN_WARP_NPC,{}
```
apparently when using -1 with coordinates, the server doesn't throw error
=> Add new config to allow player vend/chat room nearby hidden npc (#834)

src/map/atcommand.c, src/map/clif.c, src/map/pc.c, src/map/pc.h, src/map/unit.c
Moved all idle time changes to its own function..
This allows for plugin to customize idle times and make their own separated idle time's for Walk/etc..
like, I only want to check when they last chat.
Also can be used with plugin to know if person is afk after entering xyz..
=> Added a function to update idle time

doc/script_commands.txt, src/map/script.c
Useful for scripts that temporary adjust the group id of players.
```
prontera,155,181,5	script	setgroupid	757,{
mes "Input new Group ID";
input .@groupid,0,99;
dispbottom "Current Group ID : "+getgroupid();
.@ouput = setgroupid( .@groupid );
// .@ouput = setgroupid( .@groupid,"name" );
// .@ouput = setgroupid( .@groupid,2000000 );
// .@ouput = setgroupid( .@groupid,strcharinfo(0) );
// .@ouput = setgroupid( .@groupid,getcharid(3) );
dispbottom "> Update : "+ ( .@ouput ? "SUCCESS":"FAILED" );
dispbottom "Latest Group ID : "+getgroupid();
close;
}
```
=> Add *setgroupid script commands.

src/map/atcommand.c, src/map/homunculus.c, src/map/pc.c, src/map/pc.h, src/map/skill.c
Rewritten skill_tree parser in a more robust way
- Fixes an issue that prevented skills with more than 4 pre-requisites
or more than 3 pre-requisites and a minimum level from being parsed
correctly (and without any warning or error messages).
- Removes the limit on 5 pre-requisites (replaced a fixed size array
with a VECTOR)
- Reduces memory usage of skill_tree from 794kB to 440kB (32 bit) or
523kB (64 bit).
- Fixes an issue that prevented multiple inheritance from working
correctly in rare cases (incorrect definition order), without any
warning or error messages. Now a warning is displayed if a job is
inherited before being defined.
- Fixes an issue that prevented skills inherited from being correctly
merged with the skills defined for the current job.
- Prevents a job from inheriting …
=> Skill tree fix

src/map/atcommand.c, src/map/script.c
- Negative refine value isn't allowed.
Create a NPC that give item using getitem2 script command.
```
prontera,155,175,5	script	Sample#getitem2	1_M_04,{
getitem2 5353,2,1,-1,1,4403,4403,4403,4403 );
end;
}
```
=> Fix *getitem2 and @item2 refine bug.

src/map/battle.c
Set the skillratio to 20*skill_lv as mentioned in skill describtions.
iro wiki: http://irowiki.org/wiki/Spear_Stab
ratemyserver: http://ratemyserver.net/skill_db.php?skid=58&small=1&back=1
=> Spear Stab damage adjustment

db/constants.conf, doc/script_commands.txt, npc/merchants/hair_dyer.txt, npc/merchants/hair_style.txt, src/map/script.c
the VAR_ constant added on this date
https://github.com/HerculesWS/Hercules/commit/f4278f36db32f35e535a0ea8feb1cf83ca95019e
then the LOOK_ constant added on this date
https://github.com/HerculesWS/Hercules/commit/a25c820fba6bd86fe2fb50e2b5b512295583522d
I compare the value, which both of them exist on the *setlook documentation,
with this script I made some times ago
https://github.com/AnnieRuru/customs/blob/master/scripts/Dressing%20Girl.txt
and found the one made by lone_wolf is wrong, brian is actually correct
so have to remove the one made by lone_wolf
also, the F_GetArmorType global function
https://github.com/HerculesWS/Hercules/blob/master/npc/other/Global_Functions.txt#L312
doesn't seem right, if the upper headgear cover mid, or lower, it will return default case
I wonder maybe …
=> Add EQP_ = Equipment Position constants

npc/re/jobs/3-1/archbishop.txt, npc/re/jobs/3-1/guillotine_cross.txt
continue on the adventure on my friends server...
he increased the BaseLevel on all jobs on db\re\exp.txt
although his server has [job changer npc](https://github.com/HerculesWS/Hercules/blob/master/npc/custom/jobmaster.txt),
but I found out the official script gives 3rd job exclusive items, so I do the 3rd class quest
what a weird thing is, my gypsy can do the wanderer job change quest on level100+, no problem
but my high priest can't start the quest .... what a stupid check
on a side note, I noticed warlock check with [BaseLevel > 94](https://github.com/HerculesWS/Hercules/blob/master/npc/re/jobs/3-1/warlock.txt#L61)
is this seriously official ?
although the npc only start the quest on level99+
=> Fix 3rd jobs BaseLevel requirement

src/char/int_guild.c, src/common/mmo.h, src/map/guild.c
I came across a custom patch that extended the guild_permission logic with additional features, controlled via atcommands. While cleaning it up to use enum constants instead of hexadecimal values, I found that the current form of GPERM_BOTH does not extend very well. So I tweaked the naming a bit. I also noticed that the same name, GPERM_BOTH, is used in two unrelated contexts, so I split off a more meaningfully named alias.
=> more meaningful names for fields of enum guild_permission

src/common/mmo.h, src/common/socket.h, src/map/clif.c, src/map/clif.h
Move P2PTR Macro to socket header and split the macro into two macros for WFIFO/RFIFO.
Change packet database enums to defines in mmo.h
=> Move P2PTR Macro and Define Packet DB enums

src/map/status.c
- PR_MAGNIFICAT HP Regeneration applies only in PRE-RENEWAL.
=> PR_MAGNIFICAT Skill Fix.

src/map/script.c
Reported in http://herc.ws/board/topic/11994-map-crashed-on-friendly-poring-quest-novice-quest/
=> Fix crash on npc emote, if npc not found.

src/char/int_party.c
Also not allow create party with empty or only spaces name.
=> Replace wrong wariable usage in party creation code (closed #1185)

npc/quests/quests_moscovia.txt
Fix to NPC [Larissa#mos_01] in script [npc/quests/quests_moscovia.txt] from [Help Mikhail] Quest.
delitem script uses ".@di" array instead of ".@n" array.
=> Fix to NPC [Larissa#mos_01] in script [npc/quests/quests_moscovia.txt]

src/map/script.c
my test:
prontera,156,153,5	script	afda#123	4_F_MAID,{
unittalk getnpcid(0),"Hi I m a npc!";
close;
}
after fixes
=> Unittalk script cmd shouldn't display the hidden name of npc

npc/jobs/2-1/wizard.txt
When failing the 2nd Wave of the Earth Room or the 1st Wave of the Fire Room you won't be correctly warped back, but get stuck.
This is due the NPCs "Room of Fire#Failed" and NPC "Room of Earth#Failed" not being correctly enabled, when the time limit is reached.
=> [Wizard Jobquest] Fixed getting stuck when failing some rooms.

src/common/cbasetypes.h
I'm not sure how I managed to squeeze this in the repo a while ago, but it did, and it just doesn't do anything.
I was just testing how MSVC optimized `swap`. Anyway, it should be removed :D
Thanks!
=> Remove swap testing code (leftover in cbasetypes)

npc/quests/quests_rachel.txt
By skipping quest 8102 you'd corrupt your questlog and mapserver would show those error messages:
You will still be able to complete rachel sanctuary quest, since quest 8102 is not necessary for the main quest.
The fix allows you to skip quest 8102 and also to do quest 8102.
This bug is not related to Issue #1256
=> Fixed a bug where you'd skip quest 8102 in rachel sanctuary

src/map/mob.c, src/map/party.c, src/map/pc.c, src/map/skill.c
- Now Renewal Level Penalty being calculated in pc_calcexp only
- Now Guild Tax is being paid after experience modifiers and not before
- Now Experience modifiers being calculated in right way as in aegis (Race modifiers -> PK modifiers -> Premium modifiers -> Buff modifiers)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1328)
=> Fix EXP modifiers to match aegis modifiers calclution.

src/plugins/db2sql.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1348)
=> db2sql plugin now will dump equip_job as Decimalinstead of Hexadecimal

npc/re/quests/quests_eclage.txt
-NPC checked for wrong quest and therefore didn't do anything on that part of the quest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1349)
=> Fixes Mystery Burglary Quest

npc/airports/airships.txt, npc/airports/einbroch.txt, npc/airports/hugel.txt, npc/airports/izlude.txt, npc/airports/lighthalzen.txt, npc/airports/rachel.txt, npc/airports/yuno.txt, npc/battleground/bg_common.txt, npc/battleground/flavius/flavius01.txt, npc/battleground/flavius/flavius02.txt, npc/battleground/flavius/flavius_enter.txt, npc/battleground/kvm/kvm01.txt, npc/battleground/kvm/kvm02.txt, npc/battleground/kvm/kvm03.txt, npc/battleground/kvm/kvm_enter.txt, npc/battleground/kvm/kvm_item_pay.txt, npc/battleground/tierra/tierra01.txt, npc/battleground/tierra/tierra02.txt, npc/battleground/tierra/tierra_enter.txt, npc/jobs/2-2/alchemist.txt, src/map/script.c, src/map/script.h, src/plugins/generate-translations.c
- Added support for concatenated strings in the .po files, as described in the [gettext documentation](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html):
```
msgid ""
"Here is an example of how one might continue a very long string\n"
"for the common case the string represents multi-line output.\n"
```
- Added header to the generated .pot file (improves compatibility with online translation services such as transifex)
- Converted npc/airports/ and npc/battleground/ to a HULD-compliant format (simplifies translation, especially to languages that have different sentence order or are much more terse than English, as per HULD best practices)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Huld improvements (2)

npc/cities/aldebaran.txt, npc/quests/quests_louyang.txt, npc/quests/skills/merchant_skills.txt
This request includes 3 fixes to quite old NPCs.
Luyoang Doctor Quest: Questlog being not cleared fixed.
Crazy Uproar Quest: Fixed requirements. (Blacksmiths & Alchemists needed Job Level 15 or higher, which is wrong)
Kafra Headquarter's Potato Trader: Fixed the menu being displayed incorrectly as well him entering you always into the lottery, without caring for your selection.
All tested(except Crazy Uproar Quest Fix) and working nicely on OriginsRO. ~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1392)
=> Fixes to Doctor Quest, Crazy Uproar Quest, Kafra HQ's Potato Trader

npc/quests/quests_ayothaya.txt
Just added a missing close; that stops an scope from falling through in quest dialogue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1398)
=> Added missing close;

conf/battle/gm.conf, src/map/atcommand.c, src/map/battle.c, src/map/battle.h
- OnPCBaseLvUpEvent
- OnPCJobLvUpEvent
Useful when debug `OnPCBaseLvUpEvent` / `OnPCJobLvUpEvent` script. 
Especially in a low rate server, you don't have to kill hundred of mob to gain a level to trigger the event to test the script you want to build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1396)
=> Enable @b/joblvl trigger OnPCLvUpEvent

src/map/clif.c
The showscript packet was being sent to all players logged in which can be
network intensive.
Thanks to @Tokeiburu & aleos89!
Based on https://github.com/rathena/rathena/commit/47a69c082a9520f14b19ebfd335c4956d0c5a13b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1401)
=> Corrected the showscript packet

src/map/map.c, src/map/npc.c
Fixed various issues in the functions that process npc_removed_list and map_removed
- Corrected DBMap options
- Re-implemented (and optimized) handling of "all" in npc_removed_list
- Removed the now useless special handling of `npc->addsrcfile("clear")` and `npc->delsrcfile("all")`, both superseded by `npc->clearsrcfile()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1435)
=> Fixes for npc_removed_list and map_removed

npc/mapflag/nomemo.txt, npc/mapflag/noteleport.txt, npc/re/other/dimensional_gap.txt, npc/re/scripts.conf, npc/re/scripts_warps.conf, npc/re/warps/other/dimensional_gap.txt
- original script by RagnarokNova rathena/rathena@7d0c7d8
full credits to him.
- removed onchat labels, added a variable to check for the timer instead of using enable/disablenpc and 3 npcs on 1 location
- using constants
- simplified script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1431)
=> Initial commit dimensional gap

src/plugins/db2sql.c
Trying to fix this error when importing `item_db_re.sql`.
```
ERROR 1264 (22003) at line 9768: Out of range value for column 'equip_locations' at row 1
```
Seems we are trying to insert `65536` to an `unsigned smallint` which could only handle `65535`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1451)
=> use mediumint for equip_locations in item_db.sql & item_db_re.sql

npc/cities/jawaii.txt, npc/cities/umbala.txt, npc/custom/etc/monster_arena.txt, npc/custom/etc/rpsroulette.txt, npc/other/divorce.txt, npc/quests/eye_of_hellion.txt, npc/quests/okolnir.txt, npc/quests/quests_13_1.txt, npc/quests/quests_ayothaya.txt, npc/quests/quests_moscovia.txt, npc/quests/seals/megingard_seal.txt, npc/quests/the_sign_quest.txt
Fixes #1176
On Aegis players set their HP to 0 by script are still alive. Since we don't want to copy this, scripts that set HP to 0 and expects the player to stay alive are changed.
Additionally some scripts where changed where the HP were set to 1% instead to 1 HP and also the percentheal -100 with intended death set into close2. In megingard_seal.txt a end; was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1473)
=> Fix cases were player were executed

db/re/item_db.conf
This fix for 
GN_CRAZYWEED and WL_CHAINLIGHTNING
should be
GN_CRAZYWEED_ATK
WL_CHAINLIGHTNING_ATK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1487)
=> Fix wrong skill name used to increase damage

src/map/script.c
The script command areawarp has been checking the wrong target map for ages. It has been checking the mapindex rather than the mapid and therefore returned a wrong result.
Original commit: rathena/rathena@ac2ba09
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1521)
=> Fixed areawarp cell check

doc/script_commands.txt
When trigger event label, it run as `donpcevent` not `doevent`, no player are attached to the script when it's triggering the event. 
No RID are attached to script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1537)
=> Update *waitingroom script document

npc/quests/quests_moscovia.txt
Some ancient typo, which results in `script_rid2sd: fatal error ! player not attached!` and never showing those messages.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1542)
=> Fixed announces from Koschei the Immortal (Moscovia Quests)

conf/map/battle/client.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/map.h
This patch removes the hardcoded chat area size and instead reads it from battle.conf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1562)
=> remove hardcoded chat area size

npc/mapflag/zone.txt
WoE:SE maps were missing GvG2 zone, allowing use of Leap/High Jump.
Fixes #1391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1565)
=> Adds GvG2 zone to WoE:SE maps

src/map/unit.c
issue #841
[Original Commit by Playtester on rAthena](https://github.com/rathena/rathena/commit/6f74f67da060a063183e1147dfc893c9454af853)
- Players will no longer get +2 range server-sided when using a target spell
- This will prevent players from modifying the client to get extra range
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1457)
=> Fixes Range Exploit

npc/other/auction.txt
getbattleflag was using a wrong string for feature confs, I believe this was caused when battle folder was converted into libconfig, as `feature.*` became `features/*` and this script wasn't updated. I checked the entire script folder and couldn't find any other `feature.*` to update.
Fixes #1580 as merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1581)
=> Fixes getbattleflag on npc/other/auction.txt

src/map/clif.c, src/map/packets_struct.h
Fixes named items having their names changed when near other players/name's owner. Fixes #1206 when merged.
There was 2 issues there:
- first: item name disappeared, because the client needs the character name when it's near
- second: name changing to another player, that's because when the player wich name is on the item walked near the one who had the item, unit_walking was sending the GID of the one who had the item instead of the one walking near, thus changing the name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1567)
=> Fixes named items having their names changed when near other players

src/map/clif.c
The negative bl->id must be in the second byte, so In newer packets AID must be changed instead of GID.
Fixes #1078 as merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1585)
=> Fixes disguise position de-synchronization

doc/script_commands.txt, src/map/script.c
It feels awkward to have to use `attachrid` just to get a variable of another player.. with this improved `getd` you can now do it without ever changing the rid. It can be used for both players and npcs, so it's basically a `getvariableofnpc` on steroids.
`getd("<var>"{, <GID>{, <default value>}})`
`getd("@var", getcharid(CHAR_ID_ACCOUNT, "player"), -1)`  
The above will return a reference to variable `@var` from player `player`, or else return `-1` if the player could not be found.
<br>
<br>
---
In the future I might make a `getparam(Param, <GID>)` which would return a reference to a param of another player (ie `Zeny`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1 …
=> getd enhancement

npc/re/merchants/shadow_refiner.txt
- double chance should only available for Enrich ores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1602)
=> Fix issue #1524

npc/woe-se/agit_main_se.txt
Fixes #1595. Adds a protection to 1st Barricade line on WoE SE maps to avoid splash damage without destroying Guardian Stones previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1596)
=> Barricade fix to Splash Damage

doc/script_commands.txt, src/map/script.c
`strcharinfo()` and `strnpcinfo()` can now work without an attached rid, and can get details from another GID than the attached pc/npc. It can also return a default value if the attached or target gid is not found.
* `strcharinfo(0)` will return the name of the attached player, or an empty string if there is no attached player
* `strcharinfo(0, "foobar")` will return the name of the attached player, or `foobar` if there is no attached player
* `strcharinfo(0, "foobar", id)` will return the name of the player with account id `id`, or `foobar` if the player could not be found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1589)
=> allow strcharinfo() and strnpcinfo() to take a GID

doc/script_commands.txt, src/map/script.c
- Added optional parameter to warp member from target map.
- Update to loop guild member using `g->member[]` data.
Sample Script:
```
prontera,155,181,5  script  NPC_1   757,{
npctalk "warp from here to here.";
warpguild( "prontera", 155, 170, getcharid(2) );
end;
}
```
```
prontera,155,171,5  script  NPC_2   757,{
npctalk "warp from payon to here.";
warpguild( "prontera", 155, 170, getcharid(2),"payon" );
end;
}
```
```
prontera,155,161,5  script  NPC_3   757,{
npctalk "warp from prontera to here.";
warpguild( "prontera", 155, 170, getcharid(2),"prontera" );
end;
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1496)
=> Updated *warpguild() script command.

doc/script_commands.txt, src/map/script.c
- add a new parameter to `addtimer`, `addtimercount`, and `deltimer` to make them usable on another player
- ~~~add new buildin: `areatimer("map", x1, y1, x2, y2, tick, "npc::event")`~~~
**Issues addressed:** (none)
(none)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1610)
=> allow the PC timer buildins to run on another player

npc/jobs/2-2/crusader.txt
If a player has Patriotism_Marks and Sacred_Marks before starting the quest, he'll skip the introductionary dialogue of the Crusader automatically.
(This actually irritated a player of mine heavily, making him believe the quest is bugged.)
He does his introduction and when you're willing to become Crusader, you'll be able to use your 2 Items to skip the Item Gathering part.
I moved one of the alternative first quest parts to the part where the player already has accepted the Item Gathering part. This is exactly at the location where it is in the original aegis script.
This also makes the 2nd very same code-part not obsolete anymore.
**Affected Branches: Master** 
**Issues addressed: None**
[code]: …
=> Fix wrong order of dialogue at Crusader Jobchange Quest.

db/constants.conf, doc/script_commands.txt, src/map/script.c
As requested by @Emistry, here's a buildin to check if the player has timers
* new buildin: `gettimer(<mode>{, <account id>{, "<event>"}})`
**Examples:**
* `gettimer(0)`
* will return the total number of timers attached to the player
* `gettimer(0, getcharid(CHAR_ID_ACCOUNT), "NPC::EVENT")`
* will return the number of timers attached to the player for event `NPC::EVENT`
* `gettimer(1, getcharid(CHAR_ID_ACCOUNT), "NPC::EVENT")`
* will return the number of ticks remaining before the next call to `NPC::EVENT`
* `gettimer(2, getcharid(CHAR_ID_ACCOUNT), "NPC::EVENT")`
* will return the number of ticks remaining before the last call to `NPC::EVENT`
* `master`
<sub>(none)</sub> …
=> add gettimer() buildin

src/map/script.c
Infinite Duration status would result in error since there was no timers
attached to it.
Added a condition to check if status is having infinite duration and
return value according to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1544)
=> getstatus() Update

conf/map/battle/items.conf, src/map/battle.c, src/map/battle.h, src/map/pc.c
Forces the un-equipment of arrows when a bow is unequipped.
Also adds a configuration to disable this setting.
In either case (on or off) it works only when compiled in renewal.
**Issues addressed:** #745 
Based on original PR by @Jedzkie in #1079 
=> Unequip arrows when a bow is unequipped. (RE only)

src/map/clif.c, src/map/packets.h, src/map/packets_struct.h
Add missing packets into packets.h from start of 2014 to end of 2015 years.
Found issue what some packets for ragexeRE for some months in 2014 will not works before or after this pull request. Conflicting packets was added to packets.h and was added comments about issue.
=> Add missing non shuffle packets for 2014 - 2015 years.

src/map/script.c
Related to the order of the arguments.
Fixes the order of the arguments of *setequipoption(<equip_index>,<slot>,<opt_index>,<value>);
I had forgotten to interchange <slot> and <opt_index>.
=> Fixes a minor typo in buildin_setequipoption

conf/map/battle/monster.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c
Original PR #1148 by @SamuelHercules committed on 8 Feb 2016
* Monsters no longer have Vulture's Eye level 10 and Snake's Eye level 10 learned by default
* When you tank Cecil Damon from 10-14 cells away, she will no longer use her target skills
* Added a configuration with which you can set the level of Vulture's Eye and Snake's Eye that monsters have learned
Merged rathena/rathena@cccd1496f716fe02a3db20780b6e52b3c33391b4
Credit: Playtester
**Affected Branches:** Master 
**Issues addressed:** #1148  …
=> Monster Vulture's Eye and Snake's Eye removed.

src/map/script.c, src/map/script.h
It seems that when we tested #1592 we only tested `@` variables (temp PC vars). For those variables it is suitable to use the generic `set_reg_ref_` because they store the absolute value (`char*` or `int`), but all other PC variables (`#`, `##` and no prefix) store a full `script_reg_` struct so they need a custom getter & setter.
**Affected …
=> fix for #1592 (getvariableofpc)

src/map/packets.h
Add missing non shuffle packets for 2013 ragexe client.
Move some packets added in wrong versions to past versions.
Non destructive changes for existing implemented packets. In other words it change nothing for already implemented packets, but fix possible missing packets issues.
=> Add missing non shuffle packets for 2013 ragexe client

conf/map/battle/player.conf, src/map/battle.c, src/map/battle.h, src/map/pc.c, src/map/pc.h, src/map/unit.c
kRO does not prevent players from logging out after connecting to its zone servers.
Credits to @secretdataz of rAthena
https://github.com/HerculesWS/Hercules/issues/981
[//]: # (Issue Tracker Number if …
=> Made prevent_logout effect on log-in optional

doc/script_commands.txt, npc/other/CashShop_Functions.txt, src/map/clif.h, src/map/pc.c, src/map/script.c
Update the *warpparty script commmand, credits to Dastgir
Coding-style fixes & whitespace adjustments in warpparty part in script.c
Our current implementation of …
=> Implemented official Giant Fly Wing Effect

doc/script_commands.txt, src/map/script.c
* add optional parameter `<account id>` to the following buildins:
* `checkoption()`
* `checkoption1()`
* `checkoption2()`
* `setoption()`
**Issues addressed:** *(none)*
- - -
I really only need this to check `Option_Invisible` on another player. …
=> allow checkoption et al to check another player

doc/script_commands.txt, src/map/script.c
* new buildin: `has_permission(<permission>{, <account id>})`
* See documentation in the [Files changed](https://github.com/HerculesWS/Hercules/pull/1712/files#diff-0) tab
* See [doc/permissions.txt](https://github.com/HerculesWS/Hercules/blob/master/doc/permissions.txt) for the list of permissions
* new buildin: `can_use_command("<atcommand>"{, …
=> add permission checking buildins, expose PC permission constants

doc/script_commands.txt, src/map/map.h, src/map/pc.c, src/map/script.c
* Expose `map_session_data->status.bank_vault` as `BankVault` to the script engine
* Expose `MAX_BANK_ZENY` to the script engine
* Update the documentation to reflect those changes
<br>
* Allows NPCs to manipulate the vault, so players with a client that does not support the vault packets can still deposit and withdraw money through a NPC.
<br>
```c …
```
=> expose the bank vault to the script engine

src/char/int_storage.c, src/map/storage.c
Special thanks to @MishimaHaruna for the fix.
Fixes an issue with storage saving where items weren't being matched correctly.
Fixes an amount updating issue with non-stackable items in `storage_additem()`
Credits to @MishimaHaruna.
**Issues addressed:** #1754 
More to find out.
[cont]: …
=> Fix storage saving checks and amount update.

src/char/char.c, src/char/int_storage.c, src/char/int_storage.h
The storage data is no longer cached in the char server. This removal
doesn't cause any performance loss, since the cached data was refreshed
(loaded from the database) after every save operation. This commit
moves the load at the beginning of the save rather than at the end, and
discars the cached copy after the save is completed.
Fixes #1754, related to #1752 and #1756
=> Fix a race condition when saving the storage on logout

src/char/int_storage.c
Fixes an issue where the replace statement is improperly formatted:
```
REPLACE INTO `storage` (`id`, `account_id`, `nameid`, `amount`, `equip`, `identify`, `refine`, `attribute`, `card0`, `card1`, `card2`, `card3`, `opt_idx0`, `opt_val0`, `opt_idx1`, `opt_val1`, `opt_idx2`, `opt_val2`, `opt_idx3`, `opt_val3`, `opt_idx4`, `opt_val4`, `expire_time`, `bound`, `unique_id`) VALUES('50', '2000000', '512', '27200', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0')('54', …
```
=> Fix replace statement formatting in storage save function.

doc/script_commands.txt, src/map/script.c
* new buildin: `isstr(<argument>)`
* This is required to implement [array_shift()](http://herc.ws/board/files/file/326-array-manipulation-functions/)
* **Original author:** @4144 
<br>
* new buildin: `getarrayindex(<array>)`
* This is required for array functions that loop through members, so you don't have to start from index 0 all the time
<br> …
=> new buildins: isstr, getarrayindex

doc/script_commands.txt, src/map/script.c
* Allow passing params to `readparam`
* you can still pass integers and constants like before
* Add missing `<player name>` parameter to the documentation of `readparam`
<br>
As @AnnieRuru pointed out in #840, doing the following:
```c
debugmes(sprintf("%d - %d", Hp, readparam(Hp)));
```
Will print, for example, `40 - 0`. This is because `readparam` …
=> patch for readparam()

src/map/skill.c
Fixed assert report when arrow shower(skill) was used on traps.
Fixes #1676
scope of bst variable is reduced to only UNT_VACUUM_EXTREME case, so other traps aren't affected if bst is NULL.
master
#1676 
None
=> Fixes error when skill is used on traps

src/map/script.c
For some reason the reference is lost right after the `conv_num` or `conv_str`. See https://github.com/HerculesWS/Hercules/issues/1761#issuecomment-306341881
**Issues addressed:** #1761
[code]: …
=> fix for #1761

doc/script_commands.txt, npc/dev/test.txt, src/map/script.c
New buildin: `getdatatype()`. Currently isstr() returns if the data evaluates to a string or not, but there is no way to know what type the original data (prior to get_val) was. This new buildin fills that gap.
<br>
For some reason when passing a constant it treats it as an integer:
```c
getdatatype(3); // DATATYPE_INT
getdatatype(Zeny); // …
```
=> new buildin: getdatatype()

src/map/script.c
Reading a player variable with `getvariableofpc()` works just fine without attached player, but it can't be passed to `set()` if there is no attached player (triggers `script:set: no player attached for player variable`). This PR fixes this. It also fixes the loss of reference, akin to #1765.
=> fix setting pc var on another pc

src/char/char.c, src/char/char.h, src/char/int_storage.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
Implements the storage saving algorithm for inventory, cart and guild storage tables.
Total queries to a table in any call would be no more than 4 per call, replacing the original algorithm that could make a lot more through single update queries per call. This significantly reduces the run time speed for saving/loading of item data from the game server.
[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull …
=> Optimisation of char_memitemdata_to_sql()

configure.ac, src/char/int_mail.c, src/map/clif.c, src/map/homunculus.c, src/map/itemdb.c, src/map/map.c, src/map/mob.c, src/map/npc.c, src/map/quest.c, src/map/script.c, src/map/status.c, src/map/status.h
Split status_change_start partially to smaller functions.
Fix possible buffer overflows in sprintf/snprintf.
Disable var-tracking warnings. They can happened in gcc-7
=> Refactor status_change_start and fix some issues in other code

src/map/status.h
SC_X conatants can be with any numbers.
Save near 200 places in arrays with size SC_MAX.
=> Save near 200 places in arrays with size SC_MAX.

.travis.yml
the inclusion of `ubuntu-toolchain-r-test` is for `libstdc++6`, which is required by `clang-5.0`
=> Add clang 4.0 and 5.0 builds to Travis

doc/script_commands.txt, src/map/script.c
New buildin: `getmapinfo()`
Allows to get misc info about a map
=> add buildin_getmapinfo

src/map/map.c, src/map/mob.c, src/map/unit.c
Invisible NPCs (including those with `FAKE_NPC` and `HIDDEN_WARP_CLASS` sprites) will be ignored for the purpose of cell stack counting.
This improves the Dancer Quest experience as well as other cases of hidden NPCs blocking off certain cells.
- Fixes #1135
This has been used in a production server for a while, as mentioned in the linked issue. No known problems as of now.
=> Ignore hidden units in the cell stack limit checks

src/map/skill.c
Reporting the index to the user when there is a mistake in the database is not helpful and could be confusing sometimes as the user might search for an id that does not exist.
=> Change skill_init_unit_layout to report skill id instead of index

src/map/battle.c
Cardfix is now always calculated in thousandths (it previously was in
hundredths in renewal mode only). The variable size is increased to int
(from short), to ensure that no overflows occur in case of large
multipliers.
This doesn't change the game mechanics (barring some minor truncation
issues that would previously occur due to the lack of precision in
renewal)
- This wasn't tested in depth in actual game environments, but the code changes are quite simple.
=> Remove separate cardfix definition for pre-re/re

src/map/atcommand.c, src/map/pc.c
This aims to fix the type conversion warnings described in #1867 and related to the changes from uint32 to uint64 of the Exp-related variables.
- master
- stable
- #1867 
=> Fix various warnings on Visual Studio 2017

src/map/script.c
This PR fixes an incorrect null check in `BUILDIN(logmes)` (inverted order of arguments in a `nullpo_retr` call).
The incorrect check would cause the `logmes()` script command to never log to database (but rather output a backtrace to the console).
Issue detected by coverity.
Note: From this point onward, we're going to manually run a coverity scan before each release is merged  to the stable branch, so that this kind of errors won't get noticed too late.
- master
- stable
- tagged release `v2017-10-22`
- Coverity CID 168499
We'll probably need a .1 release for this.
=> Fix an incorrect null check in BUILDIN(logmes)

npc/re/instances/octopus_cave.txt
=> Applied standardization to octopus_cave script

npc/re/instances/saras_memory.txt
=> Applied standardization to saras_memory script

doc/script_commands.txt, src/map/script.c
Currently, there's no way to remove the equip option
so, Modified setequipoption to allow type to be 0.
Type 0 will remove the equip option currently been set at slot x. …
=> setequipoption Modification

doc/script_commands.txt, src/map/clif.c, src/map/map.c, src/map/map.h, src/map/mob.c, src/map/mob.h, src/map/npc.c, src/map/packets.h, src/map/packets_keys.h
Add spawn flag miniboss_monster for spawn mini boss monsters. Old clients see mini bosses as boss/mvp.
Add support for 2017-10-25 clients.
=> Fix boss flag and add 2017-10-25 client packets

db/constants.conf, src/map/clif.c, src/map/npc.c, src/map/npc.h, src/map/script.c, src/map/script.h, src/map/status.c
Allow each npc use own view_data structure. Before they was shared for each npc class.
Allow set/get different view_data fields for npcs by setunitdata/getunitdata
For clients staring from 20170726, set npc type to CLUT_EVENT even if npc using player sprite.
=> Allow set equipment and other styles to npcs, use player sprites for npcs.

src/char/char.c, src/char/int_homun.c, src/char/int_quest.c, src/char/int_rodex.c, src/char/int_storage.c, src/common/sql.c, src/common/sql.h, src/login/account_sql.c, src/map/mapreg_sql.c, src/map/npc.c
Through the codebase there are several calls to the StmtBind functions with incorrect data types. This works on some platforms, and fails on others. An example of failure, caused by the different size of `long` on different platforms, is described in #1531.
This PR checks the calls to the StmtBind functions, changes the data type to the correct one for each, and adds an assertion inside the function, so that it won't fail silently if called with the wrong data type. Detection is currently solely based on the size (so there is still a chance of passing a signed data type while specifying an unsigned one, or pass a different type that has the same size), but it is enough to avoid issues such as the one from the linked issue.
Note: Existing third party code may experience failures at …
=> Correct and sanitize SQL bind types

src/map/battle.h, src/map/skill.c, src/map/skill.h
This suppresses an assertion in the skill DB accessors when called with `skill_id = 0` (such as during normal attacks). In such case, they'll now return an appropriate zero value, as it happened before 2b4bfa5d0.
- master
- stable (v2017.11.19)
- #1909 
N/A
This fixes a regression in v2017.11.19 that makes the map server console very chatty, potentially causing slowdows as the server prints multiple stack traces to the console for every attack. I suggest an uplift to the stable branch (and a v2017.11.19-1 release) once this is merged to master.
Review for uplifting to stable:
- Regression caused by: 2b4bfa5d0
- Impact if declined performance degradation as multiple stack traces are printed to the console, potentially several times each second …
=> Allow using the skill DB accessors on non-skill attacks (skill_id = 0)

src/map/skill.c
This restores the behavior that was broken in 2b4bfa5d0.
Fixes #1911
- master
- stable (v2017.11.19, v2017.11.19-1)
- #1911 
N/A
=> Fix handling of the special case of SplashRange < 0 meaning AREA_SIZE

src/char/int_rodex.c
This PR fixes a regression introduced in e5a63561bba9d09e5a88636f4982cdb2cf57a569
The order of the SQL statement operations was:
- Prepare
- Bind Parameters
- Bind columns
- (loop varying parameters)
- Execute
- (loop on rows)
- NextRow
instead of:
- Prepare
- Bind Parameters
- (loop varying parameters)
- Execute
- Bind columns
- (loop on rows)
- NextRow
- master
- stable (`v2017.11.19`)
- #1912 
N/A
=> Rodex stmt order

src/map/npc.c
Changes the NPC initialization code to use the correct view data (`INVISIBLE_CLASS`) instead of the novice class ID (0).
Related to #1893
- master
- stable (v2017.11.19)
- #1916
N/A
=> Fix invisible NPCs (such as FAKE_NPC) showing up as Novice

doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/packets_struct.h, src/map/script.c
This PR adds support for Packet ZC_PROGRESS_ACTOR (0x09D1) also introduce new buildin `progressbar_unit` to use progress bar with given gid.
master
note: after test the new packet doesn't work …
=> Add support for packet ZC_PROGRESS_ACTOR

db/pre-re/item_db.conf, db/re/item_db.conf, doc/item_db.txt, src/map/atcommand.c, src/map/clif.c, src/map/itemdb.c, src/map/itemdb.h, src/map/map.c, src/map/map.h, src/map/mob.c, src/map/mob.h, src/map/packets_struct.h, src/map/pc.c, src/map/pet.c, src/map/script.c, src/map/skill.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
This PR adds support for new drop packet with ability to set effect on item drop.
- master
- Official behavior uses the count of random options on drop as DropEffectMode for equipments.
[//]: # …
=>  Add support for new drop packet 0xadd for zero clients

tools/ci/travis.sh
The address sanitizer's leak detector isn't supported on i386, so it can't be forced to be enabled in the travis.sh script.
Related to #1949 
- master
N/A
N/A
=> Fix i386 CI builds

src/map/clif.c
Correction of the problem mentioned [IN THIS TOPIC.](http://herc.ws/board/topic/15409-bug-bg_message/)
Apparently there was a memory leak in the dynamic allocation. I compared previous versions of the emulator and found that the message size was received as a parameter, and that all entries per parameter were +1 the original size of the string.
I kept the length definition inside the function and incremented the variable. I have run the tests and the messages are now displayed normally.
Master
=> Overflow correction in visual function bg_message

src/map/clif.c
This extends the changes from #1890, targeting the clients that were excluded.
The unterminated string could cause client crashes or trailing garbage to be displayed when receiving a battlegrounds chat message, on various client versions.
Regardless of whether each client version requires that a string NUL terminator is present in the packet, the client is able to properly handle its presence. As a safety measure, this patch always appends a NUL terminator to the message, regardless of client version, to fix the issues described in the comments of PR #1890.
This has been double-checked on the following clients, to ensure that the NUL terminator doesn't cause display glitches:
- 2010-07-30aRagexe
- 2013-08-07aRagexe
- 2018-01-24bRagexeRE
- master
- stable
**Issues …
=> Fix unterminated strings in ZC_BATTLEFIELD_CHAT

src/map/skill.c
The `sd` pointer is checked before calling the clif function, as suggested in #1875.
- stable
- Fixes #1875
N/A
=> Prevent a null pointer failure when TK_JUMPKICK is used by a non-player

src/map/script.c, src/map/script.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
`script->sprintf()` is renamed to `script->sprintf_helper()`, so that it won't break when the C library defines a `sprintf()` macro.
- stable
- #2003 
N/A
=> Fix HPMHooking compilation when sprintf() is a macro

src/plugins/Makefile.in
There are 3 different ways to populate a variable in a Makefile (https://stackoverflow.com/a/28891382)
1.  You manipulate the file directly and set the variable before it gets used
2.  You pass it to make like so: make MYPLUGINS="test" all
3.  You set an env variable via export like so: export MYPLUGINS="test"
The problem is precedence. If you just …
=> Comment out "MYPLUGINS ="

src/char/pincode.c
Add missing pincode decryption.
Fix pincode packets field size to avoid send garbage to client.
Add missing seed in packet 0x8bb.
=> Fix pincodes after commit 2a05dbfc2f62c6bbac7983dcec120502914567f1.

src/map/mob.c
a followup to be90f6c69b6ac54ee83878f603cb9bf733d29d04
this is fixes an issue where max monster skills got limited to 5
now skill index is saved in it own variable to save it for later use and avoid confusion with others
Thanks to @trojal  for noticing this.
[//]: # (Syntax: - [ ] …
=> fix a wrong iterator used for mob skill db parsing

doc/script_commands.txt, src/map/script.c
I got asked numerous times to add support in `buildin_getunits` to search on the whole server, so here goes.
<br><br>
---
This PR makes the following buildins obsolete:
- `maprespawnguildid()`
- `playbgmall()` …
=> Allow global unit lookups from scripts

src/map/mob.c
Using mob_db2 and Inherit: true shouldn't override the base mob's range if it's not included.
all
Using mob_db2 mode "Inherit: true" should not set the overridden mob's range to 1.
[//]: # (Issue Tracker Number …
=> Don't overwrite mob.range with Inherit:true

doc/script_commands.txt, src/map/atcommand.c, src/map/battle.c, src/map/clif.c, src/map/pc.c, src/map/pc.h, src/map/script.c, src/map/script.h, src/map/status.c, src/map/unit.c
This is NOT what I had in mind when I did the previous pull request
but a lot was going on, on the forums, and somehow it turn out this way
... now this has become quite complex
1. I seriously think PCBLOCK_ is a better constant, but the community want it as BLOCK
because I fear maybe in the future there will be a real BLOCK constants coming from aegis ? I dunno
that's why it was PCBLOCK_ in the source, BLOCK as scripts
need Haru opinion on this
2. I don't really like to remove others work, like removing the name [Valaris] in the source code <.<
but members like the bit-wise method, so meh ...
so I removed those 2 sd->state.
3. I'm wondering the enum block_action should belongs to script.h or pc.h...
4. we have suggested so many types
here we go ...
BLOCK_MOVE => its a must
- keep the …
=> Add new *pcblock script command

src/map/skill.c
- master
- stable
This fixes a regression introduced in 2b4bfa5d08931530d5c9b30af10dd58c1af14883
When over the max skill level, the skill element shouldn't be attempted to be extrapolated from the skill element table (arithmetic can't really be applied to elements), yielding an invalid element.
N/A
=> Fix the skill element for levels above the MAX_SKILL_LEVEL

src/map/clif.c, src/map/clif.h
=> correct wrong respond message being used in stylist shop

src/common/HPM.h
Remove flag RTLD_DEEPBIND from dlopen.
This flag unneeded now, and it may prevent using asan in gcc-8.
=> Remove flag RTLD_DEEPBIND from dlopen.

src/common/console.c, src/common/core.c
When the `core` module was interfaced, the `shutdown_callback` was overlooked. Before this pull request, there exist two:
- `core->shutdown_callback`, which is assigned to, but never used
- `core->shutdown_callback`, which is never assigned to, but checked
This implies that the callback is defined but never called. The pull request fixes this, and removes the extra variable.
The `server:exit` console command is also updated to call the callback, so that proper cleanup is ensured.
- master (since 22bd368e5d4d8d61a7189d03f52c3afd90c0729e)
- stable
- Unlisted regression, since 22bd368e5d4d8d61a7189d03f52c3afd90c0729e
N/A
[code]: …
=> Fix the shutdown callback (2015 regression)

npc/dev/test.txt, src/map/script.c
https://github.com/HerculesWS/Hercules/issues/912
https://github.com/HerculesWS/Hercules/issues/1553
https://github.com/HerculesWS/Hercules/issues/1710
yes all were duplicates
https://github.com/HerculesWS/Hercules/issues/705
only the main one
Fix `if (1) ++.@i;` no longer throw error
which is parse as C_ADD_PRE and C_SUB_PRE ... I guess ?
actually ... rathena already fixed this ... this is something I just compare with theirs ...
```
prontera,150,182,5	script	kshdfkfs	1_F_MARIA,{
for ( .@i = 0; .@i < 5; ++.@i )
dispbottom .@i +"";
.@i = 0;
if (1) ++.@i;
dispbottom .@i +"";
if (1) .@i++;
dispbottom .@i +"";
//	dispbottom ++.@i +""; // still throw …
```
=> Fix pre-increment / pre-decrement operator error

src/map/status.c
The commit this PR reverts has broken SC_INCATKRATE and thus made skills like NPC_POWERUP for Monsters like Doppelganger or Atroce useless as it doesn't increase their ATK by 200% anymore as it is supposed to. (This has been tested by @Asheraf and looked at in decompiled Aegis Code by Rytech)
Additionally reverting this commit will also make Divest Weapon's ATK Reduction of 25% on Monsters work again as it is supposed to in Renewal. (It's already working in pre-Renewal)
**Issues addressed:** none(?)
none
```
if ( SKID == 349 )
{
CNPC::SetATKPercentInfo(v6, 0x15Du, 5000 * v4[4], 200);
v93 = 0;
v92 = 0;
v91 = 0;
v90 = 0;
v63 = 5000 * v4[4];
v89 = 1;
*&v88[8] = v63;
*&v88[4] = 98;
goto LABEL_182;
}
```
[cont]: …
=> Fix SC_INCATKRATE not working on monsters and Divest Weapon

.gitlab-ci.yml
This PR updates the GitLab CI configuration for compatibility with various changes in the target linux distributions that were causing build failures, and adds new versions of the compilers and systems to the tests.
- Each job now specifies the correct version of the SQL server image to use (to match the client and libraries shipped with the linux distribution it's running), in order to avoid test failures.
- The following clang jobs were changed:
- clang-4.0 moved from the primary to the secondary stage
- clang-5.0 added (secondary stage)
- clang-6.0 added (primary stage)
- clang-7 added (secondary stage)
- The following gcc jobs were changed:
- Removed gcc-4.6
- Removed gcc-4.7
- Moved gcc-4.8 from the primary to the secondary stage
- Added gcc-7 (secondary stage)
- Added gcc-8 …
=> GitLab-CI fixes

src/map/skill.c
https://github.com/HerculesWS/Hercules/issues/662
Follow rathena method ->
https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L739-L750
Note: I've already tested npc->isnear, no need to do that check
https://github.com/AnnieRuru/customs/blob/master/screenshots/screenHercules018.jpg
* Master
maybe should remove related checks in clif.c and buyingstore.c ?
rathena also left those blueprints behind
=> Fix novending cause player gets stuck

conf/map/battle/client.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/clif.h, src/map/map.h
This fixes an issue where a dead monster stay on the user map until he somehow reloads the map (e.g. through refresh/login out/warp). This happens when the user goes out of the area range of the monster in a couple miliseconds between monster dead and the actual packet that …
=> Fixed monsters not disappearing from some clients upon death

src/map/script.c, src/map/script.h
SCRIPT_MAX_ARRAYSIZE is UINT_MAX -1 ...
so let's try it out
```
prontera,161,185,5	script	test	1_F_MARIA,{
.@test[2147483648] = 1;
end;
}
```
oops ~ already got an error
```
[Warning]: script error in file 'npc/zzz.txt' line 2 column 9
parse_simpleexpr: overflow detected, capping value to INT_MAX
1: {
*    2:         .@test[2147483648] = 1;
~~~~~~~~~~~~~~~^
3:         end;
4: }
```
and no need to say that it cannot be a negative value
```
[Warning]: script:getelementofarray: index out of range (-1)
[Debug]: Data: variable name='.@test' index=0
[Debug]: Source (NPC): test9 at prontera (161,185)
```
this means ... the element in array can only hold …
=> Fix SCRIPT_MAX_ARRAYSIZE

src/map/skill.c, src/map/skill.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
skill_init_unit_layout_unknown is missing 'pos' parameter.
It is called with this:
```
default:
skill->init_unit_layout_unknown(i);
break;
```
If we see the loop, we need the `pos` variable to adjust the skill->dbs->unit_layout data:
```
case PF_FOGWALL: {
static const int dx[] = …
```
=> Added missing parameter to init_unit_layout_unknown

src/map/pc.c
A cooldown timer could expire before the associated character's data gets added to the ID/PC DB, causing skill_blockpc_end() to be unable to find and clear the cooldown data.
The normal order of operations is:
- (1) `pc_authok()` is executed upon login
- `skill_cooldown_load()` is called, and all the character's cooldows are restored, with the relative timers.
- `intif_request_registry()` is called, and continues asynchronously.
- (2a) `pc_reg_received()` is called asynchronously
- `map_addiddb()` is called, adding the `sd` to the `pc_db`.
- (2b) Cooldowns eventually expire, calling the timer function `skill_blockpc_end()`
- the `sd` is fetched through `map_id2sd()`, and its `sd->blockskill[]` data is cleared
But this leaves a race condition open, since (2a) and (2b) can be arbitrarily …
=> Fix an issue that causes skill cooldowns to get stuck indefinitely

npc/re/jobs/novice/academy.txt
this effect is officialy given thought the achievements system on first login.
remove the specialeffect as it's shown by the achievements system.
=> remove specialeffect on first login from the novice academy script

src/map/skill.c
The Venom Splasher skill is handled in a special way, causing its item requirement to be processed twice:
- The skill is cast and processed through `skill_castend_nodamage_id()`.
- Item requirements are processed the first time here, and the gemstone is consumed normally
- Damage is not applied right away, but `SC_SPLASHER` is started on the target.
- When the `SC_SPLASHER` status ends, `skill_castend_damage_id()` is called.
- Item requirements are processed again, consuming the gemstone a second time (note that this is not a strict requirement, and the gemstone is only consumed if present in the inventory at this time, since it's a collateral effect, and the double consumption wasn't taken into account when calculating the skill requirements! i.e. it's a bug, and not an intentional …
=> Fix Venom Splasher consuming its gemstome requirement twice

doc/script_commands.txt
having a fight over misunderstanding ....
blame https://github.com/HerculesWS/Hercules/pull/1124, I wasn't active at the time to see this change
Point all db\constant.conf to doc\constants.md in the doc\script_commands.txt
* Master
the C_ constants inside the db\constants.conf is hexadecimal
but when it convert over in doc\constants.md became base 10
there are still 2 lines in the documentation that I didn't change because of this
=> Point all db\constant.conf to doc\constants.md

src/map/script.c
consider the following:
```c
.@var = 1;
set(getd(".@var"), 2);
```
here everything works fine, because on the first line `.@var` is defined, so the script engine gives it type `C_NAME`, but if the first line is omitted,  `.@var` will not be defined and `getd` will give it type `C_NIL` (default type from `add_str`)
this creates issues when the script engine checks the type of the reference:
```c
set(getd(".@var"), 2);
getdatatype(getd(".@var"));
```
```
script:getdatatype: Unknown reference type!
Data: reference name='.@var' type=C_NAME
Please report this!!! - script->str_data.type=C_NIL
```
The solution is simple: always give type `C_NAME` when using `getd`.
`setd` is not affected by this bug.
=> fix getd not setting the type to C_NAME for new variables

src/map/skill.c
If MAGIC_REFLECTION_TYPE is set to 0 in src/config, a warning will appear in skill_attack. This suppresses it.
#1920
=> Supress warning in skill_attack when MAGIC_REFLECTION_TYPE is 0.

doc/script_commands.txt, src/map/script.c
I frequently find myself doing things like `debugmes(sprintf("foo=%d, bar=%d", .@foo, .@bar));` so I thought "why not simplify this?".
```c
debugmes("Hello %s!", "World"); // => Hello World!
```
=> bake sprintf into debugmes

npc/dev/test.txt, src/map/atcommand.c, src/map/battleground.c, src/map/channel.c, src/map/clif.c, src/map/duel.c, src/map/intif.c, src/map/mapreg_sql.c, src/map/mob.c, src/map/npc.c, src/map/pc.c, src/map/script.c, src/map/script.h, src/map/skill.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
A lot of places add variables to `script->str_data` without setting their type afterwards, so these variables end up with the type `C_NOP`, which was made evident by #2163. This PR adds `script->add_variable()` which works like `script->add_str()` but also sets the type to `C_NAME`
<br>
closes #2163 
closes #1801 
[cont]: …
=> always set the type to C_NAME when adding variables through script->add_str 

doc/script_commands.txt, src/map/map.h, src/map/quest.c, src/map/script.c
fix wrong check that was used to validate quest type in questinfo, thanks to the report on http://herc.ws/board/topic/16319-questinfo-setquestinfo
=> Fix wrong validation for quests in setquestinfo

src/map/pc.c
When a player does a zeny transaction, `achievement_validate_zeny` is called to see if the transaction triggered the completion of an achievement objective, but this function expects `z < 0 || z > 0`, so we should either remove the non-zero assert or only call it when we have a non-zero zeny transaction.
This PR fixes …
=> only update zeny achievements and logs for non-zero transactions

src/map/script.c
`building_getvariableofpc` __never__ actually worked when using it to set char-scope or account-scope variables
This PR fixes the following bugs:
- `set_reg_pc_ref_num` was incorrectly setting the type to `1`, which made `script_reg_destroy` behave unexpectedly
- `set_reg_pc_ref_num` was not setting the `vars_dirty` flag _at all_, which made map …
=> fix setting char/account variables of another player 

npc/dev/test.txt, src/map/script.c
Yay! yet another getd-related PR!
Fixes http://herc.ws/board/topic/16346--
=> allow buildin_getd to work with constants and params

src/map/script.c
This fixes the assertion error reported in #1388.
When sc_end is called it sets all sc `val*` fields to 0 before calling `status_change_end`. This works fine most of the time, but for `SC_BERSERK` the value on `val1` is used as an skill level to run an `sc_start` when berserk ends. So by setting `val1` to `0` it caused an assertion error.
On this pull …
=> Fixes an assertion error when sc_end is called for SC_BERSERK

src/map/packets_struct.h
this fixes the size of hp fields in PACKET_ZC_PROPERTY_HOMUN  for clients older than 20150513
this bug was introduced in eb54c762a3e9ca00fab5ff94a082861e1b70c0e0
reported at http://herc.ws/board/topic/16349-homunculus-bug-new-update-bug/
=> fix PACKET_ZC_PROPERTY_HOMUN size for old clients

conf/map/battle/skill.conf, db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c, src/map/skill.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
These commits fixes two issues related to traps.
- The first one allows traps that causes damage to be reflected by skills/cards that gives physical attack reflection (e.g. Reflect Shield and High Orc Card). This feature can be turned off in skill.conf to get old effect back.
As …
=> Fixes some issues with traps

doc/global_configuration.md
Turned doc/global_configuration.txt into Markdown format.
closes #2216 
=> global_configuration.md

doc/script_commands.txt, src/map/clif.c, src/map/script.c, src/map/script.h
* Deprecates `prompt()`
* It has the same behaviour as `select()`, except that it does not terminate the script on cancel
* no Hercules scripts make use of it
<br>
<sub>El Deprecador strikes again 🧛</sub>
=> deprecate buildin_prompt, bake it into buildin_select

src/map/map.c, src/map/map.h, src/map/script.c
Makes `getunits()` stop iterating when the max number of units is reached. Currently it just stops filling the array but keeps on iterating, so this PR fixes this.
=> break the loop in buildin_getunits when the max is reached

doc/script_commands.txt, npc/dev/test.txt, src/map/script.c
Adds a function to return a string representation of the given data (counterpart to `getd`)
```c
function foo {
if (getdatatype(getarg(0)) & DATATYPE_STR) {
debugmes("Warning! This function expects an integer. (got %s)", data_to_string(getarg(0)));
return;
}
// do some stuff
}
foo(.@bar$); // => Warning! This function expects an integer. (got .@bar$)
```
```c
data_to_string(getd(".@foo")) == ".@foo"
```
=> add data_to_string()

conf/messages.conf, src/map/channel.c
Old
`You're talking too fast!`
New
`You cannot send a message to this channel for another %d seconds.`
This is not a bug so it will be subjective as to whether it is necessary. I feel it would be a nice change for our custom channels system to include the delay before a player can …
=> Change channel delay message to time left instead of generic message.

src/map/map.c, src/map/map.h, src/map/npc.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
`map_zone_remove` is supposed to remove all mapflags from a map that were added by a zone, but instead just re-applies them (wtf?). this PR makes it actually disable them by passing the `off` argument
This should fix #2242 
[code]: …
=> fix map_zone_remove not actually removing flags

src/map/battle.c, src/map/unit.c
- The defense penalty for being attacked by many enemies at the same time can no longer make DEF go negative
- Fixed two potential overflow exploits
When being hit by a lot of monsters, your DEF will become negative and then eventually overflow, making you almost invincible.
On official servers the simultaneous attacker count is limited to 22. So at max, your def is reduced by ((22-2)*5%) = 100%. So it should neither be able to make your DEF negative nor cause an overflow.
Merge from https://github.com/rathena/rathena/commit/590f42cd15c58de78cff8be6053109852375bce1#diff-d96b6365b4bdad78139e676d6e7e3295R4589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1233)
=> Fixed defense overflow exploit

.gitlab-ci.yml
Debian removed the clang-4.0 package from unstable (as it won't be part of their next release), and our builds are failing.
This switches them to `debian:stretch`, where it's unlikely to get removed.
After this gets merged, the pipeline should be green again: https://gitlab.com/MishimaHaruna/Hercules/pipelines/36470066
=> Fix clang-4.0 builds in gitlab-ci

src/map/atcommand.c, src/map/channel.c, src/map/clif.c, src/map/guild.c, src/map/pc.c, src/map/pc.h, src/map/unit.c
This PR includes the fix for an issue that caused characters leaving a guild to stay into some of the allied guilds' `#ally` sub-channels, and be able to receive messages they shouldn't be entitled to.
Other related fixes/improvements are included. In detail:
- The `sd->channels` array has been changed into a VECTOR, to remove some awkward array compaction code related to the main issue.
- `#ally` is now left correctly when leaving the channel or guild. The code that loops through the channels to find the `#ally` ones is now safer against vector compaction.
- When joining a guild, if the `ally_channel_autojoin` setting is enabled, the channel is now joined immediately, without requiring a relog.
- A duplicate line was removed from the help message for `@channel`, likely caused by an …
=> Fix allychat leaveguild

src/map/mob.c, src/map/pc.c, src/map/pc.h
Current checks for empty entries assumed that if id and group is 0 that
it is empty, while in fact ITMCHAIN_ORE has group 0 as value,
for easier checks and more aesthetic code short group has been
replaced, id's are now always written into short id and bool
is_group decides if it's an item or a group.
**Issues addressed:** Gaia Sword not dropping anything at all.
=> Change short group to bool is_group in s_add_drop

db/item_db2.conf
Fixed typo in `db/item_db2.conf` to fix `Gungslinger` into `Gunslinger`. Double checked in `item_db.conf` files to see if they used Gunslinger, which they did. The inline documentation simply had a typo.
No Github issue was created to deal with this typo.
=> Fixed Gungslinger typo

src/map/pc.c
This fixes an issue when you cast abracadabra and a target skill is chosen and instead of using the skill you cancel and use a DELAYCONSUME item, as the abra_flag is not unset in this case, the item doesn't get consumed. My change clears abra_flag when you're using a delayed consume item.
master
Fixes …
=> Fixes delayed-consume items not being consumed after using Abracadabra

npc/custom/events/disguise.txt
https://rathena.org/board/topic/117852-i-got-error-when-applying-custom-commands/?do=findComment&comment=356295
Fix a bug in custom disguise event script that causes the event to run indefinitely
the .RoundCount only increase when having players answer correctly
if nobody playing this event, or players give up before .Rounds(10) rounds, it will continue run forever
add the exact same line from answer correctly, into wrong answer label
* Master
=> Fix a bug that causes disguise event to run indefinitely

src/map/itemdb.c, src/map/itemdb.h
Fix searching item by name with id > 65535.
Fix load item with id > 65535 on packet version without support for this kind of item ids.
=> Fix item db with item id bigger than 65535

src/char/char.c, src/login/login.c
Char server will show proper message is IP is not allowed to connect.
#737
[//]: # (**NOTE** Enable the …
=> Updated message on char-server

doc/script_commands.txt, src/map/script.c
Adds a script command to return the number of signed items a character has in their inventory.
Currently you have to do the following for this same functionality:
```
.@slot3 = getcharid(0) & 65535;
.@slot4 = getcharid(0) >> 16;
countitem2(<item ID>, 1, 0, 0, 254, 0, .@slot3, .@slot4)
```
This pull request changes that so you can simply do this:
```
countnameditem(<item ID>, {<character id/name>});
```
=> Added countnameditem script command.

npc/re/jobs/3-2/sura.txt
Fixes following Sura job change quest issues:
a) Player will not be able to success the test if fail it (die in test).
b) Waiting room will not get stuck anymore after the first attemp of the quest.
For more details, please read issue.
None
[//]: # (**NOTE** Enable the …
=> Fixes #1655 - Fix to Sura Job Change Quest get stuck after first attemp.

vcproj-15/char-server.vcxproj, vcproj-15/login-server.vcxproj, vcproj-15/map-server.vcxproj, vcproj-15/plugin-HPMHooking_char.vcxproj, vcproj-15/plugin-HPMHooking_login.vcxproj, vcproj-15/plugin-HPMHooking_map.vcxproj, vcproj-15/plugin-sample.vcxproj
http://herc.ws/board/topic/16521-how-to-setup-offline-server-for-personal-development-use/?do=findComment&comment=90471
Thanks to utofaery !!
Currently Visual Studio 2017 default their Windows Platform Version at 10.0.17763.0
but Hercules uses 10.0.15063.0 ...
means we have to download additional 1.43GB just to compile Hercules
So change the Windows Platform Version into 10.0.17763.0,
so we don't have to download unnecessary stuff ... 
* Master
not really sure if this break anything ?
let's see what Travis says ... ALL GREEN ... probably means ok to do so
=> Retarget 10.0.15063.0 into 10.0.17763.0 for Visual Studio 2017

doc/script_commands.txt, src/map/script.c
There are some constants return 0,
example `UDT_SEX` can have `SEX_FEMALE`, which is 0
`UDT_SIZE` -> `Size_Small` == 0
`UDT_LOOKDIR` -> `DIR_NORTH` == 0
etc etc
Change return value from 0 into -1 when `*getunitdata` return error 
* Master
more to come .....
https://github.com/HerculesWS/Hercules/compare/stable...AnnieRuru:34-setunitdata
by the way, this will break existing custom scripts that made check on 0 already ...
=> getunitdata should return -1 instead of 0. Phase 2

doc/script_commands.txt, src/map/script.c
http://herc.ws/board/topic/16588-1-how-to-make-it-not-list-clone-monster-or-slaveclone/#comment-90623
that script is flawed, obviously I could do `if ( .@mobid >= 4001 && .@mobid < 5000 )`
but if somehow gravity introduce more monsters ID, this range will subject to change,
which break my custom script
Add `MOB_CLONE_START` & `MOB_CLONE_END` to server defined constants
```c
prontera,155,185,5	script	sdkfjhsdkf	1_F_MARIA,{
.@mobgid = monster( "this", -1,-1, "--ja--", PORING, 1 );
.@mobid = uid2mobid(.@mobgid);
dispbottom "GID: "+ .@mobgid +" | mob ID: "+ .@mobid;
if ( .@mobid >= MOB_CLONE_START && .@mobid < MOB_CLONE_END )
dispbottom "this is a clone"; …
```
=> Add MOB_CLONE_START & MOB_CLONE_END to server defined constants

conf/map/battle/skill.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c
Adds a battleconf option for Magic Rod behavior, allowing a choice between official and old eAthena.
- Official: Every time you use the Magic Rod skill, the animation will occur.
- eAthena: The animation for Magic Rod will only occur when you absorb a spell.
**Affected Branches:** …
=> Adds configuration for Magic Rod behavior (official/eAthena).

npc/other/Global_Functions.txt
Added missing return on F_GetTradeRestriction. The function only created a variable but didn't return its value.
**Issues addressed:** none 
=> Added missing return on F_GetTradeRestriction

doc/script_commands.txt, src/map/script.c
Add missing **documentation** for disable battleground respawn
... erm ...
https://github.com/AnnieRuru/customs/blob/master/scripts/bg_pvp_point_queue.txt
just change 
```
.red = bg_create_team( "guild_vs3", 13,50 );
.blue = bg_create_team( "guild_vs3", 86,50 );
```
into
```
.red = bg_create_team( "-", 13,50 );
.blue = bg_create_team( "-", 86,50 );
```
* Master
well, pressing the [Return to last Save Point] from the client side will forcefully leave the battleground team though
=> Add missing documentation for disable battleground respawn

doc/script_commands.txt, npc/re/jobs/3-1/archbishop.txt, npc/re/jobs/3-1/ranger.txt, npc/re/quests/eden/eden_tutorial.txt, src/map/script.c, src/map/script.h
while fixing https://github.com/HerculesWS/Hercules/pull/2395 and I need a script command to return mercenary GID,
so I copy existing code from rAthena
Add constants and MERCINFO_GID to *getmercinfo script command
```c
prontera,155,185,5	script	kjdshfksdf	1_F_MARIA,{
getitem Bow_Mercenary_Scroll1, 1;
for ( .@i = 0; .@i <= 8; ++.@i )
mes getmercinfo(.@i) +"";
mes rid2name(getmercinfo(MERCINFO_GID));
mes getunitname(getmercinfo(MERCINFO_GID)); // return nullpo
close;
}
```
* Master
none
=> Add constants and MERCINFO_GID to *getmercinfo script command

doc/script_commands.txt, npc/quests/quests_rachel.txt, src/map/script.c
Actually I was writing this for my custom scripts,
but when I do a search `OnTouchNPC` in npc folder, suddenly found this is actually official
rAthena already having `*getattachedrid` like for ages already
https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L922-L925
Add `*mobattached` and `*killmonstergid` script command
```c
prontera,155,185,5	script	qwer	1_F_MARIA,{
getmapxy .@map$, .@x, .@y, UNITTYPE_NPC;
.@mobid = monster( .@map$, .@x, .@y, "--ja--", PORING, 1, strnpcinfo(0)+"::Onaaa" );
unitwalk .@mobid, 160,185;
end;
Onaaa:
npctalk "run";
end;
}
prontera,160,185,5	script	asdf	1_F_MARIA,0,0,{
end;
OnTouchNPC:
//	unitkill …
```
=> * Add *mobattached and *killmonstergid script command

src/common/socket.c, src/common/socket.h, src/map/atcommand.c, src/map/atcommand.h, src/map/map.h, src/map/mapdefines.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc, src/plugins/HPMHooking/HPMHooking_login.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_login.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_login.Hooks.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Add function connect_client into socket interface.
Move stylist_data into clif interface.
=> Different interfaces fixes

doc/script_commands.txt, src/map/script.c
thanks to @Emistry showing me this link https://github.com/HerculesWS/Hercules/pull/2246
we actually don't support `<char_id>` field, unlike rathena counterpart
Fix *needed_status_point not support `<char_id>` field
* Master
=> Fix *needed_status_point not support <char_id>

conf/map/battle/feature.conf, src/map/achievement.c, src/map/battle.c, src/map/battle.h
Configuration to enable/disable achievement system database loading and validation.
[//]: # (**NOTE** …
=> Added configuration to enable/disable achievement system

doc/script_commands.txt, src/map/script.c
getinventorylist now creates extra variable named @inventorylist_idx, which returns items corresponding
inventory index.
It would be useful for #2394 
Example:
```c
getinventorylist();
for (.@i = 0; .@i < @inventorylist_count; .@i++) {
dispbottom(sprintf("Index %d: %s (%d)", @inventorylist_idx[.@i], getitemname(@inventorylist_id[.@i]), @inventorylist_id[.@i]), C_AQUA);
if (@inventorylist_id[.@i] == Beret && @inventorylist_expire == 0) {
delitemidx(@inventorylist_idx[.@i]);
dispbottom(sprintf("Deleted Index %d: %s (%d)", @inventorylist_idx[.@i], getitemname(@inventorylist_id[.@i]), @inventorylist_id[.@i]), C_RED);
break;
}
}
```
None
[code]: …
=> Expanded getinventorylist:

doc/script_commands.txt, src/map/script.c
we have `*getcalendartime` script command, but why our `*gettimestr` isn't update for it?
Add optional parameter for `*gettimestr`
```
prontera,155,185,5	script	sdkfjhsdkf	1_F_MARIA,{
mes(gettimestr("%Y-%m/%d %H:%M:%S", 21));
mes(gettimestr("%Y-%m/%d %H:%M:%S", 21, getcalendartime(0,0)));
close;
}
```
which is stated in the documentation
* Master
none
in fact this is mostly a copy-paste from rathena repo
=> Add optional parameter for *gettimestr

src/plugins/sample.c
http://herc.ws/board/topic/16597-help-absorb-damage-taken-bonus/?do=findComment&comment=90812
change `rand()` into `rnd()`
* Master
none
=> Fix rand() not support on certain compiler

src/map/script.c
http://herc.ws/board/topic/16641-q-about-setunitdata/
Fix UDT_LEVEL when show_mob_info level display is on
no.1 there is a battle_config.mobs_level_up,
when player is killed by a monster, it run clif->charnameack
https://github.com/HerculesWS/Hercules/blob/a0820df92f781bfc721bb7797f6f840880f1de08/src/map/pc.c#L8129-L8143
no.2
```c
prontera,155,185,5	script	askdaksd	1_F_MARIA,{
.@mobgid = monster( "this", -1,-1, "--ja--", PORING, 1 );
setunitdata .@mobgid, UDT_MAXHP, 1000000;
setunitdata .@mobgid, UDT_HP, 1000000;
setunitdata .@mobgid, UDT_LEVEL, 99;
end;
}
```
* Master
yes I know there are a lot more,
but I am thinking its very much better to split …
=> Fix UDT_LEVEL when show_mob_info level display is on

db/constants.conf, doc/script_commands.txt, src/map/script.c, src/map/script.h
Copy Paste from rAthena !!!
although they don't support pet evolution yet, though ...
1. Deprecate *petstat script command 
2. Add constants to *getpetinfo, and add some new fields
```c
prontera,155,185,5	script	kjdshfs	1_F_MARIA,{
for ( .@i = 0; .@i <= 12; ++.@i )
mes (.@i)+". "+getpetinfo(.@i)+"";
close;
}
```
* Master
I have to go back on the forum .... 
there is still `*gethominfo` and `*geteleminfo` need to do ...
=> Deprecate *petstat and add CONSTANTS to *getpetinfo

doc/script_commands.txt, src/map/script.c
we use to do like this
```
prontera,155,185,5	script	kjsdkf	1_F_MARIA,{
mes "input Item ID";
next;
if ( input( .@itemid, 501, 32768 ) ) { // item ID was smallint(6)
//	if ( input( .@itemid, 501, MAX_ITEM_ID ) ) {
mes "invalid range";
close;
}
if ( getitemname( .@itemid ) == "null" ) {
mes "invalid Item ID";
close;
}
mes "OK";
close;
}
```
add MAX_ITEM_ID as the limit of Item ID is no longer 32768
https://github.com/HerculesWS/Hercules/blob/stable/src/map/itemdb.h#L41
* Master
=> Add new server define constant MAX_ITEM_ID

src/map/pc.c
1. https://github.com/HerculesWS/Hercules/issues/2383#issuecomment-467607801
2. if the player on 3rd job, having alternate bodystyle, and `@jobchange` into novice for example,will crash the client.
This is extremely annoying when we testing stuffs
1. Apply temporary fix so Job_Super_Novice_E no longer crash client 
2. Fix atcommand @jobchange when the player changing from 3rd job into non-3rd job, crashing client
* Master
=> Fix @bodystyle crash client

doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/script.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
as requested by Kuroe, add optional parameter to allow `*showscript` to only shown to the player
* Add optional parameter for `*showscript` to send target to SELF only
* also remove the useless script_pushint
* Master
this is copy paste from rathena
=> Add optional parameter for *showscript to send target to SELF only

src/char/int_rodex.c, src/char/int_rodex.h, src/char/inter.c, src/char/mapif.c, src/char/mapif.h, src/common/HPMDataCheck.h, src/common/mmo.h, src/map/intif.c, src/map/intif.h, src/map/rodex.c, src/map/rodex.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_char.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Improve rodex attach handling.
Clean mail list on refresh rodex.
=> Different rodex fixes

src/map/pet.c
Automatically migrate pets to the new system that keeps hatched eggs in the inventory
- The pet evolution update caused all already hatched eggs to get lost cause the previous system would actually remove the egg unlike the new one, this code will ensure the return of it.
=> Automatically migrate pets to the new system that keeps hatched eggs in the inventory

src/common/sysinfo.c
properly print the names for visual studio 2017 and 19
=> Update MSVC version naming in console info

src/map/chat.c
- doesn't allow chatroom creation/switch if the coordinated cell are set with `cell_nochat`.
- chatroom will be auto deleted.
<details>
```
-	script	sample	-1,{
OnInit:
.@map$ = "prontera";
.@max_x = getmapinfo(MAPINFO_SIZE_X, .@map$);
.@max_y = getmapinfo(MAPINFO_SIZE_Y, .@map$);
setcell(.@map$, 0, 0, .@max_x, .@max_y, cell_nochat, true);
.@range = 10;
.@center_x = 155;
.@center_y = 181;
setcell(.@map$, (.@center_x - .@range), (.@center_y - .@range), (.@center_x + .@range), (.@center_y + .@range), cell_nochat, false);
end;
}
```
player 1 - create a normal chatroom at normal cells that dont have `cell_nochat`.
player 2 - move to `cell_nochat` area, and join the chatroom
player 1 - leave the chatroom
** at this point, chatroom shall be auto deleted since the new owner are located in the …
=> Disable chatroom creation if cell_chknochat

doc/script_commands.txt, npc/custom/etc/quest_warper.txt, npc/custom/quests/quest_shop.txt, npc/custom/quests/thq/THQS_TTShop.txt, npc/dev/test.txt, npc/woe-fe/agit_main.txt, src/map/script.c
- deprecated `*debugmes` script command.
- added `*consolemes` script command which display the console message based on `type`.
- allow map-server console to auto logging into text file depend on type of message in the setting.
Currently, the `st->rid` and `st->oid` values, i keep it in both `ShowWarning()` and `ShowError()`. Should we still remain it in `ShowDebug()`? any advice?
`debugmes` has hardcoded string `script debug ....` seem unnecessary most of the time, and tend to ignored it. 
Sometime we use `debugmes` to display info, which aren't really "debugging" just purely for information display, so its more appropriate to use other like `ShowInfo`, `ShowStatus` etc.
**Preview :**
<details>
```
List of available <type> are:
CONSOLEMES_DEBUG   = 0 …
```
=> Added *consolemes script command

doc/script_commands.txt, src/map/script.c
- return an array `@inventorylist_favorite`
- indicate whether an item in the inventory are located inside favorite tab or not.
Allow npc script to detect if an item are located in favorite tab. 
Sample:
```
prontera,155,181,5	script	sample	4_F_KAFRA1,{
getinventorylist;
mes "Favourite Items";
for (.@i = 0; .@i < @inventorylist_count; .@i++) {
if (@inventorylist_favorite[.@i]) 
mes "~ "+ getitemname(@inventorylist_id[.@i]);
}
close;
}
```
=> Expand *getinventorylist() script command - favorite field

doc/script_commands.txt, npc/other/Global_Functions.txt, npc/re/instances/OldGlastHeim.txt
too many members doesn't even know this exist
simply because it is not documented
Add `F_MesItemInfo` function to show item name with description link
* Master
```
prontera,155,180,0	script	Test Instance	1_F_MARIA,{
mes("You can <URL>Google<INFO>http://www.google.com/</INFO></URL> anything");
.@id = Apple;
mes(F_MesColor(C_BLUE) +"This message is now in BLUE");
mes F_MesColor(C_BLACK);
mesf("%sThis message is now in BLUE.", F_MesColor(C_BLUE));
mes F_MesColor(C_BLACK);
mes F_MesItemInfo(.@id);
mesf "Testing %s", F_MesItemInfo(.@id);
mes("Bring me an <ITEM>Apple<INFO>512</INFO></ITEM>.");
mes("Bring me an "+ F_MesItemInfo(Apple) +".");
mesf("Bring me …
```
=> Add F_MesItemInfo function to show item name with description link

src/map/clif.c, src/map/clif.h
1. Fixed a packet size underflow in storage list sending which started with client supporting int32 for item id and added static assert to detect this problem if ever happened again.
2. Fixed direct calls to clif_send in clif.c
3. Add missing nullpo and assert to clif_send
None
=> Storage item list packet size fix and minor clif.c fixes

src/plugins/HPMHooking.h, src/plugins/sample.c
- Starting from 5db7c799055c6ae9c4463f6cf4c88a35597d5d31 the ability to hook to private interfaces was removed, this commit restores this ability by introducing two new macros for specifically.
* addHookPrePriv to add a pre-hook for private interface member
* addHookPostPriv to add a post-hook for private interface member
=> Restore the ability for HPM Hooks to hook to private interfaces

src/map/unit.c
- allow NPC to warp to non-walkable cell. Just like `*movenpc()` did.
- NPC are allow to stay on non-walkable target cell, hence this command shouldn't show the warning and should warp the NPC to that cell instead.
Try to use `unitwarp()` function to warp a npc to a non-walkable target cell.
Reference https://github.com/rathena/rathena/issues/2270
=> Update unitwarp script command.

tools/itemdbconverter.pl
In perl v5.22, using a literal { in a regular expression was deprecated, and will emit a warning if it isn't escaped: \{. In v5.26, this won't just warn, it'll cause a syntax error.
Before:
After:
=> Fixed issue with Perl v5.2x

tools/HPMHookGen/HPMHookGen.pl
This adds the interface variables of type pointer to array to the ignored variables when generating the hooks.
Fixes the following errors:
```
Error: unable to parse 'char(* atcommand_interface::atcmd_output)[(255+1)]'
Error: unable to parse 'char(* atcommand_interface::atcmd_player_name)[(23+1)]'
```
=> Fix errors in the HPM Hooks Generator

src/common/HPMDataCheck.h, src/map/clif.c, src/map/instance.c, src/map/map.c, src/map/map.h, src/map/npc.c, src/map/npc.h, src/map/quest.c, src/map/quest.h, src/map/script.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
https://github.com/HerculesWS/Hercules/issues/2431
fix memory leak in setquestinfo
=> Move questinfo data from map to npc_data

conf/map/script.conf, src/map/clif.c, src/map/pc.h, src/map/script.c
```
prontera,155,185,5	script	kljhdsfskjh	1_F_MARIA,{
.@b = input(.@a, -1000,100);
dispbottom .@a +" "+ .@b;
end;
}
```
input -100, always gets 0
blame clif.c, now allow negative input
* Master
rathena also allow it, why hercules don't ?
=> Allow *input script command to support negative input

doc/script_commands.txt, src/map/script.c
- Added parameter `MAPINFO_NPC_COUNT` to return the total number of NPC exists in the map.
- Added new server define `MAX_NPC_PER_MAP`
Allow NPC script to validate max npc count in the map before adding new NPC through script command. Useful for https://github.com/HerculesWS/Hercules/pull/2473
=> Update *getmapinfo script command.

doc/script_commands.txt, src/map/script.c
- add `cap_value(value, min, max)` script command.
- its kinda useful in the `src` if you noticed, so I am sure it could come in handy to add for NPC script usage.
- avoid the ugly nested `min()` and `max()` combo if needed.
=> Add *cap_value script command

doc/script_commands.txt, src/map/script.c
- `*mesclear()` script command will clear the NPC dialog text and continue
the script without player interaction. example: `next();`.
Original Info can be found at here https://github.com/rathena/rathena/pull/2840
The reason I prefer `mesclear()` over `clear()`, it sound more appropriate since we are clearing `mes(...)` and not anything else.
=> Add *mesclear script command.

db/pre-re/mob_skill_db.conf
Updated `NPC_SUMMONSLAVE` skill delay for `Byorgue` monster.
- prevent potential farming exploit.
- Gravity seem to increased it long time ago before renewal.
It's wrong on Herc and correct on rAthena. Gravity increased it a long time ago (before renewal) to prevent farming exploit.
_Originally posted by @Playtester in https://github.com/rathena/rathena/issues/3992#issuecomment-469418860_
=> Update Byorgue summon slave delay

src/map/script.c
Check for unit data `(nd->ud != NULL)` before adjust the NPC speed. 
Throw warnings if `nd->ud == NULL`.
script command `npcspeed`, `npcwalkto`, `npcstop`, `unitwalk`, `unitwarp`, `unitstop` are not applicable for floating npc (without coordinate/location).
Fix map-crash due to unit_data `NULL`.
Sample NPC Script:
```
-	script	dummynpc	-1,{
OnInit:
debugmes "set speed to 100";
npcspeed 100;
debugmes "set speed done";
end;
}
```
Result:
After fixed:  throw warnings but didnt crash map-server
Related PR https://github.com/HerculesWS/Hercules/pull/1733
=> Fix map-crash when floating npc use *npcspeed script command

doc/script_commands.txt, npc/custom/events/mushroom_event.txt, npc/re/instances/ghost_palace.txt, src/map/script.c
I don't want to memorize another special capital letter case
"All" and "all" is already enough for us -> #784
nobody was bother with the "All" and "all" because eathena/rathena is not case-sensitive script engine
during hercules early days, script engine became case-sensitive, and [Emistry has asked to change it](https://github.com/HerculesWS/Hercules/issues/784)
Haru said this isn't an issue -> because it mentioned in script-commands
and we are being force to memorize `*killmonster` -> "All", `*mobcount` -> "all"
```
prontera,155,185,5	script	kjhdsfks	1_F_MARIA,{
monster "this",-1,-1, "--ja--", PORING, 1;
sleep 1000;
if ( mobcount( …
```
=> Standardize to "all" in script commands

README.md, mariadb.bat, tools/install_mariadb.bat, tools/setup_mariadb.ps1
This is a follow-up to http://herc.ws/board/topic/16318-cant-connect-to-mysql-server-on-127001/#comment-89417
* Adds a [scoop](https://scoop.sh)-based automatic installer for MariaDB
=> Simplify windows installation

src/map/status.h
Fix some stats calculation issues by reverting basic stats type from uint32 to uint16.
=> Fix some stats calculation issues by reverting basic stats type from uint32 to uint16

doc/script_commands.txt, src/map/script.c
Adds new script command delitemidx().
`delitem(<index>{, <account id>})`
An important command which will allow scripters to delete an item at a specific index. Why is this important? Now we can check an item for cards, if it's a rental and other useful information `getinventorylist()` provides us.
Currently if you have a quest which has an item requirement which can also be a Rental on your server, it will just eat up that rental item with no regard. This can be problematic if that rental item is a recolour, effectively allowing you to make the item with a rental.
**Hypothetical example:**
- Recolouring Beret (Black, Blue, Red, Yellow) quest requires Beret and 10,000z.
- You can rent a Beret for 1z.
- If you give it a rental Beret, you can still complete the quest. …
=> Adds BUILDIN(delitemidx), which deletes an item at the given index.

npc/jobs/1-1e/ninja.txt, npc/quests/quests_nameless.txt, npc/quests/quests_prontera.txt, npc/re/jobs/2e/kagerou_oboro.txt, npc/re/merchants/renters.txt
- update npc name translation. 
`Cougar -> Kuuga Gai`, `Gaebolg -> Geoborg`, `Family -> Clan`, `Magic Gear -> Mado Gear`
- updated mado gear renter npc to enable player to obtain `mado gear box` and `cooling devices`.
https://github.com/rathena/rathena/issues/3854
=> Update NPC scripts

doc/script_commands.txt, npc/other/inventory_expansion.txt, src/map/script.c
http://herc.ws/board/topic/16526-some-upcoming-hercules-features/?do=findComment&comment=90516
All script commands should be in small letters
* Master
I don't want to memorize another special capital letter case
"All" and "all" is already enough for us -> https://github.com/HerculesWS/Hercules/issues/784
--> standardize into "all" for script commands -> https://github.com/HerculesWS/Hercules/pull/2380
~so if Haru say again this isn't an issue, feel free to close this PR~
for standardization, script commands has to be small letters
=> standardize script commands to small letters

doc/script_commands.txt, src/map/script.c
Adds BUILDIN(getguildonline) which returns the amount of players online in a guild.
Optional param for type, which will exclude vendor characters from the count.
Returns -1 if guild not found.
I know `getguildmember()` can perform this functionality, but this is quicker and …
=> Adds buildin_getguildonline.

src/map/itemdb.c, src/map/mob.c
This PR makes option_drop_groups.conf and item_options.conf be loaded when running map-server in minimal mode. This fixes errors when map-server loads mob db in minimal mode and it can't find option_drop_groups to be assigned to mob drops.
Indirectly reported on #2484 (The actual issue was different, but the error was written in it)
=> Adds Option DB and Option Drop Groups DB to be loaded on minimal mode

src/map/npc.c
https://github.com/HerculesWS/Hercules/issues/2347
Suppress ShowWarning for adjust_skill_damage mapflag when `@reloadscript`
1.
when "@reloadscript", it actually runs npc->parse_mapflag once with all value `""` or `"off"`
https://github.com/HerculesWS/Hercules/blob/95bf87b3b3c256f1d84e53a49ee43aab98912932/src/map/map.c#L4695-L4713
2.
some mapflag has checked with `"off"` status already
https://github.com/HerculesWS/Hercules/blob/95bf87b3b3c256f1d84e53a49ee43aab98912932/src/map/npc.c#L4362-L4363
3.
```
{
name: "MyZone"
mapflags: (
"adjust_skill_damage	MG_FIREBOLT	900",
"nosave",
)
}
```
```
prontera	mapflag	zone	MyZone
```
* Master
none
=> Suppress ShowWarning for certain mapflags when @reloadscript

doc/script_commands.txt, src/map/itemdb.h, src/map/pc.c, src/map/script.c
- `setfavoriteitemidx()` set an item as favorite item or not
- if an item is set to favorite item, it will be moved into favorite
tab, else move out from favorite tab.
- only non-equipped item can adjust the favorite item state.
- `autofavoriteitem()` will auto set an item as favorite state or not whenever obtained. (affect globally)
-----------------------------
Sample Script: `autofavoriteitem(<itemID>, <flag>)`
<details>
```
prontera,155,181,4	script	Sample	4_F_KAFRA1,{
.@item_id = 909;
mes getitemname(.@item_id);
// mes "auto favorite: "+getiteminfo2(.@item_id, 21);
.@flag = select("disable favorite", "enable favorite") - 1;
autofavoriteitem(.@item_id, .@flag);
close;
}
```
</details>
Sample Script: `setfavoriteitemidx(<idx>, <flag>)`
<details>
```
prontera,155,181,4	script	Sample …
```
=> Add *setfavoriteitemidx & *autofavoriteitem script commands - alter item favorite state

npc/re/merchants/enchan_mora.txt
Based on data from [iRO on Mora Village](https://irowiki.org/wiki/Mora_Village), there were missing equipment for guillotine cross, ranger, and rune knight.
I simply added the item IDs for the items, and the menu paths to get the said items.
Not sure if I should replace the item IDs with their Aegis names, or if that is not necessary.
=> Added missing equipment

doc/atcommands.txt, src/map/atcommand.c
- `@reloadnpc <path>` - unloads all NPCs in a file and reload it again.
- Be aware that mapflags and monster spawned directly are not removed.
none
=> Add new atcommand *reloadnpc

doc/atcommands.txt, doc/script_commands.txt, src/map/atcommand.c, src/map/script.c
This PR implements script commands to identify items, although lots of scripts nowadays kind of fake that behavior by using a combination of `delitem2` + `getitem2`, this leads to wrong behavior when items have more information, like random options (as shown in this [forum post][post], where doing this leads to losing dropped options). New script commands:
- `identify(<Item ID>)`: Identifies the first unidentified item with ID = "Item ID"
- `identifyidx(<idx>)`: Identifies item at inventory index `idx`.
I took the chance to also add `@identifyall` atcommand, because it is quite boring to identify item per item when you are testing lots of drops.
[code]: …
=> Add identify/identifyidx script commands and identifyall atcommand

npc/instances/SealedShrine.txt
There is a situation where you can invoke more than one sealed Baphomet.
To reproduce:
1. Go to the second floor of catacombs and before you summon, as party leader, stop on the dialog "The bottom of the Main Altar trembles furiously.".
2. Change party leader to another member, so, he can talk with the seal in the middle too. He stops on the same dialog "The bottom of the Main Altar trembles furiously."
3. Keep doing it until all party is on the same dialog. All of them proceeds the dialog to invoke the sealed Baphomet, and we'll have a lot of sealed Baphomet unsealed.
So, this PR is to don't allow players to abuse the instance using this way.
I've just added instance status check and if the character is truly the party leader.
Related to instances #1582, not …
=> Fix sealed bapho problem

src/map/atcommand.c
- using `@refresh`/`@refreshall` during NPC conversation will caused player stucked due to unable to close the NPC dialog that no longer visible.
- `@refresh` shall display failure message if interact with NPC.
- `@refreshall` shall skip the player if the target player are interact with NPC.
=> Disable refresh atcommand when talk with NPC.

src/char/char.c
- failsafe function to not execute the query
- avoid EXP sharing bug
> This adds a failsafe function to not execute the query during the family check AND avoid an exp sharing bug when the child_id is == 0 AND the returning value from the SQL is 0 also, this makes the check on `char_child` function returns a FALSE 1(positive)
https://github.com/rathena/rathena/pull/3350
=> Fix family check and EXP bug

conf/map/battle/homunc.conf, src/map/battle.c, src/map/battle.h, src/map/homunculus.c, src/map/pc.c
- homunculus will obtain a portion or full EXP (`1~100%`) from master.  (`0% = disable`)
- `@showexp` shall display homunculus EXP gain.
homunculus gain `10%` bonus exp from master. (default = `10%`)
```
Battle configuration has been reloaded.
Experience Gained Base:56 (0.00%) Job:60 (0.06%)
Homunculus Experience Gained Base:5 (0.23%)
```
<details>
homunculus gain `50%` bonus exp from master.
```
Battle configuration has been reloaded.
Experience Gained Base:56 (0.00%) Job:60 (0.06%)
Homunculus Experience Gained Base:28 (1.29%)
```
homunculus gain `100%` bonus exp from master.
```
Gained exp is now shown.
Experience Gained Base:56 (0.00%) Job:60 (0.06%)
Homunculus Experience Gained Base:56 (2.57%)
```
</details>
https://github.com/HerculesWS/Hercules/issues/2313 …
=> Update Homunculus obtain EXP from master

db/re/item_combo_db.txt, doc/script_commands.txt, src/map/script.c
- allow to specify more than one equipment slots.
- return the total of refine of specified equipment slots.
Shorten this
```
.@r = getequiprefinerycnt(EQI_SHADOW_ARMOR)+getequiprefinerycnt(EQI_SHADOW_WEAPON)+getequiprefinerycnt(EQI_SHADOW_SHIELD)+getequiprefinerycnt(EQI_SHADOW_SHOES)+getequiprefinerycnt(EQI_SHADOW_ACC_R)+getequiprefinerycnt(EQI_SHADOW_ACC_L);
```
into this
```
.@r = getequiprefinerycnt(EQI_SHADOW_ARMOR, EQI_SHADOW_WEAPON, EQI_SHADOW_SHIELD, EQI_SHADOW_SHOES, EQI_SHADOW_ACC_R, EQI_SHADOW_ACC_L);
```
**Test Result:** 
<details>
**Test Script:** 
```
prontera,155,181,5	script	Sample NPC	4_F_KAFRA1,{
for (.@i = EQI_HEAD_TOP; .@i <= EQI_SHADOW_ACC_L; .@i++) {
.@old_refine += getequiprefinerycnt(.@i);
}
.@new_refine = getequiprefinerycnt(
EQI_HEAD_TOP
,EQI_ARMOR
,EQI_HAND_L …
```
=> Update *getequiprefinerycnt script command

src/map/homunculus.c, src/map/itemdb.c, src/map/mob.c, src/map/pet.c, src/map/quest.c, src/map/refine.c
- show file path
Current result: (display only file name without extension and path)
```
[Status]: Done reading '416' entries in 'item_combo_db'.
```
Updated result: (display file path + name)
```
[Status]: Done reading '416' entries in 'db/re/item_combo_db'.
```
<details>
```
[Status]: Done reading '64' command aliases in 'conf/atcommand.conf'.
[Status]: Done reading '4' channels in 'conf/channels.conf'.
[Status]: Done reading '10606' entries in 'db/re/item_db.conf'.
[Status]: Done reading '263' entries in 'db/re/item_db2.conf'.
[Status]: Done reading '186' entries in 'db/item_options.conf'.
[Status]: Done reading '416' entries in 'db/re/item_combo_db'.
[Status]: Done reading '57' entries in 'db/re/item_group.conf'.
[Status]: Done reading '4' entries in 'db/re/item_chain.conf'.
[Status]: …
```
=> Fix missing file path in console.

src/map/pc.c, src/map/pc.h
- fix auto bonus doesn't trigger for costume/shadow gears
- fix `pos` always obtained `0` due to `short` data type.
fixes #1355
fixes #1190
fixes #2451 
=> Fix equipment auto bonus trigger

db/pre-re/item_chain.conf, db/re/item_chain.conf, src/map/clif.c, src/map/itemdb.c, src/map/itemdb.h, src/map/pc.c, src/map/pc.h
- allow player to revive themselves if their inventory consists of any type of siegfried tokens.
- support the following siegfried tokens:
https://github.com/HerculesWS/Hercules/blob/7063a6539316da89f33ccd8909aa7f718764c4f3/db/re/item_chain.conf#L62-L66
Currently, if players has any of these siegfried token, only `7621` can be used to revive the players, the rest of the siegfried tokens will only enable the client to show the resurrection button but doesn't revive the players if clicked.
**Known Issue:**
I have no idea in what order of these tokens are consumed in official server. If the players have multiple different tokens, which shall be consumed first?
If anyone know, kindly let me know, so that I could update it.
[cont]: …
=> Update Siegfried Tokens support.

src/map/mob.c, src/map/npc.c, src/map/pc.h
This PR includes two fixes related to the MVP tombstones:
- When a player is talking to the tombstone while it disappears, it no longer gets stuck and requires to relog.
- When a player clicks (multiple times) a tombstone to read its message, it no longer prints the message several times inside the same NPC dialog.
=> Tombstone fixes

doc/script_commands.txt
You can't put a switch() statement inside a while statement.
I fixed 2 examples that had this mistake, which was probably caused by copy-pasting.
None
=> Fix two examples in scripting documentation

npc/battleground/kvm/kvm_item_pay.txt, npc/custom/battleground/bg_kvm01.txt, npc/custom/battleground/bg_kvm02.txt, npc/custom/battleground/bg_kvm03.txt
* The npc traded the wrong item to point
Credit: https://github.com/rathena/rathena/commit/cc11869a93571f0e0355917ba113d1bd98d42d48
fixes #2404 
=> Corrected KVM Logistic Officer item ID

db/item_db2.conf, db/pre-re/item_db.conf, db/re/item_db.conf, doc/script_commands.txt, src/map/itemdb.c, src/map/itemdb.h, src/map/pc.c, src/map/script.c, src/map/script.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Implemented new script fields in item db executes when item is rented and when item rent expires
Implemented a new script command getfont() gets the current player font id
Fixed hardcoded checks for rental items in source
#140
=> Dehardcode Rental Expire/Renting item checks

src/map/atcommand.c, src/map/clif.c, src/map/itemdb.c, src/map/itemdb.h, src/map/script.c, src/plugins/constdb2doc.c
Rewrote item name checks in both functions to be more readable
Changed flag to be enum item_name_search_flag and made itemdb_searchname_array_sub respect flag given to parent function
Corrected item count returned by parent function when dbmap search is performed
Fixed a memory violation caused by the old code when dbmap search is performed
Fixed dbmap searching having static array size which did not adhire to the size passed to the function
=> Fixed several issues in itemdb_search_name function

db/pre-re/item_db.conf, db/pre-re/item_lapineddukddak.conf, db/re/item_db.conf, db/re/item_lapineddukddak.conf, doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/itemdb.c, src/map/itemdb.h, src/map/packets.h, src/map/packets_struct.h, src/map/pc.h, src/map/script.c, src/map/script.h
=>  Implementation of LapineDdukDdak System

npc/other/arena/arena_party.txt
Adding an end; so you can't infinitely reset the timer.
This bug allowed you to have no time limit on the party mode of
Izlude Arena, making it quite easy for you to farm OCAs.
Thanks to Vector from oRO Staff for finding this!
**Issues addressed:** none
=> Fix a missing end in Slipslowrun NPC that allowed to reset the timer

src/map/script.c
npcshopdelitem now moves data within structure size.
Wrong limit was used, which is fixed in this PR.
NA
=> Fixed heap-buffer-overflow on npcshopdelitem

npc/quests/quests_umbala.txt
Moved delitem before getitem.
So even if somebody manages to do some kind of manipulation to items, delitem would stop the script execution …
=> Umbala Script Update:

conf/messages.conf, src/map/atcommand.c
- The correct amount of dropped items should be displayed.
- Included skipped amount.
Merge from https://github.com/rathena/rathena/commit/beb6b579f21158411c885b19ff955ba4c49d5e71
=> Update dropall atcommand

src/map/clif.c
Result: Negative values return as 256 - (value). 
For instance, Undead Lv1 has -25 against Poison and Shadow, so it shows up as 231: 
Expected Result: 
Negative values instead return as 0 on kRO: 
How to Reproduce: 
Use Sense against a monster whose property will absorb any element.
Official Information: Only took Gravity 17 years to fix! 
http://ro.gnjoy.com/news/notice/View.asp?seq=7126
Merged from https://github.com/rathena/rathena/commit/19835b638bce924b9e8b9d5a71b05d23e68bb26d
=> Update Sense Skill - show 0 for negative values

src/map/clif.c
This PR removes some checks that were preventing players to close their vending (from merchant skill). The issue was basically because we had a check that prevented a player in any trading state (including vending) to close it.
I also removed the check for a dead player, because the client itself allows that, and the same problem would happen.
Fixes #2554 
=> Fixes close merchant vending

src/map/skill.c, src/map/unit.c
Fix Chaotic Blessings never healing the enemy.
Fix Homunculus skill failure message not displaying required items. (eg: Healing Hands from Lif)
Fix Homunculus skill requirements being put on owner as well.
Last change meant for example that currently if the owner of an homunculus doesn't have enough SP, the homunculus won't be able to use skills requiring SP, even though the Homunculus might have enough SP. This is now fixed with this change.
Note:
All of these fixes have been tested and are proven to work.
=> Homunculus skill fixes

conf/map/battle/monster.conf, src/map/battle.c, src/map/battle.h, src/map/mob.c, src/map/mob.h
Make slave monsters chase after what their master is chasing, instead of merely following him until he attacks or uses a skill on a target.
That way if the master is immobilized during chasing,
the slaves will still continue to chase and attack once getting in range.
Before this fix Hunters could Ankle Snare Orc Hero for example,
making his slaves completely unresponsive for the trap duration.
**Change has been tested and found to be working well**
=> Make slave mobs react to master's chase target

src/char/int_party.c, src/map/guild.c, src/map/party.c
1. Clear the party ID from the saved character data, when leaving or getting kicked (causing database inconsistencies)
2. Clear the cached guild pointer when the guild ID is cleared, upon error (dangling pointer).
3. Clear the (clientside) party name from all the party members when a party is disabanded (just visual).
**Issues addressed:** Point 2 is a possible cause of the crash described in #1266
=> Clean up cached party/guild data when leaving/disbanding

src/common/console.c, src/map/map.c
- Fixed the `gm:info` console command to correctly set the mapindex for the dummy console SD
- Fixed a crash in the console message parser, when processing a string consisting of only spaces (i.e. press Space, then Return on the console)
- Fixed console command argument processing: when multiple spaces are passed at the beginning of a command, now they're correctly stripped before calling the command handler
=> Console command fixes

src/map/mob.c
Fix aggressive ranged mobs not attacking from above a cliff,
such as WoE Archer Guardians from above towers or Orc Archers in gef_fild14.
**Issues addressed:** none?
=> Fix aggressive ranged mobs not attacking from above a cliff

src/map/mob.c
Follow up to 6608308
Fix some nullpo errors caused by wrongly assuming,
that masters in mob->ai_sub_hard_slavemob() are only of type BL_MOB.
This also fixes slaves with masters of type != BL_MOB not locking to master's target anymore.
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/2576
=> Fix unintended nullpo errors

src/map/mob.c, src/map/mob.h, src/map/pc.c
This fixes two issues with the TF_STEAL skill:
- The HP bar of the target is now sent to all the party members in case of successful cast, as soon as the mob is added to the damage log. Previously, party members needed to leave and re-enter the view area. This only affects packetvers between 20120404 and 20131223.
- The Steal skill now explicitly ignores cards, to match the official behavior. This was affected by a regression when the item DB was converted to the libconfig format in ed72a947a6c97804c1eef5b80bfa49d99f7d7586, as the cards are no longer in a fixed position in the drops array.
=> Fix some issues in the Steal skill

src/map/clif.c
This fixes @fakename display. Currently it only displays if you have a disguise active.
Proposed changed = only shows when you don't have disguise active. Although, my personal opinion is there should be no check for disguise.
This one needs some clarification. Previously we did not check for `sd->disguise` in relation to fake names. Was there a report that said @fakename has some issues?
#2539 
=> Fix issues with @fakename.

src/map/unit.c
Thanks to Marida from oRO Staff doing a heavy part in fixing and debugging this!
Clear ud->target_to when appropriate.
Changes have been tested thoroughly.
The following bugs are fixed by this:
- Hunters with auto-attack on that are clicking to move away from mob, constantly walking back to attack the mob and back to where they wanted to move.
- When the target of a monster died mid-chase, it would constantly walk towards the corpse back and forth (If no new targets are in sight)
=> Fix ud->target_to not being cleared appropriately

src/map/script.c
This PR adds a handling to read `\r` in `.po` files as a control character (i.e. carriage return) instead of two separate, normal, characters (i.e. `\` and `r`). Currently, HULD is not able to translate messages like:
```
mes("Oh...!\r"
"Welcome to Alberta,\r"
"young adventurer!");
```
Even though this is the recomended way (See: #1292 ). That happens because when parsing the NPC file, the script engine takes `\r` as a control character, but when loading a `.po` file, it considers it as 2 separate characters, not matching with the original string, thus not translating them.
This PR fixes this.
None
=> Makes HULD .po files read \r as a control character

src/map/map.c
the database loading message shows after the npcs are loaded which is inconsistent with the other databases
=> Make the stylist db load before the npcs

db/sc_config.conf
Removing these status using `sc_end(SC_ALL)` results in some weird behavior as it gets stuck reapplying and removing the effect due to some data not being cleaned properly (we should probably look into that at some point).
=> Passive Guild Skill status should not reset with SC_ALL

src/map/skill.c
Guild skills will be ignored in `skill_cooldown_save()` if `guild_skill_relog_delay` is set to 1.
If guild skills are not ignored when `guild_skill_relog_delay` is set to 1, the map server will throw error messages (no such timer) if the guild master relogs while cooldown.
Also applied Hercules coding style to `skill_cooldown_save()`.
**Issues addressed:** #2591 
=> Modified skill_cooldown_save() to ignore guild skills if guild_skill_relog_delay is set to 1.

src/map/skill.c
The current behavior of Tarot Card breaking card is to break any equipment except weapon, however after referring to Aegis both for EP12.1 and EP14.3 the code clearly showed it only break Left Arm (Shield), Armor and Helm.
as an extra for future reference chemical protection is not bypassed by this breaking behavior.
The aeigs code snippets is as the following
``` C
{
CPCBattle::ReflectDamage(v2, other, 1000);
if ( !v5 )
{
v7 = GetServerRandom(0, 20000) % 3;
if ( !v7 )
{
CPC::OnDamagedArmor((CPC *)other);
return 4;
}
if ( v7 == 1 )
{
CPC::OnDamageEquipment((CPC *)other, 256);
return 4;
}
CPC::OnDamageEquipment((CPC *)other, 32);
}
result = 4;
}
```
All inner functions has been checked for any other behaviors and confirmed as well.
[cont]: …
=> Fix Tarot Card breaking equipment behavior

src/map/battle.c
Make racial crit bonuses affected by the katar crit bonus.
(Such as Goblin Steamrider Card for example)
First: We're assuming that this part of katar crit bonus didn't change in Renewal.
Test was done on 11.3 Ep Aegis Server.
Assassin had 42 LUK.
Equipment was Specialty Jur[4] with 4x Goblin Steamrider Cards and 2x Critical Rings.
Crit Shield of Sleeper is 5.6
Crit without Goblin Steamrider Cards is 50 - 5.6 = 44.4
IF katar crit bonus doesn't affect goblin steamrider cards then that would be 72,4 Crit against Sleepers.
Since it does affect them it's 100,4 as the test showed.
=> Fix racial crit bonuses not being affected by katar crit bonus

doc/constants.md, doc/script_commands.txt, src/map/clif.c, src/map/pc.h, src/map/script.c, src/map/script.h, src/map/unit.c
PCBLOCK_NPC for setblock script command to prevent players interacting with NPCs (e.g. During some npctalk dialogue). This is required for some official behaviours.
=> Adding PCBLOCK_NPC to setpcblock script command

doc/script_commands.txt, src/map/script.c
* Added a flag to ignore mapflag restrictions in `warpparty()` and `warpguild()` script commands.
* Applied code style to `warpparty()` and `warpguild()` script commands.
* Updated doc/script_command.txt.
**Issues addressed:** #1861
=> Add flag to ignore mapflag restrictions in warpparty() and warpguild() script commands.

src/map/clif.c
The condition `if( sd->mail.inbox.msg[i].zeny + sd->status.zeny > MAX_ZENY ) {` would overflow and turn into negative value, resulting in the code never executing even if it exceed MAX_ZENY
[//]: # (Issue …
=> Fixed a condition in RoDEX attachment

src/common/HPMi.h, src/plugins/HPMHooking.h
With some compilers if build complex plugins, can exists redefine issue for HPM interfaces.
In this pr added special check for avoid this issue.
=> Fix redefine HPM structs in multy file plugins

src/common/mmo.h, src/map/skill.c, src/map/skill.h
Previously, skill_get_index was having hardcoded ID's to convert skillID to indexes, which was not too easy to edit in case of adding new skills (custom/official).
Changed the way skill_get_index works, so that it includes array of Skill Ranges (Start, End) and calculates index based on that.
None
=> Changed logic of skill_get_index

src/char/int_party.c, src/char/int_party.h, src/common/mmo.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_char.Hooks.inc
Fixed Visual Studio C4018 compiler warning, caused by `inter_party_check_exp_share()` function in src\char\int_party.c.
> ..\src\char\int_party.c(320,56): warning C4018: "<=": signed/unsigned mismatch
[C4018 reference](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=vs-2019)
**Issues addressed:** #1434
=> Fix C4018 compiler warning in src\char\int_party.c.

conf/map/battle/misc.conf, conf/messages.conf, src/map/atcommand.c, src/map/duel.c, src/map/duel.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
- Able to set cooldown in `seconds` format.
- New `duel_time_interval` value will be applied to any existing cooldown
if new value is reloaded in-game using `@reloadbattleconf`.
- Display the cooldown tick before can create new duel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/herculesws/hercules/1495)
=> Update Duel System Cooldown

src/map/skill.c
These are small fixes to how Asura Strike skill behaves. This fixes:
* After using Asura Strike the caster doesn't end up looking to its target anymore
* When Asura Strike fails, it doesn't shows "Skill failed" twice in chat
* When Asura Strike fails, the caster will now walk 3 cells from where he originally was (instead of 2)
**Affected Branches:** …
=> Minor fixes to Asura Strike

db/pre-re/item_db.conf, db/re/item_db.conf
**For the 4 elemental resistance potions:**
They used `SC_ARMORPROPERTY` to apply multiple elemental resistance modifications at the same time.
But in `status_change_end_()`, `clif->sc_end()` is called for `SC_ARMORPROPERTY`, which has no effect because this status change was never send to the client.
Actually one or more of these status changes needs to be ended client side, depending on the consumed potion: `SC_RESIST_PROPERTY_WATER`, `SC_RESIST_PROPERTY_GROUND`, `SC_RESIST_PROPERTY_FIRE`, `SC_RESIST_PROPERTY_WIND`
Because of this issue, the status changes should be started separately, to make sure, the correct status change will be ended client side.
**For Undead Elemental Scroll:**
It used ` SC_ARMOR_RESIST` which won't show a status change icon client side.
Since its Aegis script …
=> Updated items which used SC_ARMORPROPERTY or SC_ARMOR_RESIST.

src/map/skill.c
`PR_STRECOVERY` should cure status effects only if the target's defence/armor element is not `ELE_UNDEAD`.
**Issues addressed:** #2558
=> Updated PR_STRECOVERY to only cure status effects if defence element is not Undead.

src/map/mob.c
Mobs, spawned by `mob_clone_spawn()`, were invulnerable, because their `dmg_taken_rate` was never set and thus became `0`. Now, `dmg_taken_rate` will be set to `100`, to remove that invulnerability.
**Issues addressed:** #2607
=> Added an initial dmg_taken_rate value to clone spawns.

src/map/map.c, src/map/script.c
There were 2 cases causing map-server to crash.
1) When getunits was called with invalid mapname, mapname2mapid would be called, and it will return -1, which would then call map_forcountinmap, which does not perform any checks. So, a error message is added to getunits, to know exactly where something went wrong.
2) Source can use map_forcountinmap without validating the inputs, or even passing wrong value of mapid, which would have caused the map-server crash.
=> Crash fixes

db/pre-re/mob_db.conf, db/re/mob_db.conf, doc/mob_db.txt, src/map/mob.c
When using the `ViewData` block in mob_db.conf, `HairStyleId` currently defaults to 0.
This causes client errors, because there is no head sprite with ID 0.
So `HairStyleId` should default to 1 instead.
=> Make mob DB field ViewData->HairStyleId defaulting to 1 instead of 0.

src/map/battle.c
Rifle type weapons had a broken call to battle_calc_base_damage2 since
they were passing the flag value 18 and flag&16 != 0 as stated by the
documentation shall only be the case when no gun or bow is equipped. 
*This bug likely didn't affect Renewal as it seems like flag&16 isn't used there.*
This bug existed since 2006 and got introduced by the commit e24d467f1ae47475e3441d7453f549e22f46f541 .
**Issues addressed:** *None?*
=> Fix W_RIFLE damage calculation being too low than intended

src/map/pc.c
In `pc_readparam()` function, `case SP_VARCASTRATE` is defined twice.
On is defined in `#ifndef RENEWAL_CAST` and the other one in `#ifdef RENEWAL_CAST`.
I merged both and made the assignment of `val` depending on `RENEWAL_CAST`.
**Issues addressed:** #1311
=> Merge pre-RE/RE case SP_VARCASTRATE in pc_readparam() function

src/map/homunculus.c
Vanilmirth for example would get incompletely vaporized when using
HVAN_EXPLOSION, if the owner died due to it, and then it would be killed at the end of it.
This produced a bug which made it not ressurectable but callable, once it
was called it would be dead though and you'd be unable to control it,
requiring you to ressurect it after that.
This bug got introduced by 0eca88efc69becc591428fbb6b9fddd9237afd3d .
Make it impossible to vaporize homunculi when bl.prev == NULL, such as when delblock is used in HVAN_EXPLOSION.
=> Fix Homunculi being partially vaporized.

src/map/npc.c
If `SECURE_NPCTIMEOUT` is defined, `script_detach_state()` is called as soon as the idle time reaches the defined value.
Then `sd->npc_id` will be set to `st->bk_npcid` (which is 0 at this point) in `script_detach_state()`.
When now `npc_scriptcont()` is called, it will throw an unnecessary debug message: 
> [Debug]: npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not ....
To prevent this, `npc_scriptcont()` should check `sd->npc_idle_timer` for not being `INVALID_TIMER` if `SECURE_NPCTIMEOUT` is defined.
**Issues addressed:** #2073
=> Change NPC ID validation in npc_scriptcont()

src/map/status.c
skill_get_index call was missing from Skill2SCTable causing overwriting of SC Status, resulting in some skill giving out wrong status.
#2636 
=> Missing get_index call in Skill2SCTable.

src/map/pc.c
Request Prelude
Since the used return values in `pc_setpos()` function may cause errors, or at least are misleading, I added two new return values:
* 3 - No character data. (Parameter sd is a NULL pointer.)
* 4 - Character is jailed.
@MishimaHaruna
This may be merged manually after #2600, since that PR applies code style to that function.
**Issues addressed:** #2632
=> Add new return values to pc_setpos() function

src/map/mapdefines.h
Increase `MAX_MOB_LIST_PER_MAP` to 115 in pre-RE mode, to enable all defined monster spawns.
**Issues addressed:** #1915 
=> Increase MAX_MOB_LIST_PER_MAP to 115 in pre-RE mode

src/map/clif.c, src/map/pc.c
* Prevent the execution of an item's (un)equip script, regardless of the `unequip_restricted_equipment` configuration, if the item is restricted in that zone.
* Force the execution of an item's unequip script when entering a zone where the item is restricted, even if the item won't be unequipped.
This replaces #2207, since there seems to be no more progress.
@MishimaHaruna
This may be merged manually after #2600, since that PR applies code style to `clif_parse_LoadEndAck()`.
**Issues addressed:** #2180
=> Fix (un)equip script execution for map zone restrcited items

db/pre-re/item_db.conf, db/pre-re/skill_db.conf, db/re/item_db.conf, db/re/skill_db.conf, doc/script_commands.txt, src/map/pc.c, src/map/pc.h, src/map/script.c, src/map/script.h, src/map/skill.c, src/map/unit.c
* To be able to use the `itemskill_*` flags in `skill_check_condition_castend()`, the conditions to call `pc_itemskill_clear()` in `unit_skilluse_id()` and `unit_skilluse_pos()` need to be extended. Otherwise those flags are unset prior to the execution of `skill_check_condition_castend()`, which leeds to unintended behaviour of some items.
* Changed behaviour if `itemskill()` script command to ignore conditions by default. Now you have to explicitly set the `ISF_CHECKCONDITIONS` flag if conditions should be checked/consumed.
(Requested by @Asheraf to keep custom items unaffected.)
* Added missing requirements to `CASH_INCAGI` (15 HPCost) and `RK_CRUSHSTRIKE` (equipped weapon) skills.
**Issues addressed:** #2646 …
=> Fix itemskill() script command

src/map/unit.c
This bugged aggressive monsters for example, as they wouldn't move to
you and just do a move animation on 1 cell, stationary.
Introduced by fe378985d5267bee1f73049c826ad4f1e9c2b9c4
Return 1 instead of 0 on success, as unit->walktobl still uses "non-standard" error-codes.
=> Fix wrong return-value on success by unit->walktobl

src/map/unit.c
Monsters get stuck when trying to loot, which is caused by a misplaced condition in `unit_walktobl()`.
**Issues addressed:** https://herc.ws/board/topic/18014-bug-looter-monster
=> Fix mobs get stuck when trying to loot

src/map/npc.c
The `StringBuf` in `npc_expanded_barter_fromsql()` function isn't freed if the statement preparation/execution fails and thus generates a memory leak.
=> Fix memory leak in npc_expanded_barter_fromsql() function

src/map/script.c
Using `ITEMINFO_NAME` or `ITEMINFO_AEGISNAME` in `getiteminfo()` script command causes an overflowing pointer error when the respective stack element gets freed.
> [Error]: Memory manager: args of aFree 0x052B7B62 is overflowed pointer ...\src\map\script.c line 3774
Therefore `script_pushstrcopy()` should be used instead of `script_pushstr()` to push the item's name to the script stack.
=> Fix overflowing pointer in getiteminfo() script command

db/re/skill_db.conf, src/map/skill.c
Liete mentioned that skills don't check if the equipped ammunition type is appropriate for equipped weapon and thus can be cast with wrong ammunition type equipped.
> Liete
> Hello.
> Can anyone help me out with this issue:
> I have set certain skill - Spread Shot to be working with grenade launchers, but there is a problem it uses both bullets and grenades be it shotgun or launcher equipped.
The actual problem is that you can equip bullets or grenades regardless of the equipped weapon type. This issue has already been reported: #2579
Since this needs some more information before completely get fixed this PR is a quick workaround for the time being.
**Issues addressed:** #2661, Partially #2579
Closes #2661 
[code]: …
=> Make skills check if equipped ammunition type is appropriate for equipped weapon

doc/script_commands.txt, src/map/script.c
Someone asked me to add a parameter for the account ID to `setpcblock()` to restore the usability of `pcblockmove()`. In my opinion this is a reasonable enhancement and should be added to Hercules.
Additionally I added that parameter to `checkpcblock()`, too.
=> Extend *pcblock script commands

src/map/unit.c
A misplaced return condition in `unit_walk_toxy_timer()` (introduced in https://github.com/HerculesWS/Hercules/pull/2546/commits/fe378985d5267bee1f73049c826ad4f1e9c2b9c4) caused assertion errors in `timer_do_delete()` because `ud->walktimer` could not be unset.
**Issues addressed:** https://herc.ws/board/topic/18073-error-timer_do_delete-error
=> Fix misplaced return condition in unit_walk_toxy_timer()

src/map/unit.c
The assert-returning for unknown bl-types in `unit_bl2ud()` (introduced in https://github.com/HerculesWS/Hercules/pull/2546/commits/88cca0d976bdd6fbe07c8646939fc1512e97cf72) caused "failed assertion" message spamming in the map-server console when a `BL_SKILL` unit was attacked. (For example Ice Wall.)
=> Add case for BL_SKILL to unit_bl2ud() to not trigger assert-returning

src/char/int_pet.c
A missing pet ID assignment in `inter_pet_fromsql()` (introduced in https://github.com/HerculesWS/Hercules/pull/2600/commits/70edf6f2d4f042b470cb1f62e408c076f5c8d76b) caused a bug where pets could no be hatched correctly.
**Issues addressed:** #2683 
=> Add missing pet ID assignment to inter_pet_fromsql()

src/map/mob.c, src/map/skill.c, src/map/status.c
Prevent `SC_AUTOTRADE`, `SC_KSPROTECTED` and `SC_NO_SWITCH_EQUIP` from falsely being recognized as unknown status changes.
**Issues addressed:** #2684 
=> Fix status changes falsely being recognized as unknown

src/map/atcommand.c, src/map/pc.c, src/map/pc.h
* When a character unhides while being disguised and if no other character is within view range, the disguised character stays invisible until he moves or another character enters view range.
To fix this `clif_spawn_unit()` should be called when unhiding while being disguised to update the disguised character's client properly.
* When a character unhides by using `@option 0`, clients are not being updated properly in `pc_setoption()` and thus causing crashes.
**Issues addressed:** #2104, #1556
=> Fix unhiding while being disguised and when using @option 0

src/map/pet.c
The `pet_ai_hard` timer is executed before the pet's block and the pet master's block are added to the map, which causes nullpo errors in `pet_ai_sub_hard()`.
This wasn't noticed before #2600 was merged, because 0 was returned silently instead of using `nullpo_ret()`.
To fix this, the conditions for calling `pet_ai_sub_hard()` in `pet_ai_sub_foreachclient()` should be adjusted to check `sd->bl.prev` and `sd->pd->bl.prev` for `NULL`.
**Issues addressed:** https://herc.ws/board/topic/18186-error-petc-1018/
=> Fix conditions for calling pet_ai_sub_hard()

db/mob_skill_db2.conf, db/pre-re/mob_skill_db.conf, db/re/mob_skill_db.conf, src/common/cbasetypes.h, src/map/mob.c, src/map/mob.h, src/map/script.c, src/map/unit.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
- Add missing constants to enable global skills assignment.
- Harmonize behaviour of cast condition constants.
- Add some error messages.
- Add proper defaulting and capping when reading monster skill DBs.
- Apply code style.
- Add Windows support for predefined identifier \_\_func__. (Not related to the topic but useful.)
=> Extend and clean up monster skill DB code

src/map/pc.h, src/map/status.c
Change `SC_NOCHAT` validation to compare against `battle_config.manner_system` instead of `val1` to get affected by battle config changes.
**Issues addressed:** #227
=> Make SC_NOCHAT gets affected by battle config changes

src/map/atcommand.c, src/map/script.c
```
prontera,155,185,5	script	jskdhfjshfd	1_F_MARIA,{
setpcblock PCBLOCK_COMMANDS, true;
atcommand "@kick "+ strcharinfo(0);
end;
}
```
cause map-server.exe to show warning
```
[Warning] buildin_atcommand: failed to execute command '@kick AnnieRuru'
```
`*atcommand` should bypass the restriction
I also failed to noticed the `player_invoked` variable in the function
> * @param player_invoked true if the command was invoked by a player, false if invoked by the server (bypassing any restrictions)
* Master
none, this is minor edit
=> Fix *atcommand cannot be use when PCBLOCK_COMMANDS is true

src/char/char.c, src/map/pc.c, src/map/skill.c, src/map/skill.h
This PR adds some robustness to the code related to `skill_get_index()` and fixes some wrong assumptions and dangerous index arithmetic index in the Bard/Dancer Soul Link temporarily granted skills, reported in #2670 .
Warnings have been added, to help detecting incorrectly defined ranges for `skill_get_index()`.
Finally, the use of the `SKILL_FLAG_REPLACED_LV_0` value (and in general, values from `enum e_skill_flag`) have been sanitized, since suspicion on them was raised in a private report about attempts to save negative skill indexes to the database (which may or may not have been a secondary effect of the Bard/Dancer granted skills issue).
**Issues addressed:** #2670 
[code]: …
=> Fix skill idx

conf/map/script.conf, doc/script_commands.txt, npc/dev/test.txt, src/map/map.h, src/map/npc.c, src/map/npc.h, src/map/script.c, src/map/script.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
This is my proposal to fix #2137:
* local functions can no longer be called as events, even if their label begins with `On`
* local functions may be explicitly exported by defining them as `public function ...`.
this allows other scripts to call them as if they were part of their own script
* exported local functions can be called from any script by doing `"npc name"::MyFunction();`
<br>
```c++
-	script	npc1	FAKE_NPC,{
private function NonExported {
return "[1] non-exported";
}
public function Exported {
return "[1] exported";
}
// local call:
debugmes(NonExported()); // => [1] non-exported
debugmes(Exported()); // => [1] exported
// call in another NPC:
debugmes("npc2"::NonExported()); // ERROR: not exported
debugmes("npc2"::Exported()); // => [2] exported
}
-	script	npc2	FAKE_NPC,{ …
```
=> allow local NPC functions to be public or private

doc/mob_skill_db.md, src/map/mob.c, src/map/mob.h, src/map/script.c
Add MSC_MAGICATTACKED cast condition for monster skills to trigger when a monster has received magic damage.
**Issues addressed:** #2578
=> Add MSC_MAGICATTACKED cast condition for monster skills

conf/map/battle/items.conf, conf/map/battle/skill.conf, doc/script_commands.txt, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/pc.c, src/map/pc.h, src/map/script.c, src/map/skill.h
To enable consuming usable items and using skills while interacting with a NPC I did the following:
* Extend `item_enabled_npc` battle flag with option for usable items.
* Add `skill_enabled_npc` battle flag.
**Issues addressed:** #862
=> Add/extend battle flags to enable item/skill usage while interacting with NPC

src/map/unit.c
Since it's kind of expectable to occasionally be unable to retrieve the target's `block_list` by its ID in `unit_steptimer()`, the `NULL` pointer report should be replaced with returning an error code.
**Issues addressed:** #2707
=> Replace NULL pointer report with returning error code in unit_steptimer()

src/map/skill.c
Pass `0` for `type` instead of `-1` when calling `skill_addtimerskill()` for `GN_CRAZYWEED`.
This value is later used to retrieve the skill's unit ID at the given index so `0` is the correct value for `GN_CRAZYWEED` since it has only one unit ID.
**Issues addressed:** #1151
=> Fix left shift of negative value for GN_CRAZYWEED_ATK

src/map/pet.c
A pet's rename flag isn't applied to its egg item's `card[3]` field and thus not being saved to the database.
This leads to a missing "Beloved" prefix for eggs of renamed pets.
**Issues addressed:** #2743
=> Save a pet's rename flag when returning it to its egg

src/map/clif.c
The `mineffect` flag in `clif_maptypeproperty2()` should not be affected by `sd->state.lesseffect` or any other state and should be applied to guild castles even if WoE is not running.
**Issues addressed:** #803
=> Make mineffect flag not being affected by sd->state.lesseffect in clif_maptypeproperty2()

db/pre-re/item_db.conf, db/re/item_db.conf, doc/script_commands.txt, src/map/clif.c, src/map/clif.h, src/map/script.c
Aegis uses the `LoudSpeaker` command for broadcasting megaphone messages.
Namely this is a special use case of packet `0x009a` where the message's first 34 bytes are reserved for string `micc` (4B) which identifies the broadcast as megaphone shout, the character's name (24B) and the text color (6B).
Side note: I had to use "loudhailer" because "megaphone" is already taken by item 7040. :disappointed_relieved:
**Issues addressed:** The "double clickable name" part of #2751
=> Add loudhailer() script command

src/map/clif.c, src/map/pc.c
`pc_setpos()` checks for invalid equipment and unequips it if required. On login, the character's status data was not yet calculated at this point and thus the server could crash due to missing memory allocation.
To fix this, the equipment check should be moved to `clif_parse_LoadEndAck()` because it's called after the character's status data was initially calculated in `pc_reg_received()`.
**Issues addressed:** None. Private report via Discord.
=> Prevent unequipping items on login before calculating the character's status data

doc/script_commands.txt, src/map/clif.c, src/map/guild.c, src/map/instance.c, src/map/party.c
- Use account ID instead of character ID for `IOT_CHAR` in `instance_force_destroy()`.
- Remove nonexistent return value `-3` from documentation of `instance_create()`.
- Show instancing window on login for party instances if instance state is `INSTANCE_IDLE`, too.
- Show instancing window on login for guild instances, too.
- Show instancing window on login for character instances, too. (This also fixes an issue where a player could create unlimited instances of owner type  `IOT_CHAR` with identical names because `sd->instances` and `sd->instance` are reset on logout.)
- Update documentation of `instance_create()` script command.
- Fix some typos.
- Add a paragraph about owner types and the corresponding owner ID to use.
- Remove nonexistent return value `-3` from example.
**Issues …
=> Update instancing window display and documentation of instance_create() script command

src/char/int_party.c
- In `inter_party_leave()` the removed party member's data is cleared before calling `inter_party_tosql()` which causes the SQL update to fail because no account ID is found.
Due to this the character is removed from the party only when its data gets saved and offline characters are not removed correctly.
- If party options are changed automatically in `inter_party_check_lv()` the party's data isn't saved.
=> Fix updating SQL data when removing party member or options are changed in inter_party_check_lv()

src/map/skill.c
Currently it's almost impossible to fulfil the condition for calling `skill_clear_unitgroup()` in `npc_unload()` since `nd->ud` always is `NULL` or `&npc->base_ud` if `unit_bl2ud2()` was never called for the NPC's block_list (for example by `npcspeed()`).
I changed `skill_initunitgroup()` to call `unit_bl2ud2()` instead of `unit_bl2ud()` if `src` is of type `BL_NPC`.
**Issues addressed:** #768 
=> Fix condition for deleting skill units when unloading NPC

src/map/skill.c, src/map/skill.h
A user reported via Discord that Slim Potion Pitcher does not work as intended because of an incorrect index selection for required items.
> on skill level 10 item_idx is 9, which cause 100% fail, because max index of requirement item array is 2, and actually skill level 3 works as level 10, with heal part, but without consuming any requirement items
To fix this issue I added `skill_get_item_index()` function.
**Issues addressed:** None. Reported via Discord.
=> Fix required item index selection for various skills

conf/map/battle/pet.conf, src/map/atcommand.c, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/pc.c, src/map/pc.h, src/map/pet.c, src/map/pet.h, src/map/script.c
- Implement intimacy display in pet egg's item description window.
- Remove pet if intimacy drops to 0 instead of making it randomly running around. (Added battle flag to disable/enable this behaviour.)
- Send pet's intimacy data only in `pet_set_intimate()`.
- Send pet's hunger data only in `pet_set_hunger()`.
- Centralize pet spawn code in `pet_spawn()` function.
- Remove ancient `FIXME` comment related to deleting taming items of type `IT_DELAYCONSUME`.
- Add `pc_has_pet()` macro.
=> Add some pet features and minor pet code clean up

conf/map/battle/client.conf, conf/map/battle/guild.conf, conf/map/battle/party.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/clif.h, src/map/packets_struct.h, src/map/party.c, src/map/party.h, src/map/pc.c
- Implement `PACKET_ZC_PERSONAL_INFOMATION` (`0x097b`) and use it in `clif_show_modifiers()`.
- Add battle flag for rate modifier messages display.
- Add missing configuration messages `CZ_CONFIG_CALL` and `CZ_CONFIG_PET_AUTOFEEDING` to `clif_parse_LoadEndAck()`.
- Add battle flag for configuration messages display.
- Extend `guild_notice_changemap` battle flag with option for login.
- Add several cases where party options should be sent.
- Add battle flag for sending party options.
- Add battle flag for overweight messages display.
- Do the message sending in new `clif_load_end_ack_sub_messages()` function to have it centralized and be able to control the order.
- Add `clif_open_ui_send()` function to do the actual packet sending for opening an UI.
- Add battle flag for tip of the day …
=> Adjust server messages on login and map change

src/map/battle.c, src/map/script.h
The `item_enabled_npc` battle flag's maximum value is 3. Thus the `npc_item_flag` field in `struct script_state` should be enlarged accordingly.
=> Enlarge field size of npc_item_flag in struct script_state according to possible values

npc/quests/quests_amatsu.txt
**First One:**
Fix Dokebi Battle Quest becoming undoable until server restart under certain circumstances.
Reproduce by having 1 person inside the battle area doing the quest, waiting for the timer to run out and have 1 person waiting in the waiting room / chat.
The waiting room will get disabled as intended but the timer will as well. If the person in the room now logs out or doesn't kill the Dokebis, the quest is bugged till server restart.
**Second One:**
Fix possible exploit in Dokebi Battle Quest
As many players as wanted could remain in the battle area, where the
dokebis and am muts spawn, as long as you have a dialogue open, which
the script provides. One could even keep a certain part of the dialogue
open right before the am muts spawn. Making you able to abuse this quest
in order …
=> Dokebi Battle Quest bugfix and exploit patch

src/char/char.c
- Adjust the SQL query in `char_change_sex_sub()` to update the character's gender and robe view ID, too.
- Remove unnecessary gender update SQL query from `char_changecharsex()`. Gender gets updated in `char_change_sex_sub()` now, so we can safely skip it in `char_changecharsex()`.
- Adjust `char_change_sex_sub()` to use prepared statements.
- Adjust `char_changecharsex()` to use prepared statement.
- Apply code style to `char_change_sex_sub()`.
- Apply code style to `char_changecharsex()`.
**Issues addressed:** #2789
=> Fix @changesex not saving new gender to SQL DB

doc/script_commands.txt, src/map/script.c
Prevent overflow of script variables (`signed integer`) when using `gettimetick(0)` by doing a bitwise `AND` operation on `timer->gettick()`' and `INT_MAX`.
This decreases the tick loop interval from ~50 to ~25 days, but I think this is the best approach to fix this issue.
**Issues addressed:** #2779
=> Prevent overflow when using gettimetick(0)

npc/jobs/2-1/wizard.txt, npc/quests/quests_juperos.txt, npc/quests/quests_lighthalzen.txt, npc/quests/seals/god_weapon_creation.txt, npc/quests/the_sign_quest.txt
Replace all OnTouch areawarp logic with areawarp were appropriate.
This fixes a few bugs and possible exploits, some OnTouch-Warp-NPCs didn't cover the entire
area they intended to areawarp. If you have any NPC Dialogue open, you
will not trigger the OnTouch and thus not get warped. Areawarp though
will ensure that you are guaranteed to get warped.
This also fixes some poor timer usage in juperos quest for example,
where one of the NPCs just won't ever get enabled again.
=> Refactor scripts that use OnTouch Logic to use areawarp instead

src/map/atcommand.c
These parameters are actually optional, use default value if not provided. 
So that we don't really need to enforce 0 for these fields if not required (example card fields 2 ~4)
However, if the fields that we wanted to customize a certain parameter, then all the parameters before it required to set value.
Instead of 
```
@item2 5001 1 1 10 0 4001 0 0 0
```
we could just do these
```
@item2 5001
@item2 5001 1 1 10                     (refine only)
@item2 5001 1 1 10 0 4001              (refine + 1 card)
@item2 5001 1 1 10 0 4001 4002         (refine + 2 cards)
@item2 5001 1 1 10 0 4001 4002 4003    (refine + 3 cards)
```
=> Enable item atcommand to have optional parameters

db/constants.conf, db/re/item_combo_db.conf, db/re/item_db.conf, doc/item_bonus.md, src/map/battle.c, src/map/map.h, src/map/pc.c, src/map/pc.h
- Add `bonus3(bSubDefEle, <element>, <rate>, <flag>)` item bonus to emulate `SubDamage_Property User <element> <rate>` from Aegis.
- Add `bonus3(bMagicSubDefEle, <element>, <rate>, <flag>)` item bonus to emulate `SubMDamage_Property User <element> <rate>` from Aegis.
- Update/add several items and item combos which use those bonuses in RE database. (Pre-RE doesn't use them.)
**Note**:
I tested several skills processed in `battle_calc_misc_attack()` on Aegis and none of them was affected by `SubDamage_Property` or `SubMDamage_Property`. Thus I decided to not add code to the `BF_MISC` case in `battle_calc_cardfix()`.
If someone knows about any "misc" type damage which should be affected by those bonuses please let me know.
**Issues addressed:** #548
[cont]: …
=> Add bonuses to reduce received damage based on attacker's defense element

db/re/refine_db.conf
hd ores to normal ores chances, fix chances to 10>refines
* Change HD ores to match normal ores chances
* Fix refine chances on 10+ refines
**Issues addressed:** #2771  
=> refinery fix

db/re/item_db.conf
The Flying Galapago on `db/re/item_db.conf` was not working like how it works on official and throws this error on console every time the script takes effect.
> [Error]: pc_skill: Skill level 40 too high. Max lv supported is 20
=> Added official script for Flying Galapago headgear.

src/map/itemdb.c
This just removes the extra `/` in loading the `item_combo` file.
From:
`[Status]: Done reading XXX entries in 'db/re//item_combo_db.conf'.`
To:
`[Status]: Done reading XXX entries in 'db/re/item_combo_db.conf'.`
=> Fixed item_combo load out on console.

src/map/script.c
A missing call to `pc->autocast_clear_current()` made it possible to bypass the deletion of skill requirements of a normally cast skill by using a scroll.
**Issues addressed:** N/A (privately reported)
=> Fix an exploit in the autocast system

src/map/clif.c
Send inf to client of some combo skills, in particular MO_EXTREMITYFIST, TK_JUMPKICK, SR_DRAGONCOMBO, SR_GATEOFHELL and SR_TIGERCANNON.
When doing combos (ie: SR_DRAGONCOMBO -> SR_FALLENEMPIRE -> SR_GATEOFHELL), the named skills were not changing the target type (on combos it should be INF_SELF_SKILL since it auto target). Instead it was sending the target type defined on the skill_db (all this skills are enemy targeted) because it was not checking the passing arg `inf`.
=> Fix on clif_skillinfo to check inf argument

src/map/guild.c
Fix memory corruption on using command ``@unloadnpc`` or any other way for unload npc file.
=> Fix memory corruption on unloading npc

src/char/char.c
This PR adds an explicit check to skip skills with the `SKILL_FLAG_PLAGIARIZED` flag when saving them. It introduces no functional changes, since the issue was already caught by the subsequent Assert_chk.
Skills learned through Plagiarism should be treated like temporary skills and skipped when saving the character's skills, since they're already saved through char regs.
**Issues addressed:** https://herc.ws/board/topic/18999-plagiarism-server-error/
=> Fix a failed assertion in the char server when trying to save a plagiarized skill

src/map/skill.c
Some charm elements has multiple possible status effects, those effects per element shouldn't happen at the same time as other effects are being inflicted on the specific targets on the AoE. This PR fixes that issue which should only trigger one effect per `tick`.
=> Adjusted KO_ZENKAI AoE Effect

npc/quests/bard_quest.txt, npc/quests/quests_13_1.txt, npc/quests/quests_ein.txt, npc/quests/quests_morocc.txt, npc/quests/quests_nameless.txt
There are a few cases, especially in quests where thankfully mostly flavor texts were never able to trigger, because `BaseClass == Job_Assassin` for example was compared, while BaseClass will always return a 1-1 *normal* job or Job_Novice.
All these unsatisfiable conditions have been changed to what they were intended to be.
One of the Bar Keepers for example that sells Tropical Sograt for 800z to Assassins and everyone else 1000z was not offering that options to Assassins, that has been fixed.
Also in 2 files in a separate commit I removed some trailing whitespace.
=> Fix BaseClass misuse

src/map/clif.c, src/map/clif.h, src/map/status.c
This fixes convex mirror, where it should display monster location on the mini-map constantly until the status isn't yet `INVALID_TIMER` as long as the there is a boss on the certain map(alive or dead?) where you used the convex mirror itself and will display respawn time after you used the convex mirror or while the effect is still up.
=> Fixed convex mirror effect

src/map/pc.c, src/map/skill.c, src/map/skill.h
https://github.com/HerculesWS/Hercules/issues/2815
the actual reason why dancer didn't get the skill is because the dancer's skill index is lower than bard's
when it continue on the loop, it hit the condition above and set skill level into 0
so move the dancer/bard soul link check out of the loop
* Master
=> fix dancer with soul link didn't get the bard skills counterpart

npc/other/Global_Functions.txt
Currently dealing with a paid service script, that needs to display integer higher than 2.1b
--> please remember SQL can calculate value above INT_MAX
I have my own int__ function .... but I try to use the one in Github
nope doesn't work, it doesn't allow to display value higher than INT_MAX
the tested script below, will show you 2.1b if input over that value, along with this error on console
```
[Error]: script:conv_num: overflow detected, capping to 2147483647
[Debug]: Data: string value="1321321321321"
[Debug]: Source (NPC): dsfsdflkjsdf at prontera (158,185)
```
`.@value` variable removed, and change `.@is_negative` to check condition with strings …
=> update F_InsertComma to allow numbers bigger than INT_MAX

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/map.c, src/map/map.h, src/map/skill.c, src/map/unit.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Refactors map->random_dir. Adds map->get_random_cell and map->get_random_cell_in_range.  
Implements correct behavior of Confusion / Chaos movement, WE_CALLPARTNER, WE_CALLPARENT, WE_CALLBABY and AM_RESURRECTHOMUN.
Visualized gaps of map->random_dir 's distribution mentioned in a commit and documentation now:
**Issues addressed:** none?
=> Refactor map->random_dir and implement aegis behavior of some skills which used it

3rdparty/libconfig/scanctx.c, src/common/conf.c
Override code try to open first conf/import/include/SERVERNAME/FILEPATH file,
if it failed fallback to normal FILEPATH path.
This feature need for example for override sql_connection.conf
without changing any other configs.
=> Allow override libconfig command @include

src/map/battle.c
This fixes the damage buff effect of watery evasion when using freezing spear.
=> Fix Freezing Spear on Watery Evasion

src/map/npc.c
https://github.com/HerculesWS/Hercules/issues/2848
cap the value as 1 or 2 only
if it is 0, it becomes 1(default), and if it is over 2, becomes 2
```
guild_vs2	mapflag	battleground
```
tested is 1, because the sscanf return 0 didn't found w4
* Master
blame https://github.com/HerculesWS/Hercules/pull/2654 ... yeah its @Emistry again
=> fix missing scoreboard for battleground type 2

src/map/mob.c
This PR adds monster sprite names, if available, to some errors when loading mob skill db file. Some messages were changed in another PR, but I noticed a couple missing. This is helpful when fixing mob skill db errors because most of the time you are using their constants.
None, I think
=> improve error messages in mob skill db to show monster constants

src/map/clif.c, src/map/searchstore.c
Fixes 2 checks in search store function:
1. it prevents trying to search with an empty item list, this is not even allowed by the client, and makes no sense in the process, as it always start the search by an item. (that's why I put the check on clif)
2. When searching for an item without asking for cards, it was giving us a nullpo because card_list would be NULL (as it becomes a "0-length array"), but it is a totally valid search (e.g. Searching for an ETC item would never have cards to check for). So I disabled the null pointer check when the card count is zero, from my tests and checking the code, every code called from this would check card count before trying to access the array, so it looks safe.
None, i think
[cont]: …
=> Fix nullpo error in searchstore

src/map/battle.c, src/map/mob.c, src/map/mob.h, src/map/skill.c, src/map/unit.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
- Fix return value evaluation of `mob_skill_use()` in `mob_ai_sub_hard()`.
- Fix `nullpo`-check return values in `mob_skill_use()`.
- Fix `nullpo`-check return values and initial value of variable `ret` in `mobskill_event()`.
- Rename `mob->skill_use()` to `mob->use_skill()` due to changed return values.
- Rename `mob->skill_event()` to `mob->use_skill_event()` due to changed return values.
=> Fix some wrong return values in mob skill code

src/map/mob.c
Fix summoned monsters wont follow masters of type `BL_PC`.
**Issues addressed:** #2808
=> Fix summoned monsters wont follow masters of type BL_PC

src/map/status.c
Impositio Manus always overwrites itself regardless of which skill level is used.
_The [skill rebalancing update](https://ro.gnjoy.com/news/notice/View.asp?seq=7040) changed this behaviour, but yet we didn't even start implementing that update._
**Issues addressed:** #695
=> Make Impositio Manus always overwrites itself

src/map/unit.c
Prevent using unit->set_dir needlessly in unit_attack_timer_sub
Also prevents broadcasting it needlessly with clif_changed_dir
Credits to Heka from Origins Online Staff
**Issues addressed:** none
=> Prevent using unit->set_dir needlessly in unit_attack_timer_sub

src/map/npc.c
- Add check for `nd->bl.m` being a valid array index for `map->list[]` to `npc_setclass()`.
- Apply code style to `npc_setclass()`.
**Issues addressed:** #2899
=> Fix map server crash when changing display class of floating NPC

src/map/script.c
- Add check for receiver ID is in valid range to `rodex_sendmail_sub()`.
- Add check for valid item amount to `BUILDIN(rodex_sendmail)`.
- Add check for valid item amount to `BUILDIN(rodex_sendmail2)`.
**Issues addressed:** #2897 #2898
=> Add some data evaluation to the RODEX send mail script commands

src/map/skill.c
This PR will fix KO_GENWAKU skill effect where there is a chance of you and your target swapping position.
=> Fixed KO_GENWAKU Swap Effect

src/char/mapif.c, src/common/mmo.h, src/map/intif.c
Using too large values for `MAX_STORAGE` or `MAX_GUILD_STORAGE` can cause oversized inter-server packets which leads to a server shutdown.
To prevent this static assertion checks were added which make the user aware of this issue.
Additionally some related documentation was added/extended.
=> Add static assertion checks to prevent MAX_STORAGE and MAX_GUILD_STORAGE from causing oversized inter-server packets

doc/script_commands.txt, src/map/script.c
follow up https://github.com/HerculesWS/Hercules/pull/2900
Add ShowWarning on `*setnpcdisplay` and `*setunitdata` for floating npc
```c
-	script	asdasd	1_F_MARIA,{
end;
OnInit:
setnpcdisplay strnpcinfo(NPC_NAME), WARPNPC;
setunitdata getnpcid(), UDT_CLASS, Job_Priest;
end;
}
```
* Master
none
since the server no longer crash, now its time to put the warning message on
and able to test it without server keep crashing
=> Add ShowWarning on *setnpcdisplay and *setunitdata for floating npc

npc/cities/niflheim.txt
Prevents farm exploits (via Mimic & Myst Case Card for example) at Cursed Spirit NPC by doing the following:
- Kills monsters that were spawned right before spawning them, to prevent queuing up NPC dialogue on several characters.
- Prevents respawning monsters before 60 seconds elapsed since last summon.
**Issues addressed:** none?
=> Prevent farming exploits at Cursed Spirit NPC

src/map/mob.c
Fix battle config variable monster_loot_type not working as intended
When it was set to 1, monsters would still loot, even though they
aren't supposed to.
When it was set to 0 and the monster couldn't loot anymore, monsters
would still try to loot, even though they should avoid doing so.
**Issues addressed:** #2834
=> Fix incorrect looting behavior with monster_loot_type battle config

conf/map/battle/monster.conf, src/map/battle.c, src/map/clif.c, src/map/clif.h, src/map/mob.c
Disable HP bar on Emperium and MVP by default
Added configuration via battle conf to enable again
https://github.com/HerculesWS/Hercules/issues/744#issuecomment-171254762
=> Disable HP bar on Emperium and MVP by default

npc/quests/the_sign_quest.txt
If you timeout or logout before triggering the OnTouch that is in the Room
Serin sends you to, a global variable wasn't being unset.
This locked this part of the quest for everyone and made it impossible
to enter that room anymore, until server restart.
1. Prevent the timer for unlocking the room from not starting when room gets locked.
2. Prevent an exploit, where it was possible to enter Serin's room with more than 1 person in the solo-path of the quest.
3. Prevent the witch's part of sign quest becoming unfinishable for everyone.
=> Fix a part of sign quest becoming unfinishable for everyone

db/pre-re/mob_db.conf, db/re/mob_db.conf
- They will take only `10%` of damage dealt.
- This will applies to bosses in Endless Tower and Central Laboratory as well.
However, the following MVP aren't in the database yet, so they aren't included for now.
```
Gold Queen Scaraba / Spider Chariot / R48-85-BESTIA / Rigid Muspellskoll / 
Corrupted Dark Lord / Corrupted Spider Queen / Jewgoliant / Bone Datardeurus / 
Reginleif / Ingrid / Chimera The One / R001-BESTIA / Death Witch
```
https://www.divine-pride.net/forum/index.php?/topic/3318-kro-mvp-bosses-adjustment/
=> Update MVP DamageTakenRate

src/map/skill.c
This should fix the Failed Assertion when using Homun's Summon Legion Skill and should now summon 5 Luciola Vespa on level 5. Thanks to @4144 
=> Fixed assertion error with MH_SUMMON_LEGION.

src/map/homunculus.c
Check for homunculus skills requisites before leveling it up.
Does nothing if player.skillfree was set on battle configuration.
This allows non-evolved homunculus to make use of pre-requisites DB.
PS. I'll be very happy if someone else takes this patch for me.
I feel there are better ways to do this which I don't have enough skill to pursue.
Note: The code was copied from homunculus_calc_skilltree()
The former function is only called in the following cases:
* clif->send_homdata when intimacy >= 910 (hardcoded?) and evolved homun
(won't cause this code to run)
* status_calc_homunculus_ which is aliased as status_calc_homunculus
* Here, after the skill points has been consumed and the skill updated,
but is skipped except for evolved homuns. [Not sure if does anything]
(won't cause this code …
=> Check for homunculus skills requisites before leveling it up.

db/pre-re/item_db.conf, db/quest_db.conf, src/map/quest.c, src/map/quest.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
These changes were made using Asheraf's #2874 as base, so it must wait for it before being merged.
This change allows the use of constants for monster IDs and Item Ids. Also it adds some error messages when ignoring entries, so the user knows what happened.
After doing the change, some quests were giving errors on pre-re, because they have special RE drops, so I copied those items to pre-re db, as you shouldn't get the quest.
None, I think.
=> Allow constants on QuestDB

src/common/grfio.c
This fixes a couple of issues where the grfio library fails to load the kRO GRF.
=> Fix grfio on big size grfs

src/map/atcommand.c
If show_msg() requests a message code which is not present in messages.conf, a "??" will be provided silently.
This raises a warning so maintainers and fork owners can debug and fix their messages.conf file.
(This should not happen normally).
=> Report to console if a missing message is requested

src/map/clif.c, src/map/packets_struct.h
=> Convert some skill packets to structure format

src/map/clif.c, src/map/skill.c, src/map/unit.c
This introduces various fixes to the Abracadabra / Improvise skill validation:
- autocast code is moved to after homun/merc skill ranges so that when any of those are triggered, autocast data is not purged
- abracadabra/improvise is no longer purged immediately after cast, by calling autocast_clear_current in the proper manner
- the abracadabra/improvise skill requirement bypass that was removed in #2657 and related pull requests is re-implemented
- the condition that would get the character stuck and unable to cast other skills until teleporting or relogging when rolling AL_WARP from abracadabra (i.e. because AL_WARP lands in clif_parse_UseSkillMap in 2 steps) is fixed, by not immediately clearing the data after the first one
All credits for the fixes go to Heka of Origins
**Issues …
=> Fix Abracadabra / Improvise / itemskill validation

src/map/skill.c
This fixes vacuum extreme status gets permanent until you logout or die. This should force the max time reduction to 6.5 secs, vs before which exceed up to 18 secs(depends on target strength) when level 5 extreme vacuum only has 12 secs max duration.
**Issues addressed:**  #2919
=> Fix permanent vacuum extreme status.

src/map/status.c
\* not sure if `skillTimerIsValid` is considered a frowned-upon mixed case name.  Please recommend a better name if you'd prefer one
Ensure free cast modifies the walking speed of a unit rather than sets it.  This is to fix a (potential) bug where a cursed unit gets 75% of their original walk speed by using free cast.
#2976 
=> ensure free cast modifies speed rate instead of sets it

src/map/script.c, src/map/script.h
This updates various functions in script.c to be aware that the `struct script_state::rid` field may contain a mob's GID alternatively to a player's, when called through `OnTouchNPC`. This fixes various errors, such as the one described in #2989 and #2990.
**Issues addressed:** #2989
=> RID unexpectied behavior from OnTouchNPC

conf/login/login-server.conf, src/common/console.c, src/common/sysinfo.c, src/common/sysinfo.h, src/login/login.c, src/login/login.h
Client may send special flags in client_version field.
In this pr hercules will compare current server flags and client flags, and if flags different then client will be disconnected.
This will prevent from strange bugs if server or client was created with different features.
For now only supported feature flag is cash show with preview support.
For enable flags in client need enable this patch http://nemo.herc.ws/patches/SendClientFlags/
=> Add reading and checking client flags

src/map/script.c
- [√] I have followed [proper Hercules code styling][code].
- [√] I have read and understood the [contribution guidelines][cont] before making this PR.
- [√] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.
Added missing re-equip of item in successremovecards
Fixed re-equip in failedremovecards and setequipoption
=> Fix pc_equip

src/map/battle.c
wd.damage2 not applying target side calculation (resist reductions)
Issue #3011 wd.damage2 not applying target side calculation (resist reductions)
=> issue #3011 fix - wd.damage2 not applying target side calculation (resist reductions)

src/map/mob.c, src/map/mob.h, src/map/script.c, src/map/status.c, src/map/unit.c
- [√] I have followed [proper Hercules code styling][code].
- [√] I have read and understood the [contribution guidelines][cont] before making this PR.
- [√] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.
Made view_data for mob unit changes persistent.
As of now, if we use setunitdata to change the view_data of a mob, it works but it overwrites the data, not changing the view data for that specific unit.
It's a PR from rathena
All credits to: @Lemongrass3110 
=> Made view_data for mob unit changes persistent

src/map/skill.c
Move map unlock from skill_castend_nodamage_id_unknown to caller
=> Move map unlock from skill_castend_nodamage_id_unknown to caller

src/map/battle.c
This PR should fix the OP damage of Cart Tornado. Thanks to 3Ceam[Rytech] and 4144.
=> Fixed damage overflow on GN_CART_TORNADO.

src/map/mob.c
=> Fix mob groups reading rate from wrong object

src/map/skill.c
This is part 2 of #2995. This fix is about multiple targets experiencing different duration when hit by SC_VACUUM_EXTREME.
To experience the bug: you must place multiple characters within range of extreme vaccum(atleast 5 targets), then check if all targets can move once the status ends.
FIXME: This is a temporary fix. SC_VACUUM_EXTREME should be same duration to all affected targets instead of splitting the Duration to each target within the AOE.
=> Fixed permanent SC_VACUUM_EXTREME on multiple targets

src/map/atcommand.c, src/map/chrif.c
Removed redundant condition for checking homun_data.
=> Redundant homun_data check.

db/constants.conf, doc/item_bonus.md, src/map/battle.c, src/map/map.h, src/map/mob.c, src/map/pc.c, src/map/pc.h, src/map/script.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Added the following item bonuses:
- `bonus bSubSkill`
- `bonus2 bDropAddRace`
=> Added new item bonuses

db/re/skill_db.conf, src/map/battle.c
Fixes skills reported on #1597
- Updated damage formula to `3 * (Kunai Atk+ Weapon Atk + Base Atk)) * (Skill Level + 5) / 5`
- Pierce attack modifier no longer applies to it
- Element comes from kunai rather weapon
- SP Cost gets increase and Hit count should be 1 
- It should now apply elemental modifier and ignores target's flee.
- Damage should now be 3x when skill element is ghost.
=> Some renewal skill fixes

doc/script_commands.txt, npc/dev/test.txt, src/map/script.c
When supplied with the current time (hour and minute), `getcalendartime`, in some cases, gives today as the "next occurrence of a time" instead of the same hour/minute of the next day. "Some cases" being dependent on the parameters used.
I believe this is an unexpected behavior, because:
1. the code doesn't go for that rule in all cases;
2. I remember custom scripts having issues because it was used expecting to be the next day (discord discussion);
3. The original reason to make this command was to make quest cooldown to a fixed time, if the user just finished the quest, you wouldn't expect that the cooldown is 0 (or negative).
So I updated it to make an standard of always looking for the next occurrence.
Also added a CI test for that and improved the documentation to clarify this …
=> Fix getcalendartime when using current time

src/common/mmo.h, src/map/atcommand.c, src/map/clif.c, src/map/rodex.c, src/map/script.c, src/map/script.h
This PR fixes a few issues on RoDEX, specially in message creation. Some of them produced **visual glitches** that could lead to the user sending wrong attachment. Also, as I was reading the code I tried to simplify and style fix some parts to make easier to read, I did it in separate commits so it doesn't hide behind the real fixes, let me know if some commit should be squashed.
Finally, it exposes the script command helper function `rodex_sendmail_sub` in the script interface, it is now named `buildin_rodex_sendmail_sub` to match other similar functions.
To help debug it I added the inventory index (`idx`) to the `@itemlist` command, if you think it doesn't belong there, I am fine with removing it :)
The issues addressed are the following:
**Issue when attaching the first item in …
=> Few fixes to RoDEX

src/map/map.c
This fixes issues with skills such as Sharpshooting where the shooting path had gaps or was too narrow for it's width.
=> Fix map->foreachinpath having gaps or too narrow paths

src/map/skill.c
On Hercules we're currently applying the strip effect from rogues when the Armor & Weapon Break triggers for non-player characters. This is wrong, nothing should happen.
=> Implement official behavior for Acid Demonstration Armor & Weapon breaking

src/map/battle.c
Checked via official server software ep 11.2
The function is only used for pre-renewal calls, thus no ifdefs.
=> Fix HLIF_CHANGE not using max MATK only for pre-renewal

db/constants.conf, doc/constants.md, doc/sample/localized_npc.txt, doc/sample/npc_test_checkweight.txt, doc/sample/npc_test_duplicate.txt, doc/script_commands.txt, src/map/script.c
**Issues addressed:** N/A
This cleans up and removes some long time deprecated script commands and constants (every removed command has been deprecated at least two years ago and has a feature complete recommended replacement).
Additionally, the `getpetinfo(PETINFO_NAME)` command has been updated to return an empty string instead of the `"null"` string when no pet is found.
Summary / cheatsheet of the removed deprecated commands:
| Removed | Replacement | Notes |
| --- | --- | --- |
| `getguildname(<guild_id>)` | `getguildinfo(GUILDINFO_NAME, <guild_id>)` | Resolves `"(null)"` ambiguity |
| `getguildmaster(<guild_id>)` | `getguildinfo(GUILDINFO_MASTER_NAME, <guild_id>)` | Resolves `"(null)"` ambiguity |
| `getguildmasterid(<guild_id>)` | `getguildinfo(GUILDINFO_MASTER_CID, <guild_id>)` | …
=> Remove deprecated commands

src/map/mob.c
The value was accidentally always overridden to be 900%. With the intent to cap to 90%, `max(rate, 90000)` erroneously used instead of `min(rate, 9000)`.
**Issues addressed:** N/A (reported in discord)
=> Fix a regression in the mob drop rate calculation

src/map/script.c
The card check was always failing because card2 was tested against the whole char_id rather than just its lower 16 bits.
The check is now done by using the appropriate `MakeDWord()` function to recompose the char_id from card2 and card3
**Issues addressed:** N/A, the problem was reported privately
=> Fix countnameditem() always returning 0

src/map/macro.c
Fixes an inconsistency causing captcha images loaded server side to fail zlib compression on non-windows systems.
Privately reported by Afonso
=> Fix an issue with captcha compression on linux

db/constants.conf, db/pre-re/sc_config.conf, db/re/sc_config.conf, doc/script_commands.txt, src/map/atcommand.c, src/map/clif.c, src/map/script.c, src/map/status.c, src/map/status.h
Adds `active_transform` script command. This command works like `montransform` but gives a different SC that is stackable with the `montransform` one. sc_config was based in the `montransform` one.
**Issues addressed:** #2035 
=> Adds active_transform script command

src/map/script.c
Signed-off-by: Haru <haru@dotalux.com>
This fixes an inverted test condition (string inequality instead of string equality) that would make the conditional feature test always succeed.
**Issues addressed:** N/A
=> Fix an error causing conditional feature checks to always be true

src/map/skill.c
```
{
Id: 4283
AegisName: "Greatest_General_Card"
Name: "Greatest General Card"
Type: "IT_CARD"
Buy: 20
Weight: 10
Loc: "EQP_ACC"
Script: <" bonus3 bAutoSpell, MO_CALLSPIRITS,5,2+18*(BaseClass==Job_Acolyte); ">
},
```
clearly says here `MO_CALLSPIRITS` with level 5, should be casted here, which means max spirit should be 5. Currently when used, it only allows to cast 1 spirit which is wrong.
Thanks to @Maginitis at discord.
=> Fixed MO_CALLSPIRITS on bAutoSpell

src/common/cbasetypes.h, src/common/strlib.h, src/map/HPMmap.c, src/plugins/HPMHooking.c
Add missing includes in hpm.
Allow attribute access only for gcc 10 and newer.
=> Small fixes

src/map/clif.c
This should resume any active options on a character even after you use @refresh.
**Issues addressed:** #2706 
=> Resume visuals of active states after @refresh.

src/map/grader.c, src/map/refine.c
This fixes an issue where the item is changed/deleted before the status update is sent in the grade enchant interface.
Thanks to @Lemongrass3110 for letting me know about the issue.
=> Fix grade enchant ui status result order

src/map/status.c
Should fix the bug whenever mercenary updates whenever it idles/spawns/walks gets the "Unknown" name due to `NULL` return of `status_get_name`.
=> Fixed updating mercenary name

src/map/clif.c, src/map/clif.h, src/map/instance.c, src/map/instance.h, src/map/map.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
This PR fixes some issues around instance information and destruction, that could cause visual glitches and assertion failures. Also, I have changed the response numbers into an enum to make it clear. Those are the issues addressed:
**Issue 1:** When players were moved out of an instance due to it being expired, they were receiving the information that the instance actually went Idle instead of destroyed. That was caused because when moving players out of the instance, it is still considered a valid instance, and this triggers the idle check.
To fix that, instances are now marked as "being destroyed", and thus invalid, before moving players out of it.
**Issue 2:** When a player had a Player Instance attached to them, even after being destroyed, they were still receiving the instance info …
=> Fixes on instance information/destruction

.github/workflows/controller.yml, .github/workflows/gccold1.yml, .github/workflows/gccold3.yml
This fixes GitHub Actions CI build failures caused by an unsupported Ubuntu distribution not finding its package repositories online.
Ubuntu 21.10, used by the `gcc-10`, `gcc-9` and `gcc-8` CI builds is EOL since 2022-07-14. The image has been replaced with alternative versions that include the same packages.
The following changes have been made:
- `gcc-10` and `gcc-9` have been moved from 21.10 to to 22.04 LTS, which will be under standard support until April 2027 and EOL in April 2032 (workflow `gccold1`).
- `gcc-8` has been moved from 21.10 to to 20.04 LTS, which will be under standard support until April 2025 and EOL in April 2030 (moved from workflow `gccold1` to `gccold2`).
- `gcc-7` has been moved from 18.04 LTS to to 20.04 LTS, as described above (workflow `gccold2`).
- `gcc-6`, …
=> Fix CI build failures caused by Ubuntu 21.10 going EOL

doc/script_commands.txt, src/map/script.c, src/map/script.h
1. Adds UDT_OPTIONS to getunitdata/setunitdata. This is so people can use data when from mobs who are using job sprites. E.g.
```
{
Id: 3990
SpriteName: "Novice_Sprite"
Name: "Novice"
Hp: 100000
Element: ("Ele_Ghost", 4)
ViewData: {
SpriteId: 0
ShieldId: 4
HairStyleId: 4
HairColorId: 1
BodyColorId: 1
Gender: "SEX_MALE"
Options: 16
}
},
```
Then in a script, `getunitdata(<GID>, UDT_OPTIONS)` would return 16.
2. Second commit makes it so if you use setunitdata with a job id, e.g. `setunitdata(<GID>, UDT_CLASS, 0)` would set the mob sprite to Novice.
=> getunitdata/setunitdata: Adds UDT_OPTIONS and changes UDT_CLASS to work with Job sprites

conf/map/battle/skill.conf, db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c, src/map/skill.h
=> Refactor Skill Copy via Plagiarism and Reproduce

src/map/skill.c
- Make PF_SOULCHANGE not useable on berserked characters
- Make PF_SOULCHANGE not useable on bosses as on officials
- Make SC_FOGWALL never miss PF_SOULCHANGE under any condition as on officials
Verified on pre-re and re Aegis.
=> Fix Soul Exhale behavior

db/pre-re/skill_db.conf, src/map/battle.c, src/map/party.c, src/map/pc.c, src/map/skill.c, src/map/status.c
- Fix Kihop counting the Taekwon into the bonus
- Implement official Lex Aeterna interaction with Freeze and Stone Curse
- Implement official sp cost behavior for Tarot Card of Fate (when using Service for you)
- Remove trailing whitespace in pc.c
- Fix duration of Super Novice' Steel Body when dying at 99% exp
- Fix Cast Time and After Cast of Napalm Beat
- Fix CH_CHAINCRUSH not working after MO_COMBOFINISH
Verified in pre-re Aegis.
=> Add a few small skill fixes

src/map/unit.c
Stop units from moving and, consequently, notifying the client when the unit is already dead and the server is going to send a notification to vanish such unit. Fixes mobs walking around or standing when killed.
This issue has been already discussed here https://github.com/HerculesWS/Hercules/issues/2109 with some insights, however, I think this patch is fine as this "move request" should never be done after death. Nonetheless and, as precaution, this check could be made against BL_MOB only, which uses a timer and it's the main reason this visual bug appears.
https://github.com/HerculesWS/Hercules/issues/2047
https://github.com/HerculesWS/Hercules/issues/2109
[code]: …
=> Stop units from moving when dead

src/map/packets_struct.h
Image size is 59454, which is > INT16_MAX.
Therefore uint16 should be used.
The rest of the code should also be checked, as it uses int32 instead of int16 in general.
=> Fixed signedness of image size

conf/messages.conf, doc/atcommands.txt, src/map/atcommand.c, src/map/atcommand.h, src/map/clif.c, src/map/quest.c, src/map/quest.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
This PR introduces a few fixes to quest log:
1. Quests with 3 objectives doesn't fail an assertion anymore.
2. Quests using monster size, race or element as condition were giving out some wrong labelling.
For example, a quest for "hunting fire monsters" would give something like "fire formless monsters", while actually just checking for fire element. That was due to the code not checking whether a race/element of 0 meant no race/element, or the race/element that actually has ID = 0 (as they are 0-based).
3. Fixes the bitmask value for size
Quests that asked for a monster size were not being sent correctly to the client. I tested on 2019-12-24. I will be honest... I went by trial and error until the label showed up... so I am not sure if this changes in newer clients (@Asheraf do you know …
=> quest log fixes and quest atcommand

src/char/int_rodex.c, src/map/intif.c, src/map/rodex.c
Small fixes on RoDEX zeny retrieval process (specially for error cases).
1. Fix packet reading for GetZenyAck packet that was reading the `zeny` value using the wrong type;
2. Stop zeroing the mail's zeny if checking for the mail data failed. Otherwise, the value is lost forever;
3. Move the map-server side cleaning of the zeny flag to after the ACK is received, otherwise an error would prevent the player from being able to try again
None, I think
=> Fixes on rodex zeny retrieval

conf/messages.conf, src/map/atcommand.c, src/map/clif.c, src/map/map.c, src/map/map.h, src/map/npc.c, src/map/rodex.c, src/map/script.c, src/map/script.h
Prevent users from sending mails using RoDEX on maps with nostorage mapflag.
Makes sense on my head but **I have not checked official behavior**, thus I advise checking if it is possible to use RoDEX not only to send but also to receive mails on these maps.
I would kindly appreciate if the PR was closed if this is not a desired or official behavior.
=> Prevent users from sending mails using RoDEX on maps with nostorage mapflag.

.github/workflows/build.yml, .github/workflows/clang15_test.yml, .github/workflows/gcc_test.yml, .github/workflows/gccold1.yml, .github/workflows/gccold2.yml, .github/workflows/gccold3.yml, .github/workflows/gccsnapshot_test.yml, .github/workflows/mariadb.yml, .github/workflows/mysql.yml, .github/workflows/tools.yml, tools/validateinterfaces.py
This removes the last leftovers of python2 in the tools and uses python3 only in the CI builds. Debian unstable seems to have dropped python2, so we can no longer rely on it. The scripts seem to be compatible with python3 (since june 2020) even though validateinterfaces was still executed through python2.
**Issues addressed:** N/A - CI build failures on master
=> Remove python2 dependency from the CI builds

conf/map/battle/monster.conf, src/map/clif.c
Added guardian mode in show monster hp bar (default: no)
Added monster mode Guardian
Well I really don't know if this is the correct fix for this as WOE guardians should not show HP bar as well by default.
In our database, guardians has Boss mode enabled thus the config below will not show HP bar for guardians as well on default because they are treated as boss/MVP as well. Enabling the hp bar for MVP will enable the hp bar for the guardians as well.
// Show hp bar on monsters? (Note 3)
// NOTE: only works on client 2012-04-04aRagexeRE onwards
// 1 = Show hp bar on all monsters except Emperium and MVP
// 2 = Enable hp bar on Emperium
// 4 = Enable hp bar on MVP
// (Default: 1)
show_monster_hp_bar: 1
https://github.com/HerculesWS/Hercules/pull/2008 …
=> WOE Guardians hp bar fix

.gitignore, doc/global_configuration.md
I just noticed that include overrides (introduced on #2881) was not documented at all. This PR documents this quite useful feature.
Also, adding the path of those overrides to `.gitignore`, as they will usually contain server-specific info (and for sql_connection, even passwords), I believe it makes more sense to be ignored. If you think otherwise, feel free to send a change request and I will remove the commit.
=> Document and git ignore include overrides

npc/quests/quests_amatsu.txt
Experience rewards for both Pre-Re and Re were added. However, there isn't documentation for the exact four instances where Renewal rewards the player, so they were added in key moments of the quest (due to no multi-leveling, the separated instances are important for low level characters).
Missing experience reward in Amatsu Dungeon Quest for both Pre-RE and RE.
=> Add missing EXP reward to Amatsu Dungeon quest

src/map/battle.c, src/map/mob.c, src/map/skill.c
This fixes how damage taken rate is controlled at unit level.
Currently, we have a DamageTakenRate for monsters that is configured at db level (via mob_db), but we also have an option in `setunitdata` that allows customizing it for a single GID. The later case (single GID) was not working because every calculation was happening using the `db` field instead of the unit one.
With this change, every calculation will use unit's own rate, which will be initially set to the same as the one defined in `mob_db`
**Issues addressed:** None, I think
=> Fix unit-specifc damage taken rate

conf/map/battle/skill.conf, src/map/battle.c, src/map/skill.c, src/map/unit.c
Set skill_amotion_delay setting to 0, remove castend motion delay and apply at castbegin.
While the previous setting and behavior could stop some speedhack attempts, it does not fit oficial behavior and produces erratic behavior with the client.
For a more detailed explanation, please check https://github.com/rathena/rathena/issues/944
**Issues addressed:** [2703](https://github.com/HerculesWS/Hercules/issues/2703)
=> Set skill_amotion_delay default value to 0 and applied amotion at castbegin

src/map/clif.c, src/map/script.c
Simply replace some `sprintf` with `snprintf`, keeping their destination array size. This removes a few warnings about possible overflows (which never happens in default configs).
**Issues addressed:** None, I think
=> Fix some printf overflow warnings

.github/workflows/build.yml, .github/workflows/clang15_test.yml, .github/workflows/gcc_test.yml, .github/workflows/gccold1.yml, .github/workflows/gccold2.yml, .github/workflows/gccold3.yml, .github/workflows/gccsnapshot_test.yml, .github/workflows/mariadb.yml, .github/workflows/mysql.yml
1. Change healthcheck code for actions using MariaDB container.
the current approach of using `mysqladmin ping` is failing all the time, using the healtcheck script contained in the container image should be enough, since it ensures the instance is reachable
mysql containers still use mysqladmin ping (since healthcheck.sh is not available for them)
from my tests, the issue about failing due to unhealthy MariaDB is fixed. There is still the rare occurrence of one container failing in the overall step, but restarting the specific one works.
2. Add a 1 hour timeout to all jobs that runs hercules
After fixing MariaDB checks, I noticed that tests that starts/stops Hercules sometimes gets frozen and stays running until it reaches GitHub's default timeout (6 hours). Those jobs usually finish in …
=> Actions CI adjustments

db/pre-re/skill_db.conf, db/re/skill_db.conf, doc/script_commands.txt, src/map/battle.c, src/map/skill.c
Solves some issues with Guillotine Cross' Poisoning Weapon skill:
1. It had some issues with the effect rates and duration calculation
2. It was applying a very wrong duration for Venom Bleed poison
3. It was not showing a result message upon poison application
References:
- https://github.com/rathena/rathena/pull/6263
- https://www.divine-pride.net/database/item/12724/venom-bleed
None, I think. Bug was found by Lexi on discord
=> Guillotine Cross Poisoning Weapon skill fixes

conf/map/battle/battle.conf, src/map/battle.c, src/map/battle.h, src/map/skill.c
Currently, the damage caused by the poison status inflicted by Venom Dust does not return experience points.
This seems to be the official behavior. This PR adds a toggle setting to allow Venom Dust to give experience.
#3188 
=> Added toggle to allow venom dust to give experience points

src/map/atcommand.c, src/map/chrif.c, src/map/clif.c, src/map/clif.h, src/map/pc.c, src/map/skill.c, src/map/status.c, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Individually delete skills that are not available anymore yet the client still displays in the skill tree and the skillbar.
For example, equipping and unequiping a clip with a smokie card that grants the skill `hiding`.
#3209
=> Individually delete unavailable skills on status refresh

src/config/core.h, src/map/battle.c, src/map/clif.c, src/map/status.c, src/map/unit.c, src/map/unit.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Currently, server iteration differs from client behavior when a target receives damage.
As of now, when a character is moving to X/Y and receives damage, clif_damage is invoked and the client reproduces the flinch animation shortly after, locking the character in place without reaching X/Y.
Server side the character is also stopped and a walk delay is applied, however the delay in which this happens is much larger than the one in the client, allowing the character to walk additional cells server side without the client being aware of this, causing positional lag and visual inconsistencies.
This change adds a macro option to apply the walk delay (and stopping the character) at a time relatively similar to the time the flinch animation is displayed client side.
None …
=> Added option to synchronize flinch animation with walk delay

src/map/battle.c
Due to a coding bug in eathena, AM_ACIDTERROR only ignores defense on those target types defined in battle_config.vit_penalty_target.
This change makes AM_ACIDTERROR ignore defense regardless of this setting and target type.
None
=> Fixed AM_ACIDTERROR not ignoring def on units other than players

src/map/status.c
Fixed Sage's free cast increasing aspd instead of decreasing it when free cast level is lower than 10.
Thanks @skyleo for the correct formula.
None
=> Fixed Sage's free cast increasing aspd while casting

.github/workflows/build.yml, .github/workflows/clang15_test.yml, .github/workflows/codeql-analysis.yml, .github/workflows/controller.yml, .github/workflows/gcc_test.yml, .github/workflows/gccold1.yml, .github/workflows/gccold2.yml, .github/workflows/gccold3.yml, .github/workflows/gccsnapshot_test.yml, .github/workflows/mariadb.yml, .github/workflows/mysql.yml, .github/workflows/tools.yml
A few more updates for our CI in Actions.
- Fix one issue that made pushes to master (e.g. for release) skip several tests (regression from #3238 ). Pushes unexpectedly uses the "controller" as workflow for every test, and this made some tests get the same key and cancel each other. We now have proper names for each test.
- Updated how PR tests are run to also use "controller" so we get the same flow for direct pushes and PRs. Note that the bot will still only trigger for master (due to the "if" condition in it).
=> Actions fixes and using "controller" for PRs

src/map/battle.c, src/map/skill.c
Fixed MO_TRIPLEATTACK not applying delay
Fixed Monk combo's delay formula
This PR fixes the following incorrect behavior:
- Monk's triple attack not displaying the attack animation correctly.
- Monk's triple attack not applying any kind of delay.
- Monk's combo delay formula increasing delay with dex instead of decreasing it.
None.
=> Fixed MO_TRIPLEATTACK animation being suddenly reset

conf/map/battle/misc.conf, src/map/battle.c, src/map/battle.h, src/map/clif.c, src/map/map.c
Added configuration option `keep_dir_free_cell`. Although it is set to false, I would like it to be enabled by default in Hercules.
This option allows discovery of free cells based on the unit's current facing direction instead of always using EAST, which have the following advantages:
- Improves distribution of mobs when dispersing after being grouped. This setting allows monsters to spread in a circular fashion instead of forming a long horizontal line.
- Allows characters to move more naturally if they came from the east, instead of walking back.
- In some instances, fixes issue #1241 allowing the user to obtain the item.
This commit also fixes #1241 in all scenarios not allowing the character to enter a walk loop. Fix based on rAthena's.
#1241 
[cont]: …
=> Added config option to keep direction for free cells

src/map/clif.c, tools/ci/travis.sh
- Terminate wrong connections to map server after two first bytes received.
- Fix error detection in running server from warning by maria db.
=> Different small fixes

src/map/script.c
Disallow using the command attachrid with RIDs from characters in autotrade, as the stack is empty and may crash the server.
Additionally, inform the user of what went wrong when trying to attach such RID.
#568 
=> Disable attaching scripts to characters in autotrade

db/pre-re/skill_db.conf, db/re/skill_db.conf
As expressed on the linked issue, the correct range for Soul Breaker/Destroyer is 9 cells instead of 7 cells for pre-re.
Gravity with its 2020 skill overhaul reduced this range in renewal to 4 cells. However, Hercules is not at that episode yet, so I've decided it's better to stay at 9 cells for renewal too.
#1104 
=> Increased ASC_BREAKER range from 7 to 9 cells

src/common/grfio.c, src/common/utils.c, src/common/utils.h
Adding wrappers for some file operation functions to support long offsets on windows.
I tested this by rebuilding the mapcache using kRO's 3.6GB GRF file, worked fine on both win and debian linux.
#2935 
=> Update grfio to work with big grf's on windows

src/map/skill.c
Fixed songs not triggering onleft or onout events when overlapping, thus changing the first song into dissonance.
Fix based on rathena's.
#1501
=> Fixed songs not triggering onleft events on dissonance

src/map/battle.c, src/map/battle.h, src/plugins/HPMHooking/HPMHooking.Defs.inc, src/plugins/HPMHooking/HPMHooking_map.HPMHooksCore.inc, src/plugins/HPMHooking/HPMHooking_map.HookingPoints.inc, src/plugins/HPMHooking/HPMHooking_map.Hooks.inc
Extract the conditions to start SC_BLADESTOP to its own function, since it has several conditions, and with the rebalance (#3253), more RE/Pre-RE differences.
And also fixes some mistakes in the logic, making it closer to official behavior. This affects both Pre-RE and RE.
Changes:
1. The target's equipped weapon no longer affects the range of Blade Stop. This applies for both Pre-RE and RE. In current code, a bare-handed monk would only blade-stop targets 1-cell away
2. Player attackers are only blade stopped from far away (> 2 cells) in Pre-RE -- My tests in renewal showed that a Hunter will only get blade-stopped if they are up to 2 cells away from the Monk.
Discussion here: https://github.com/HerculesWS/Hercules/pull/3253#discussion_r1394281487 . Copying skyleo findings:
```
So yeah, …
```
=> Fixes to Blade Stop (Root) trigger

src/map/map.c, src/map/mob.c
Remove target's cell from path calculation when CELL_NOSTACK is enabled
#574 
=> Fixed CELL_NOSTACK making mob ai not being able to reach target under certain conditions

src/map/status.c
Always let 1 luk be 0.33 crit (meaning 3 luk = 1 crit) just like on officials.
Basically when luk changed due to status effects such as Gloria and other cases, the crit difference was calculated via 0.3 crit per luk instead of 0.33.
Also only adding the difference on top can result in edge cases where integer arithmetic will round down to less than one should get, to prevent this we remove the old luk from our current crit first and recalculate with the new luk.
Verified in pre-re 11.2 and re 14.0
Inspired by https://github.com/rathena/rathena/pull/7938
**Issues addressed:** https://github.com/HerculesWS/Hercules/issues/3094
=> Fix crit not always being 0.33 crit per luk but 0.3 in some cases

src/map/battle.c
Restore snap_dodge functionality when dealing with extremity fist.
#638 
=> Fix snap_dodge setting not working for MO_EXTREMITYFIST

src/map/status.c
Fixes stat foods and stat cash foods being applied simultaneously and stacked one in top of the other. Also, only cash foods can overwrite normal foods (and not the other way around) according to @Kenpachi2k13 in this old PR #2741 
In addition, being the lesser evil, in this PR cash foods will overwrite the same type of food if the level is also the same. However, according to this comment in the aforementioned PR, cash foods should only overwrite stat foods if the effect is stronger, not equal. **Please, let me know if I should respect the quoted behavior and not let foods be overwriten by foods of equal level.**
> Also the the old effect will only be canceled if the new one is stronger. Using +1 STR cash food won't cancel +1 STR normal food.
#2489
[cont]: …
=> Fixed foods and cash foods being applied simultaneously

src/map/status.c
Fix some status change counters not being set to 0 when a mob unit dies.
#3196
=> Fix sc counters not being reset when a mob unit dies

src/map/clif.c
Fixes costumes blocking itemskills execution, even when items are being consumed.
Thanks to @skyleo and @guilherme-gm for the info regarding how costumes work in officials.
#2925 Partially, as there're two different issues being described in the comments.
=> Fix costumes blocking itemskills execution

conf/map/battle/feature.conf, doc/script_commands.txt, src/config/core.h, src/map/battle.c, src/map/script.c
Add safety checks to prevent users from enabling RoDEX account box in unsupported clients and improve documentation around it.
Also enables the account box by default. It was disabled back them because herc default packetver didn't support. But since we moved to default to a 2019 main client, account mail has been enabled on the client side, so there is no reason to keep it disabled by default.
With these changes:
1. Enabling the account mail in an unsupported client will give a warning and disable it
2. Users using supported RE versions need to also enable `ENABLE_RODEX_ACCOUNT_MAIL_RE_PATCH` because they must patch their exe ( https://gitlab.com/4144/Nemo/-/merge_requests/83 )
3. Trying to send account mails while the feature is disabled will show a warning, but still send the mail -- …
=> Add date checks and warns to RoDEX mail box and enable it by default

src/map/clif.c, src/map/pc.c, src/map/pc.h
Added a new flag to indicate sc data has been loaded and postpone clif->parse_LoadEndAck until all requirements are met.
When under heavy load, pc->reg_received runs before pc->scdata_received, thus invoking character calculation without taking any sc statuses like SC_PUSH_CART into consideration.
Along with incorrect character stats or substats, this issue makes the player not able to see visual effects or elements related to statuses, as well as the cart, until the player changes maps or uses a fly wing.
=> Fix sc statuses not loaded on time when under heavy load

src/char/char.c, src/login/login.c
Add a few more info when char-server fails to connect. This helps users understand what is going on, and may also help with support on forums/discord.
I chose to make this PR after noticing the Account ID check that is never mentioned anywhere and a new user stumbled into an issue in it today.
Those cases are now more detailed:
- login-server now records details for failure due to account ID range and wrong sex
- char-server now informs about the Account ID range. It doesn't detail the maximum value since people may be using 2 different builds, and `MAX_SERVERS` is part of login server, not common/char.
None
=> Add more details when char-server fails to connect

db/pre-re/skill_db.conf, src/map/clif.c, src/map/skill.c, src/map/status.c, src/map/unit.c
- Fix MO_TRIPLEATTACK animation not working when there's no possible chainable combo skill.
- Fix one cell movements when the target cell is occupied by an invisible object (like a gm using the hide atcommand).
- Remove incorrect afterCastActDelay in PA_SACRIFICE for pre-re.
- Removed fixed target on *some* combo skills. Monk skills act on the current targeted enemy even if last skill was used on a different enemy. Proof https://www.youtube.com/watch?v=XuQ775Eu9-o thanks to akiyammio.
All combo skills are set to current enemy unless we can prove otherwise.
- Fixed attackabletime being overwritten when an autotriggered skill increased the timing (e.g. MO_TRIPLEATTACK)
- Fixed combo delays applying to all SC_COMBOATTACK based skills and not sending the proper time to client.
**Issues …
=> Fix MO_TRIPLEATTACK animation, one cell movement, PA_SACRIFICE delay

src/map/clif.c
Setting combo_cache_skill was checking current skill's delay instead of checking for the last combo skill that produced the current delay.
=> Fix combo_cache_skill checking current skill delay instead of last one

.appveyor.yml
Looks like appveyor build is breaking after #3262 due to the rename/removal of the old solution names.
Just fixing it to use the single/new name of the solution.
Since we are no longer using multiple sln, I also removed the "matrix" config (which is meant to run several similar jobs with minor changes, in our case, 1 job for each sln)
=> Change appveyor config to use new/single VS sln file

src/map/pc.c
Allow expandinventory to return to original inventory size (minimal one).
See:
```
TehAroil 𝐏𝐋𝐕𝐠𝐠 — 11/01/2024 02:34
>Have 100 Possession Limit
>expandinventory(10);
>Now 110
>expandinventory(-10);
>Refused
>expandinventory(-9);
>Now 101
expandinventory(-1);
>Refused
>Have 101 Possession Limit
```
=> Fix expandinventory not allowing to return to minimal inventory size

src/map/clif.c, src/map/pc.c, src/map/pc.h
Don't unnecessarily call clif->pLoadEndAck, when we're receiving scdata and everything else from char to map in time.
in the following part I will talk about behavior before the changes this PR introduces:
As in don't call clif->pLoadEndAck manually if you haven't even received it from the client yet aka client didn't finish loading
Also yes we will get past the various checks if everything happened in time on server-side (as in the stuff we waiting from char-server to receive).
If we login fresh sd->bl.prev will be NULL for example.
So if we call clif->pLoadEndAck in this scenario, we will send data to the client and set data before the client actually finished loading.
[code]: …
=> Fix clif->pLoadEndAck being called in pc->scdata_received before receiving client's loadendack

src/char/int_party.c, src/char/int_pet.c, src/common/memmgr.h, src/map/instance.c, src/map/map.c, src/map/mob.c, src/map/npc_chat.c, src/map/script.c, src/map/storage.c
Since gcc-14 began running in our CI, we had been having random failures in `aCalloc` due to wrong order of parameters. For some reason, fixing one place doesn't necessarily triggers the error to the other one...
In this PR I looked through every place we use `aCalloc` and fixed the order to match the function expectations: `(number of elements, size of each element)`. While using in the reverse order works for the language, it fails in gcc-14 validation.
I also renamed the macro parameters to be num / size instead of m/n (which always makes me ask what each one is supposed to receive).
None, I think
=> Fix all aCalloc calls that had their parameters in the wrong order

src/map/skill.c
SC_AUTOSPELL val1 should be the AutoSpell skill level, not the selected skill learned level. This was broken during the refactor (#3237) and is now fixed.
Thanks to @violent01 for spotting the issue in the rebalance PR ( https://github.com/HerculesWS/Hercules/pull/3230#issuecomment-1941227650 )
Since it was now using the learned level of the selected skill, this lead to cases where switching the selected skill wouldn't work. For example, if you had Fire Bolt Lv10 and Earth Spikes Lv5 (their max), Lv5 would always be less than Lv10, and would be blocked by the default block of every SC (in status.c, which prevents a lower val1 from overriding a higher val1).
None
[code]: …
=> Fix AutoSpell not replacing selected skill in some cases

sysinfogen.sh
When trying to run `make`. `sysinfo.inc` will be generated.
I'm using Mac M1 the output of `SYSINFO_CPUCORES` is
```
// CPU Cores (Platform-dependent)
#define i ( 10 (8 performance and 2 efficiency) )
```
That will be make error while compile process:
```
sysinfo.c:1020:25: error: expected ')'
sysinfo->p->cpucores = SYSINFO_CPUCORES;
^
../common/sysinfo.inc:33:34: note: expanded from macro 'SYSINFO_CPUCORES'
#define SYSINFO_CPUCORES ( 10 (8 performance and 2 efficiency) )
^
sysinfo.c:1020:25: note: to match this '('
../common/sysinfo.inc:33:31: note: expanded from macro 'SYSINFO_CPUCORES'
#define SYSINFO_CPUCORES ( 10 (8 performance and 2 efficiency) )
^
1 error generated.
make[1]: *** [obj_all/sysinfo.o] Error 1
make: *** [common_sql] Error 2
```
Add quotation marks to call `HERC_CORES` …
=> Fix sysinfogen.sh get incorrect synctax SYSINFO_CPUCORES

doc/script_commands.txt, src/map/script.c
Allow call `openlapineupgradeui()` and `openlapineddukddakboxui()` without itemid
Example:
```diff
{
Id: 23926
AegisName: "Shadow_9_Refine_Hammer"
Name: "Shadow_9_Refine_Hammer"
Type: "IT_DELAYCONSUME"
-	Script: <" openlapineupgradeui(23926); ">
+	Script: <" openlapineupgradeui(); ">
},
```
=> Allow call openlapineupgradeui() and openlapineddukddakboxui() without itemid

db/re/sc_config.conf, db/re/skill_db.conf, src/map/battle.c, src/map/pc.h, src/map/skill.c, src/map/status.c, src/map/status.h
Introduces the rebalance of the first jobs skills. This change affects Renewal-only.
On official servers this came along with rebalances of 2nd jobs and transclass too. I am working in additional PRs for the 2nd jobs, being in separate PRs in order to keep those PRs in a reasonable size.
The implementation in this PR is based on kRO and kRO zero patch notes, iRO Wiki, rAthena and divine pride info, along with some in-game testing. I can't say everything is 100% accurate because there were discrepancies between different sources, and I could not test everything in kRO, but should be quite close.
I won't list all the changes in the PR description, but it may be checked in each commit text. Also, the commits are in the same order as they appear in the references below.
**Affected …
=> 1st jobs skill rebalance (2018 patch/Renewal)

src/map/clif.c, src/map/packets_struct.h, src/map/skill.c, src/map/skill.h, src/map/status.c
Fixes a few issues with Auto Shadow Spell.
1. When casting Auto Shadow Spell, we now properly check if there are skills copied with Intimidade/Reproduce before trying to get the skill_id
This prevents assertion failures due to the skill id being "0" (no skill)
In current code, this would still work, but cause a log about bad skill handling
2. Fixed a check that prevented you from switching an active shadow spell to another when their Skill ID was smaller (due to sc val1)
3. Fix assertion error when clicking "cance" or clicking "ok" in Auto Spell list without selecting a skill
As far as I could analyze, the client is not cleaning up the field that stores the current selected skill, so when you click "ok" it just sends a garbage id that may (or may not) be a valid skill. We now validate …
=> Fix issues with Auto Shadow Spell

doc/script_commands.txt, src/map/itemdb.c, src/map/itemdb.h, src/map/script.c
This PR aims to create a script function to get all items without duplicated from a specific `group_id`. The idea behind this is be able to get all items and be capable to create more complex NPC with it. Ideal for this is: use more groups feature to handle with a list of group in a easiest way without needed to create arrays of a item listing all itens you need, and instead of it, use groups list as resource in NPC.
In same PR i create an utilities tool set to clean duplicated from group in order to get only unique list from group.
Note: I add script command on `docs/script_commands.txt`  
Example:
```c++
getitemgroupitems(.@item_list[0], "Old_Card_Album");
for ( .@i = 0; .@i < getarraysize(.@item_list); .@i++ ) {
mes "^1E56BD\t"+getitemname(.@item_list[.@i])+" ^000000";
}
```
=> Add script function to work with item_group

src/map/status.c
This ensures that ATK/DEF percent is initialized for all bl-types, which it wasn't so it was defaulted to 0, resulting to no damage or 1 damage.
Also implements correct buff for ATK % (not the one of the atk percent behavior, but in general) of BS_OVERTHRUST for party members.
=> Add missing commit for (m)atk/(m)def percent implementation and one official behavior fix for BS_OVERTHRUST

src/map/status.c
Ensure clif->updatestatus is not called for non-player objects in relation to atk/def percent stuff.
*Accidentally pushed this to a branch on the main repo instead of my fork, gomen ne*
Follow-up to  https://github.com/HerculesWS/Hercules/pull/3290
Commit-reference to my private fork:
```
eb1dcf631508f12e92260119098b5712bb11b9a5
```
=> Fix sending clif->updatestatus to non-sd objects for percent-based stuff

src/map/atcommand.c, src/map/status.c, src/map/status.h
Make `@reloadskilldb` to load status types for skills that doesn't have `StatusChange` info in `skill_db.conf` such as the spirit skills.
**Issues addressed:** #3295 
=> Reload status_type on `@reloadskilldb`

db/pre-re/skill_db.conf, db/re/skill_db.conf, src/map/battle.c, src/map/skill.c, src/map/status.c
This PR depends on #3223 , all commits from #3223 are included in this one. The first commit original to this PR is:
> Rebalance of CR_GRANDCROSS (Grand Cross)
This PR by itself is ready and I don't think there will be further changes, unless someone finds an issue or a review asks for some change.
BUT, the rebalance in main official servers came at once, so I believe the right thing to do is to merge this PR together with the rest of the rebalance (that will be in other PRs).
So I will keep this as draft for now, but feel free to give an early review :)
The main purpose of this PR is to introduce the rebalance of part of the 2-2 jobs skills. This change affects Renewal-only.
On official servers this came along with rebalances of 1st, 2nd jobs and transclass too. I am working in …
=> 2-2 jobs skill rebalance (Part 1) (2018 patch/Renewal) and small skill fixes

src/map/pc.c, src/map/pc.h, src/map/skill.c
We address this by implementing logic to use SKILL_FLAG_REPLACED_LV_0 in SC_REPRODUCE and RG_PLAGIARISM.
We also reduced some code-duplication shared with pc_jobchange and skill_attack logic of those two skills.
SKILL_FLAG_PERM_GRANTED skills are no longer copyable as there's no clearly defined implementation for those when copied.
Note: A skill that one has the prerequisites for but one didn't level will appear as SKILL_FLAG_PERMANENT and have it's .id entry set in an `sd`'s status.skill[] entry.
Note: Well skills that you didn't learn, nor can learn, will also appear as SKILL_FLAG_PERMANENT, but can be distinguished via unset id.
Vaguely inspired by https://github.com/HeraclesHub/Heracles/pull/14
**Issues addressed:** #3289
List of commits in my private-fork that this PR is based on: …
=> Fix copying own skills via RG_PLAGIARISM or SC_REPRODUCE causing the skill to be deleted and skills that required it eventually.

db/re/size_fix.txt, db/re/skill_db.conf, src/map/battle.c, src/map/skill.c, src/map/unit.c
The main purpose of this PR is to introduce the rebalance of Monk job skills. This change affects Renewal-only.
On official servers this came along with rebalances of 1st, 2nd jobs and transclass too. I am working in additional PRs for the remaining 2-2, including bard/dancer, being in separate PRs in order to keep those PRs in a reasonable size.
The implementation in this PR is based on kRO and kRO zero patch notes, iRO Wiki, rAthena and divine pride info, along with some in-game testing. I can't say everything is 100% accurate because there were discrepancies between different sources, and I could not test everything in kRO, but should be quite close.
I won't list all the rebalance changes in the PR description, but it may be checked in each commit text. Also, the commits are in the …
=> 2-2 jobs skill rebalance - Monk (2018 patch/Renewal)

src/char/char.c, src/common/Makefile.in, src/common/charloginpackets.h, src/login/login.c
This fixes how packet 0x272D (CharServer -> LoginServer online accounts sync) is read by Login Server. Thus, preventing accounts from being wrongly marked as offline.
When login-server marks an account as offline, it will eventually tell API Server to disconnect them, thus also invalidating users' API Tokens while they are in game.
Huge thanks to AcidMarco in Herc's discord that provided a quite good explanation of what he has observed and this helped me a lot in finding the root cause (or at least I think it did...)
None, I think.
=> Fix server sync reading and wrong disconnection from API Server

src/map/script.c, src/map/script.h
- [x ] I have followed [proper Hercules code styling][code].
- [x ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.
Hi, I'd like to share my version of the `getpartymember` script command, similar to `getunits`.
This updated version no longer uses global temporary variables, which are prone to being overwritten, especially when multiple players call the function simultaneously. Instead, it requires the scripter to declare an array as an argument in the 3rd parameter of the command.
Additionally, this change introduces the following constants: `PT_MEMBER_NAME`, `PT_MEMBER_CHARID`, and `PT_MEMBER_ACCID`. The function now also returns the size of the party. …
=> `getpartymember` upgrade

doc/script_commands.txt
Update `getpartymember` doc following #3305.
none
=> Update getpartymember doc

tools/ci/travis.sh
The mysql client currently being used for MariaDB CI runs tries to connect with SSL to the test db. But our test db does not run in SSL (and doesn't have to).
This PR disables the SSL connection for MariaDB tests.
I had to limit to MariaDB v11 as some other tests (specially using MySQL) would fail because `--ssl` is not recognized by them.
=> Don't use SSL for MariaDB CI runs (Fixes CI)

doc/script_commands.txt, npc/custom/quests/hunting_missions.txt, npc/other/marriage.txt, npc/quests/guildrelay.txt, npc/quests/partyrelay.txt, npc/quests/quests_louyang.txt, npc/quests/quests_morocc.txt, npc/quests/quests_nameless.txt, npc/re/instances/MalangdoCulvert.txt, src/map/script.c, src/map/script.h
The getpartymember MRs #3305, #3307, #3308 should be merged into master at the same time, so they were collected into a temporary branch and will be merged through this PR once they're all in.
See #3305, #3307, #3308
=> getpartymember updates

src/map/script.c, src/map/script.h
Similar updates to `getpartymember` #3305 where global variables get overwritten by calling the command by 2 or more players simultaneously.
This update makes the command require an array as its argument and will return the size of the guild.
Constants are `GD_MEMBER_NAME`, `GD_MEMBER_CHARID`, and `GD_MEMBER_ACCID`.
Usage:
```
.@count = getguildmember(getcharid(CHAR_ID_GUILD), GD_MEMBER_NAME, .@name$);
for (.@i = 0; .@i < .@count; .@i++) {
consolemes(CONSOLEMES_DEBUG, ""+.@name$[.@i]+"");
}
```
Wrong data when …
=> `getguildmember` refactor

doc/script_commands.txt
Update `getguildmember` doc following #3310.
none
=> Update `getguildmember` doc following #3310

src/map/pc.c
Fix reproduceskill and cloneskill being used in checks when being zero
This resulted in for example skills gained temporarily by equipping which used SKILL_FLAG_REPLACED_LV_* to be not cleared when taking the equip off.
This bug was introduced in https://github.com/HerculesWS/Hercules/pull/3298
NOTE: It's debatable if the loop that recreates skill levels of SKILL_FLAG_REPLACED_LV_* and SKILL_FLAG_TEMPORARY skills should be part of pc->calc_skilltree_clear(..) as well. But that's refactoring and not in the scope of this PR.
=> Fix reproduceskill and cloneskill being used in checks when being zero

src/common/HPM.c, src/common/HPMi.h
Adds a validation when configuration registered by HPM are longer than the supported size.
Today it would silently fail because the registered key is shorter than the actual name, it would not work but also not alert because it simply didn't find and the defaults for `add*Conf` macros is to make them not required.
With this change, users would be informed that this configuration won't work so they can provide a shorter name or increase the define.
**Issues addressed:** None, I think
=> Validate length of configuration names from add*Conf HPM commands

src/map/skill.c
Ensure that on relog the previously removed plagiarized skill doesn't get re-added.
This was due to failure to clear the remembered cloneskill script variables and such.
As by the comment `[Aegis] can't overwrite skill of higher level, but will still remove previously copied skill.` this is official behavior, that if you had a plagiarized spell, something would attack you with for example Envenom 3, when you have Envenom 10, you'd then lose the plagiarized spell but not have your higher level Envenom overwritten.
*That being said I may consider changing it so that if it tries to copy the same level nothing happens. Or re-check if in Aegis this really will result in the removal as well, in case I missed the == case.*
[cont]: …
=> Fix previously plagiarized skill re-appearing after relog, when removed prior

doc/script_commands.txt, src/map/script.c, src/map/status.h
Add a new script command named `getunitparam` to obtain the values set via unit_parameters_db.conf which used to be obtainable via getbattleflag(...)
In relation to: https://github.com/HerculesWS/Hercules/pull/3214
NOTE: The deprecation warning of the deprecated keys for the battle flags, is not shown when using getbattleflag(..), but zero (or the default value) is silently returned instead.
=> Add *getunitparam to obtain values set via unit_parameters_db.conf in scripts

doc/script_commands.txt, src/map/script.c
Avoid use of global variables that tend to get overwritten when command is called by 2 or more players simultaneously.
The command now requires an array as the second or third argument.
The third argument is optional and, if provided, will copy the drop rates into the array.
Updated documentation to reflect these changes.
Usage:
```
.@count = getmobdrops(.@mob_id, .@item, .@rate);
if (.@count) {
mes(getmonsterinfo(.@mob_id, MOB_NAME) + " - " + .@count + " drops found:");
for (.@i = 0; .@i < .@count; ++.@i) {
mes(.@item[.@i] + " (" + getitemname(.@item[.@i]) + ") " + .@rate[.@i]/100 + ((.@rate[.@i]%100 < 10) ? ".0":".") + .@rate[.@i]%100 + "%");
}
} else {
mes("No drops found.");
}
close();
```
Wrong data when multiple players call the command.
[cont]: …
=> `getmobdrops` refactor

src/map/atcommand.c
Change mobinfo atcommand. Drop list now users item links.
=> Improved atCommand(mobinfo)

conf/messages.conf, src/map/atcommand.c
Uses itemlink on iteminfo atcommand.
No longer list slots on iteminfo, itemlink contains slot information.
=> Improved atCommand(iteminfo)

db/mob_db2.conf, src/map/skill.c
- Adds `Inherit` field to documentation in `mob_db2` 
- Fixes a comment about Magnum Break's auto attack modifier
=> mob_db2 inheritance doc

db/re/sc_config.conf, db/re/skill_db.conf, src/map/battle.c, src/map/pc.c, src/map/status.c
This PR introduces the rebalance of Lord Knight job skills. This change affects Renewal-only.
On official servers this came along with rebalances of 1st, 2nd jobs and transclass too. I am working in additional PRs for the remaining transclasses, being in separate PRs in order to keep those PRs in a reasonable size.
Most credits for this PR goes to @gbasso666, I built it over their changes on #3200, breaking into smaller commits and focusing only on Lord Knight skills. Commits in this PR that has their name, are the ones where most of the changes were picked from #3200.
Some changes of #3200 seems related to a future patch (e.g. SP cost of Concentration in 2018 was still in the old values), those were discarded, since the focus of this PR is on 2018 changes.
I can't say everything is 100% …
=> Lord Knight skill rebalance - 2018 patch/renewal

.github/workflows/clang15_test.yml
This switches the clang-15 builds to debian:stable since the package was dropped from debian:unstable.
A complete review of the build matrix adding tests on newer compilers and dropping ones that are no longer relevant, will be part of an upcoming release.
**Issues addressed:** N/A
=> Fix clang-15 CI jobs in GitHub Actions
